### ISSUE TITLE
German WW2 factions not purchasing JU-88s no matter how much money they have

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1008]
**Describe the bug**
Germany won't buy JU-88s, even if they have thousands of millions of dollars to spare.

**To Reproduce**
1. Start campaign
2. Give lotsa money to Germany
3. Pass Turn
4. See them buy zero JU-88s

**Expected behavior**
JU-88s having priority for ground attack missions

Preview #1391

**Comment by DanAlbert** [comment]
The simple reason this didn't work is because Ju-88s weren't in the list for CAS, strike, or DEAD. Now they are.

The complicated reason is that we also had the priority list and faction list swapped during purchase, so the faction's aircraft list was being used for purchase priority instead of our list 😱 It just worked out that the US jets are roughly in priority when sorted alphabetically...
