### ISSUE TITLE
Replace all random objective generation with campaign specified locations

### ISSUE THREAD

**Issue by sgtfuzzle17** [dcs-liberation/dcs_liberation#1076]
**Is your feature request related to a problem? Please describe.**
Currently, when building a custom campaign there are issues with being unable to guarantee a target-rich environment for strike aircraft, especially those that perform better when hitting static positions. The campaign generation can also (on smaller campaigns especially) clump up strike targets or generate very few coastal targets, which can lead to poor objective density/flow for the overall map.

**Describe the solution you'd like**
Adding the "placing a red version of a unit guarantees spawn" functionality that the IADS placement currently has to strike targets (both ground and sea) and ships would improve the ability of campaign authors to more precisely build a scenario with player experience in mind, while still allowing for randomization to keep things fresh.

**Comment by DanAlbert** [comment]
We have some of this coming up in 3.0 (factories are fixed spawns only), and ships were a thing I was strongly considering as well.

In general I'm trying to get us away from randomness in campaign spawning _at all_ since it can off balance a campaign so severely, but we haven't really discussed it much yet. I think we'd get sufficient interesting randomness from the relocatable SAMs FR that's open, and the rest just breaks in frustrating ways.

**Comment by DanAlbert** [comment]
Heard from @Khopa and @walterroach and we're all in favor. I'll likely do this work this weekend. It's mostly _deleting_ code so should be easy :)

**Comment by DanAlbert** [comment]
Support for all types of objectives as required objectives is now checked in. Will give folks a few days to convert their campaigns before ripping out the random gen code.
