### ISSUE TITLE
X axis of Liberation window unable to fit within a 1920x1080 screen

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1146]
**Describe the bug**
Unable to fit Liberation window on 1920x1080 screen because it is too wide.

**To Reproduce**
1. Have shitty 1920x1080 resolution monitor
2. Try to fit Liberation on screen
3. Fail

**Expected behavior**
Liberation should fit on shitty screens so ColonelPanic can't have nice things.

 - DCS Liberation [e.g. 2.3.1]:
#1694

**Comment by DanAlbert** [comment]
For anyone that wants to tackle this, if you don't have better ideas I'd recommend moving this crap

![image](https://user-images.githubusercontent.com/315852/119930500-68a85900-bf34-11eb-879f-c410ac86b27a.png)

Down here

![image](https://user-images.githubusercontent.com/315852/119930521-72ca5780-bf34-11eb-9bcf-f938fecd7ee7.png)

And tile them rather than a single row.

Could maybe move the takeoff/skip turn buttons too. Any more than that and we're probably just turning the too-wide-at-the-top problem into a too-wide-at-the-bottom problem.

Another thing to look in to would maybe be making the map a tab, and adding the statistics and intel pages as tabs rather than buttons.

**Comment by DanAlbert** [comment]
Another option:

![image](https://user-images.githubusercontent.com/315852/120265198-54c26700-c254-11eb-80cd-c7ce044bca29.png)

I've freed up a bunch of toolbar space. We could move the buttons settings/stats/air wing/transfers buttons into the toolbar.

**Comment by DanAlbert** [comment]
I think moving settings and stats into the toolbar probably won back enough? Leaving this open since there's room (ha) for improvement, but as long as it's not overflowing it's not necessary for 3.0.

**Comment by Starfire13** [comment]
The UI changes are now allowing Liberation to fit properly on my screen.
