### ISSUE TITLE
[Build 1703] Logistics System/Convoy Bug with Unreachable Frontlines

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#1147]
In this campaign that I am testing, I have two frontlines that are only connected via a blue CP and a factory on just one side of the fork. When I try to pass a turn where a convoy is created, I get the error shown below. 

I think that the factory in one fork is trying to send reinforcements to the frontline in the other fork but it can't find a valid path to it since the only path is through the blue CPs.

I found this one by accident as I forgot to add a factory to the other fork but I think that the intended behavior for this is that if there is no viable path from a factory to a frontline it just does not try to reinforce that frontline.

To reproduce:
1. load save/generate campaign provided
2. set all procurement to automatic
3. attempt to pass turn

![image](https://user-images.githubusercontent.com/72566076/120008404-c5852d00-bf8f-11eb-81a0-64b347ec1014.png)

[First_Lebanon_War_Convoy_Bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/6561871/First_Lebanon_War_Convoy_Bug.zip)

**Comment by DanAlbert** [comment]
![image](https://user-images.githubusercontent.com/315852/120048350-b623d500-bfcb-11eb-99d9-d5ebe4790425.png)

The _bug_ here is that we allowed Syrian Defensive Line (red front line FOB on the right arm) to recruit units from Beirut (with the factory) despite having no connection. I'll look in to that.

The maybe FR here is that the two lines of FOBs are not connected by airlift. I had only made airports (not FOBs) connected by airlift so that the system would prefer delivering units to transit hubs before dispersing them onto roads and ships, and also to allow FOBs to actually be cut off.

Was the intent here for the right arm to be cut off from supply, or to be resupplied by helicopter? If the former, I'll fix the bug and that's all we need. If the latter, we need to decide whether FOBs should be generally connected to the transit network by air, or if that should only apply to FOBs that have heliports (which are a WIP).

**Comment by DanAlbert** [comment]
Fixed the main issue (though that save can't be fixed because the problem is already present). Can discuss the other questions here but we should file an FR if that's a thing we decide to do.

**Comment by Mustang-25** [comment]
> Fixed the main issue (though that save can't be fixed because the problem is already present). Can discuss the other questions here but we should file an FR if that's a thing we decide to do.

I'll have to think about it a bit more but it would definitely present some interesting gameplay options if helo FOBs were connected.
