### ISSUE TITLE
Main Liberation Window

### ISSUE THREAD

**Issue by Meyomyx** [dcs-liberation/dcs_liberation#1216]
Amazing work on v3 ... astonishingly good! Thank you all so much.

**Is your feature request related to a problem? Please describe.**
An enhancement - It would be useful to be able to access (but not amend) the main Liberation UI window whilst the mission is in progress.

**Describe the solution you'd like**
When the progress window is active, to be able to scroll and zoom the map in the main UI window. Being able to review the active packages and their flight plans (obviously no changes would be possible) would be a bonus - allowing the user to review packages that have been planned. Failing that, the ability to at least minimise/resize the main window (even as a tickable option in the settings?). As it stands, it becomes a giant wallpaper and inevitably, the map isn't zoomed on the place you want to check!

Thanks again for this remarkable software

**Comment by DanAlbert** [comment]
Making everything read-only only while the mission is running is unfortunately a very large amount of work, and it's unlikely that's going to be a priority any time soon.

But as a workaround you can just close the mission results window, look around, and click takeoff again. I do it all the time and it doesn't seem to cause any problems. It's been several releases since doing that would break things.

**Comment by Meyomyx** [comment]
Ah that's useful to know - I always wondered about the interaction between Liberation and DCS. I'll try that

**Comment by DanAlbert** [comment]
Not feasible for the reasons above.
