### ISSUE TITLE
Mission script error upon loading on dedi

### ISSUE THREAD

**Issue by s3-chardonjf** [dcs-liberation/dcs_liberation#1218]
I started a new campaign with 3.0

I host the mission on a dedi so I opened it in ME, saved it, and started the server up.
Upon loading the mission, the dedi comes up with a string error:
![image](https://user-images.githubusercontent.com/29724443/121775056-940e8300-cb85-11eb-9485-4c683231c577.png)

Load up the liberation save and generate the miz by clicking take off, save it in mission editor, then load it up on a server.

Attached is the saved .miz

[liberation_nextturn.zip](https://github.com/dcs-liberation/dcs_liberation/files/6642119/liberation_nextturn.zip)
[save.zip](https://github.com/dcs-liberation/dcs_liberation/files/6642120/save.zip)

**Comment by dasrehzockt** [comment]
Experiencing the same problem when hosting in singleplayer. seems to be some kind of typo related to Al Tha'lah AB. (Humble Campaign in Syria)

EDIT: This Bug seems to be breaking the Humble Helper Campaign and maybe others that include Al Tha'lah AB as a Node. #1219
As a temporary workaround you should play campaigns that exclude Tha'lah
