### ISSUE TITLE
Request.  Purchase Larger Bomber Aircraft at Airfields

### ISSUE THREAD

**Issue by alcmann** [dcs-liberation/dcs_liberation#124]
Greetings.

Still loving Liberation, and what we currently have and the potential available for this.  Wish we had the ability to purchase F-117, B-52, B-1 etc. aircraft for potential AI Strike missions for enemy positions and vise versa.  

When owned airfield Added AI aircraft, not just possible modules, especially larger aircraft for bombing.  Similar to what we have with the AH-1, AH-64 for CAS.

**Comment by Qiou87** [comment]
Hi, this is available in some coalitions (like USA 1970). You get the B-52. But I have had a lot of problems with those if you spawn them at the airfield, due to the size of the plane it would collide with other AI planes and block the entire airfield. There is no option to spawn them in flight from the software, but I guess you can edit their spawn in the ME before launching the mission.

**Comment by alcmann** [comment]
Thanks Qiou87 for the response.  I can understand the Taxiway issues with the larger AIrcraft.  Im guessing B52/B-1 etc in the same category.

What about the F-117 ? Smaller fighter sized footprint. Can run automated strike tasking in the same group as the Viggen etc.  Especially in the Modern USA category.

Thanks

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/commit/85f66161854ee4c0562eccb2da3b8bf3677b0aa6
