### ISSUE TITLE
Blank White [interactive] Screen on Startup?

### ISSUE THREAD

**Issue by TheREALGovernor** [dcs-liberation/dcs_liberation#1281]
**Describe the bug**
When I first started Liberation 3.0, I received the "setup" dialog and it showed up fine, but the Liberation "form" loaded completely white, like there was an issue loading the form itself. 

I thought this was an issue with the install possibly opening an old save, or something "frozen", but after removing every last trace of Liberation and re-extracting a fresh-downloaded copy, I experienced the same thing - only I finally noticed my mouse was able to "interact" with the objects on the form (the map, the save buttons, etc.), though nothing was being displayed other than a blank white screen.

**To Reproduce**
1. Fresh install of Liberation
2. Launch liberation
3. Big blank white screen, nothing weird shows in command prompt box

**Expected behavior**
Not a big blank white screen - I need to be able to see the buttons and the map so I can purchase aircraft for the airports, save the game, launch the game, etc.

**Additional information**

I assume this is going to be some kind of .NET issue, so I'm working on making sure I have all of the latest updates and everything - is there something I'm missing though? I would note that I am remote from the computer (WAN connection) and have to either RDP (Windows Remote Desktop) or utilize GoToAssist to remotely access this computer. There could be something going on with the display driver there, but I don't really understand how this stuff is written so I can't speak to that. I'll try reinstalling.

**Version information (please complete the following information):**
 - DCS Liberation 3.0.0

**Comment by DanAlbert** [comment]
Sorry for not responding sooner. This gets filed every so often but no developer has ever been able to repro. Until that happens, there isn't anything we can do.

**Comment by Starfire13** [comment]
In case anyone else encountering this problem comes across this report, some potential fixes which users have claimed to work for them (but it appears, not for others) are to unzip the program using something like 7-zip instead of the built in Windows installer (I think it's more likely that it was just unzipped incorrectly the first time), and running Liberation as administrator. But as DanAlbert said, impossible to troubleshoot because the problem is not replicable and the alleged fixes do not even appear to work across different users.
