### ISSUE TITLE
Setting custom save game directory leads to error

### ISSUE THREAD

**Issue by MedievalBunny** [dcs-liberation/dcs_liberation#13]
If I select a non-standard directory for the save game directory under preferences I get a "no such file or directory" error in the running CMD window when I click on "Takeoff" and no mission will be generated. 

Using the "browse" button to reset this field to default does not clear the error, I needed to delete DCS Liberation and refresh it to clear the error.

**Comment by Khopa** [comment]
Yes, it has to be a DCS save game directory. 

If you want to fix the error you need to have a sub-directory named "Missions" in your custom directory, otherwise it causes an error. 

I was able to cause the error, but i could change the folder in preferences and fix it after. Not sure why you had to delete DCS Liberation.

**Comment by MedievalBunny** [comment]
OK, got it. The need for it to be pointed to a directory with a "Missions" folder in it, but not at the Missions folder specifically, is probably what caused my issues. That's a little unintuitive, but I have it working now with a custom file path.

I also got confused by the default file path in preferences using \ and custom file paths using /
