### ISSUE TITLE
Request for running the missions on a standalone server

### ISSUE THREAD

**Issue by zbenesch** [dcs-liberation/dcs_liberation#135]
Hi,
I can not currently see other ways to run the mission on a standalone server than actually running it on the server itself.
Is there a way to have the results imported from the debrief log of the remote host?
Thanks in advance!

**Comment by davidp57** [comment]
as said in the documentation, simply copy the state.json file to the computer running dcs-liberation

**Comment by davidp57** [comment]
We've released a version that makes playing the generated missions on a dedicated MP server easier.
To be quick, it now embarks the json.lua library instead of loading it from disk at runtime, and the state.json file is either stored by the server in the path set by Liberation when the mission has been first generated, or %LIBERATION_EXPORT_DIR%, %TEMP%, or to the DCS working directory.
It'll soon be documented in more details [here](https://github.com/Khopa/dcs_liberation/wiki/Dedicated-Server-Guide).
