### ISSUE TITLE
DCS Update DCS 2.5.6.55363 September 23, 2020

### ISSUE THREAD

**Issue by jasonmayr** [dcs-liberation/dcs_liberation#144]
The newest update Broke DCS Liberation fropm recording the missions. When you save them from Liberation to DCS, and in the reverse for after the mission is complete.

**Comment by DanAlbert** [comment]
Based on another report of the same issue, it's likely that you launched DCS after it updated _before_ launching liberation? Liberation needs to modify one of the lua files in the DCS install, and every time DCS updates that change is undone. It will be redone when you launch liberation, but if you launch DCS before you start the mission in liberation it won't have any effect.

Could you verify that launching the mission in liberation _before_ launching DCS makes the problem go away? Otherwise we probably need more info.

**Comment by DanAlbert** [comment]
Not enough information.
