### ISSUE TITLE
Unit cost rebalance

### ISSUE THREAD

**Issue by sith1144** [dcs-liberation/dcs_liberation#1505]
I am personally annoyed by the fact that ground units can cost as much or more than even the most high end of player flyables. I propose a rebalance based around the idea of making the high end multiroles like the hornet and viper roughly three times the price they are now, and simplifying the unit costs and basing them on simple tiers, as many of the subtle differences in capabilities dont matter all that much in the grand scheme of things. I am willing to go update unit costs myself, but basically wanted to run the idea by others. It is possible that with this change of costs basic income should be somewhat increased to make up for the planes being a lot more expensive.

The intended goal is that rather than choosing between a single plane or a single tank, you choose between a single plane or a platoon of tanks. This will hopefully make the battlefield a bit more filled out, and make enemy attrition matter a bit more in the air war.

I have attached my proposal for new unit costs. 

https://docs.google.com/spreadsheets/d/1d-GD0UWt5zJ4uuaqHgZsGIz50XE30Gvwy6I4nhKkkPY/edit?usp=sharing

**Comment by DanAlbert** [comment]
The prices you see are the result of a recent rebalance from someone else, so I think it's safe to say that this is just a matter of personal preference and it's impossible for us to do the right thing here because there's no one right answer.

Fortunately prices are moddable in the unit data yaml files. Given that, I don't think we should be overhauling price balances every release.

**Comment by Mustang-25** [comment]
Given your stated intent, I think a better (or at least different) idea would be to just decouple ground and air budgets so that the purchases are made from different money pools and maintaining the current features of starting budgets and income multipliers. It could accomplish what you want in balancing units and also add more functionality like just having factions with little to no air forces (or armies) depending on how you want to play a campaign.

**Comment by DanAlbert** [comment]
> decouple ground and air budgets so that the purchases are made from different money pools

This is why I've been pushing for getting rid of "money" in favor of factory production limits and pilot replenishment.

**Comment by DanAlbert** [comment]
There doesn't seem to be any interest from the development team to manage the incoming price balance suggestions. I know you're offering to do the work here, but it needs someone to own the review and to keep incoming balance suggestions from competing with each other, which does require a dev to want to work on it.

Modding is the answer here. Here's how the price is defined for the Hornet, as an example:

https://github.com/dcs-liberation/dcs_liberation/blob/91daabc9d28ae49e9759f2967e1ae5f10c9f65e6/resources/units/aircraft/FA-18C_hornet.yaml#L22

Every purchasable air or ground unit will have a yaml file with a `price` field that you can modify.

**Comment by DanAlbert** [comment]
(this can of course be reopened if someone decides they want to work on it)
