### ISSUE TITLE
Dedicated Server (state.json behaviour)

### ISSUE THREAD

**Issue by Pixinger** [dcs-liberation/dcs_liberation#155]
Hi,
First of all, great work and many thanks for the time invested in this development. We are playing the liberation with a group of up to 10 players and we really enjoy it.

However I would like to try to understand some behaviours a little better. 
Currently we enabled only at the dedicated server the `MissionScripting.lua` (in order to write the `state.json`). The clients run the mission with an unmodified version of this file (so they can not write the `state.json`). After running the mission, we pick the `state.json` from the dedicated, copy it to a locall PC and insert it manually back to the `liberation process`. All in all, this is working.
However, the players report error messages, that complain about not beeing able to write the `state.json` (of course! Because the `Missionscripting.lua` was not enabled). Besides the error message, the 'turn' seems to work just fine.

From my current point of understanding, I have two things, I would like to know more about.
1. Would it be _possible_ to generate a mission, that will NOT output any errors? I know for single-players and first-time-installers this is a very valuable feature. But in our case, where we are aware of the requirement to enable the `MissionScripting.lua`, it would be wonderful to have the option (maybe in the settings) to disable the warning. 

2. As it seems, the clients also write a state.json file. Will these file be identical to the state.json of the dedicated - or do we have some kind of locality issues? 
And if they are identical... would it be possible to disable the state.json processing on the dedicated server? 
If so, we could simply use the file from our local PC, which would minimize the manual file handling. Right now the server is crashing, if the `MissionScripting.lua` is not enabled. 
This would also have the nice side effect, that we would circumvent the 'security issue' to enable filesystem access for DCS on our dedicated squadron servers (as long as one voluntary player is taking the 'risk' to write the file). At least in our squadron there are some objections on this topic. 

Thanks for your hard work,
kind regards
Pix

**Comment by davidp57** [comment]
We've released a version that makes playing the generated missions on a dedicated MP server easier.
To be quick, it now embarks the `json.lua` library instead of loading it from disk at runtime, and the `state.json` file is either stored by the server in the path set by Liberation when the mission has been first generated, or %LIBERATION_EXPORT_DIR%, %TEMP%, or to the DCS working directory.
It'll soon be documented in more details [here](https://github.com/Khopa/dcs_liberation/wiki/Dedicated-Server-Guide).

Also, I'm positive the client DOES NOT run LUA from the mission which runs on the MP server, therefore will never try and write the `state.json` file.

**Comment by Pixinger** [comment]
@davidp57 Thank you for your information. I will keep an eye on the upcoming release!
