### ISSUE TITLE
generate_convoy IndexError: list index out of range

### ISSUE THREAD

**Issue by twwhiteside** [dcs-liberation/dcs_liberation#1553]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
Several weeks into Georgia Multipart campaign I'm now getting an IndexError: list index out of range error when - after planning the next round of action - I press the "Take Off" button.   Screenshot of error in console is attached (Liberation_Error.jpg).  It appears that deleting an offending "transfer of 1 unit" -  alleviates the issue; once that transfer is cancelled and I press "Take Off" the liberation_nextturn.miz mission is generated and I can seemingly proceed.  (see Liberation_Error_Transfer_UI.jpg screenshot; I've included the subsequent now working liberation_nextturn.miz file)

**To Reproduce**
1. Open Georgia Multipart 40_2 Russia 1990 v USA 2005.liberation (attached)
2. Click on "Take Off" 
3. See error in debug (cmd) console

**Expected behavior**
Naturally "Take Off" button should generate the liberation_nextturn.miz mission.

**Additional information**

Unfortunately I don't have the state.json generated prior to this error as I switched over to another campaign to get some play time in so that state file was overwritten.

We will usually need more information for debugging. Include as much of the following as you are able:

- Georgia Multipart 40_2 Russia 1990 v USA 2005.liberation: the offending Liberation save game (pre-removal of the problematic transfer)
- liberation_nextturn.miz: after "Cancelling transfer" of the 1 unit, and pressing "Take Off" this is the liberation_nextturn.miz generated.

**Version information (please complete the following information):**
 - v4.1.1 of Liberation is being used however the issue is present in 4.0.0 as well.

[Georgia Multipart 40_2 Russia 1990 v USA 2005.zip](https://github.com/dcs-liberation/dcs_liberation/files/6993437/Georgia.Multipart.40_2.Russia.1990.v.USA.2005.zip)
![Liberation_Error](https://user-images.githubusercontent.com/89027767/129586849-59243cd3-7ed8-4bfd-b007-a28fc4b521c2.jpg)
![Liberation_Error_Transfer_UI](https://user-images.githubusercontent.com/89027767/129586874-d9297958-116c-44a5-9f77-6b46db5d8618.jpg)

**Comment by RndName** [comment]
in the debug i can see that there are unit_types in the list of units which have 0 units in the convoy. this was the issue described and solved with #1411 This should not happen anymore using Version 4.1.0 or greater.

I also created a test campaign where i manipulated the state.json to reproduce this one by killing a whole convoy. Everything works perfectly with this fix as long as the submit was made using the Liberation Version >= 4.1.0. I think that this save file here was created and submitted to the current turn with Version 4.0 and therefore the fix was not implemented.

There are two workarounds available:

1. If the blocking Transfer is on the players side: Delete the transfer from the "Transfers" Menu.
2. if the blocking Transfer is on opfor side: "Pass Turn" should solve the issue when using >= V4.1

As there is no savefile and state.json for the previous turn we can not be 100% sure that V4.1.0 was used and therefore it is also not reproducible for me..

Glad that you found a way to solve the issue!

**Comment by RndName** [comment]
As reported on discord this can be reproduced using V5 by cheat capture a CP which is used as a convoy target. As the capture event happens the convoy is reduced to a size of 0 which then leads to the bug above when the user presses takeoff.

To reproduce: (build 5d89b9a)
[IndexErrorReproduceV5.zip](https://github.com/dcs-liberation/dcs_liberation/files/7704767/IndexErrorReproduceV5.zip)
Just cheat capture Damascus and press Take off

**Comment by RndName** [comment]
#1409
