### ISSUE TITLE
Virus detection in liberation_main.exe

### ISSUE THREAD

**Issue by warthogtk** [dcs-liberation/dcs_liberation#1557]
Hello.

When I unzip DCS Liberation, I got a threath alert from Bitdefender Antivirus.
The Gen:Variant.Bulz.462489 was found in liberation_main.exe

![DCS Liberation - Bitdefender](https://user-images.githubusercontent.com/827680/129690368-10436bed-42c1-4fe2-ab60-3a0bb6471569.PNG)

Is it a known issue/false positive ? Or could it be a real alert ? 

Thank you in advance.

Arnaud.

PS : sorry for my bad english , I'm french.

**Comment by DanAlbert** [comment]
False positive.

**Comment by Khopa** [comment]
Hello Arnaud, Dan

I also submitted our .exe to Bitdefender support, so they will manually review it, and whitelist it in their database.

This false positive can often happen with antivirus checking for similar pattern in binary code. This happen fairly often for Python programs compiled with pyinstaller like liberation, because it means that it will share similarity with thousands of other programs compiled this way, including malicious ones.

Whole code source of the project is available to check here on the Github repo, and the build of the exe is also done automatically online on Github from the source, so no one could have injected additional malicious code in it. Just make sure to always download liberation from the official Github repo to avoid any issue.

Regards, 

Khopa

***

**Resources for fellow devs and project maintainers :**

- https://github.com/hankhank10/false-positive-malware-reporting
has a list of link to report false positive to antivirus vendors. But we'll have to it for every new version, which will be tedious.

As mentionned in this page, we could also get a certificate (60€/year) to sign the .exe file, which means the antivirus vendors would be more inclined to trust us.

Also did a virus total report for the liberation_main.exe (4.1.1) : 
- https://www.virustotal.com/gui/file/a708f47cd1db63849dd9a2a43993fef7d46071edf0b8737f6c30a18c536c11be/detection

Others resources : 
- https://medium.com/@markhank/how-to-stop-your-python-programs-being-seen-as-malware-bfd7eb407a7

**Comment by rbz518** [comment]
https://www.virustotal.com/gui/file/6164f8eb90818ed4916c53110c9dbf272bde85bcd854634cab6e8516775b8730?nocache=1

![image](https://github.com/dcs-liberation/dcs_liberation/assets/13086804/5c4c0f81-b756-4f86-99d2-f8a7bc35e2bd)

This looks pretty bad.

**Comment by Starfire13** [comment]
> https://www.virustotal.com/gui/file/6164f8eb90818ed4916c53110c9dbf272bde85bcd854634cab6e8516775b8730?nocache=1
> 
> 
> 
> ![image](https://github.com/dcs-liberation/dcs_liberation/assets/13086804/5c4c0f81-b756-4f86-99d2-f8a7bc35e2bd)
> 
> 
> 
> This looks pretty bad. 

False positives of this sort are not unexpected. We have no control over what all these antivirus software flag as a threat. Liberation is open source and you can look at the code if you wish. There is nothing harmful in there. I will say that in all these years, there has not been a single report of any user having caught a virus from Liberation (provided it is downloaded from the official Github repository of course).
