### ISSUE TITLE
SEAD palnes don't fire 

### ISSUE THREAD

**Issue by Dovahkiin-r** [dcs-liberation/dcs_liberation#1560]
Problem: SEAD Planes wont fire at SAMs  (in this case HAWK site). If they stay alive they fly over them and wont fire at them.
tested planes: su25t, su24
Mission: SEAD
Skynet: on

Solution:
Both planes were set to CAS on mission edditor. I changed that to sead, deleted all SEAD refs and cleaned ingress waypoints tasks then added Search and engage in zone task to ingress waypoint and puted the zone on sam site.
Also the ALT of the waypoint that is on SAM site is 0.
That should also get change to for example 6000.

Result:
Worked Perfectly.
SAM off --> SEAD aircraft in SAM firing range ---> SAM on ---> SEAD fire/ SAM fire (most of the times SEAD fires first) ---> random event (most of the time SAM's Raders got distroyed)

**Comment by Lspd-officer** [comment]
use dead

**Comment by Starfire13** [comment]
> Also the ALT of the waypoint that is on SAM site is 0.

This is intentional so that players can slave TGP to waypoint.

**Comment by adrielparedes** [comment]
> > Also the ALT of the waypoint that is on SAM site is 0.
> 
> This is intentional so that players can slave TGP to waypoint.

But what about AI? If we need the AI to do SEAD so we can DEAD, or at least do other missions?
SEAD is prefered for Human players? I had the same problem and may be that it is not the intention to have many AI missions that flies with you, but for instance if you only want to do BARCAP you can't disable SAM sites without a big number of loses because you can't do SEAD.
Everything I'm saying could be wrong so I wanted to open that discussion here if it is possible.

Thanks for all the effort!

**Comment by DanAlbert** [comment]
AI don't have a target waypoint so the altitude is irrelevant.

Idk why this was kept open. No save game.
