### ISSUE TITLE
start all squadrons with a predetermined number of aircraft?

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#1583]
Now that the air wing configuration and layout is a part of the campaign definition, we could make the _size_ of the squadron also be a part of that configuration and start the game with full squadrons. We'd also reduce the default starting budget to account for the fact that no aircraft need to be purchased on turn 0.

**Comment by DanAlbert** [comment]
Toying with this and it looks interesting, but has a significant enough effect on turn 0 that I don't want to do it for 5.

**Comment by rabauke80** [comment]
as per our Discord discussion earlier today, I wanted to have my suggestion documented in git. As I've understood, some of the points are already underway. As it's part of a larger scope, I marked the line that directly relates to this ticket with bold formating.

re-design of the budget system:

- remove starting budget completely
- **introduce amount of aircrafts as part of the faction or squadrons definition as a starting point** (e.g. fictional number, USN 2005 goes to war with 12x F/A-18C, 12x F-14B, etc...)
- introduce operational costs per aircraft, rather than cost to buy
- use income to cover operational costs and resupply
- resupply of airframes comes at a fixed delay in turns, which could be also defined in the faction definition, to represent the military economic strength of a faction in that period of time (shorter for stronger factions, longer for weaker factions)

**Comment by DanAlbert** [comment]
One bug per bug please. We cannot track comments, only bugs. The ready of those are dups anyway.
