### ISSUE TITLE
Allow user to change the JTAC Autolaze code.

### ISSUE THREAD

**Issue by apothecari** [dcs-liberation/dcs_liberation#1585]
**Is your feature request related to a problem? Please describe.**
A group of us we're running a custom Russian PMC with SU-25T and SU-25's and were slightly annoyed that we couldn't use JTAC Autolaze for ground with the Chinese Winglong drone.

**Describe the solution you'd like**
The default code for FC3 aircraft and their laser guided weaponry is 1113, a change to this code would allow the 3 FC3 aircraft (A-10A, SU-25T, and SU-25) to use the JTAC Autolaze.

Suggestions:
1. Change the default code of the JTAC Autolaze to 1113. (Probably the easiest solution).
2. Allow the input of a custom JTAC Autolaze in the DCS Liberation Campaign manager.

**Comment by MetalStormGhost** [comment]
I have implemented a potential fix by adding a toggleable option to the plugin settings which will force the JTAC laser code to 1113 when the option is activated. The default setting is off.

I figured there's no need to have a custom code since all other airframes apart from FC3 (and Ka-50, which have separate codes) can just set the code freely. All comments are welcome.

**Comment by apothecari** [comment]
This is great, perfect and simple fix for the system. 

Thank you.
