### ISSUE TITLE
Viper start error

### ISSUE THREAD

**Issue by Rogue-Reaper13** [dcs-liberation/dcs_liberation#16]
Starting mission in viper on Persian Gulf map. Cold, warm, and runway mission start only spawns in mid flight. Great mod. Thanks for your time!

**Comment by Khopa** [comment]
Thanks :)

Which airbase was your Viper operating from ? 

Sometimes, when there are not enough parking slots, i have no choice but to start the aircraft in the air; and there are some airbase on PG with very few parkings slots..

**Comment by Rogue-Reaper13** [comment]
I believe it was fujairah that was the spawn point. If I remember right, I
had 2 froggys, 4 eagles, and my 2 vipers. I haven't played the gulf map
quite as much as Caucasus, so I don't know the ports as well. I'm really
enjoying this campaign so far. Also, WW2 I tried to setup using the fw-190
dora, and it said something about wrong radio frequency on mission editor.
Thanks for your time and response!

**Comment by Khopa** [comment]
Yes, Fujairah airport has only 4 parking slots in DCS while there would be room for much more. :(
I could make it so player slots are priorized regarding parking slots allocation though.

Thanks for reporting the issue with FW-190, i'm indeed giving it a wrong frequency, it doesn't allow the same frequency as allies warbirds asi thought so. It will be fixed in next release, for now you have to manually edit the mission and replace 124Mhz by 40Mhz in the radio field. But it's tedious.

**Comment by Rogue-Reaper13** [comment]
Glad I could help with the war bird. And that's exactly what I did for a
mission with the freq. It is tedious, but at least there is a work around
for now! As for the fujairah port, it really isn't much of a bother to
change load out in the campaign map, or to just load in 4 airframes only.
Since it is start of the campaign it's really not a big deal.

**Comment by Khopa** [comment]
This should be fixed in 2.0.10 (All flights starting in the air after playing a few missions)

Please re-open if you encounter the issue again.

**Comment by Rogue-Reaper13** [comment]
That's excellent! Thanks for letting me know! Look forward to getting home
and trying out the new features
