### ISSUE TITLE
Carrier-capable aircraft cannot be placed at airfields by campaign designers

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1621]
**Describe the bug**
Defaults for the squadron bases field exclude carrier capable aircraft from shore-based airfields. This means squadrons of carrier-capable aircraft like Tomcats and Hornets cannot be placed at airfields.

https://i.imgur.com/hUzl8P8.png

**Expected behavior**
Campaign designers should be able to place squadrons with carrier capable aircraft at airfields.

While this can be fixed by placing
bases:
    carrier: true
    shore: true
in the YAML file of every single carrer capable aircraft squadron, it would be preferable to just fix the defaults in /squadrons/operatingbases.py

**Version information (please complete the following information):**
 - DCS Liberation #2880

**Comment by DanAlbert** [comment]
> it would be preferable to just fix the defaults in /squadrons/operatingbases.py

That's not what this is for. It's just a hint to any AI decisions about what to do with the aircraft. If `shore: false` and `carrier: true`, the squadron will prefer a carrier over an airbase when retreating, but it won't _prevent_ an airbase from being used if there are no viable carriers. Before squadrons had assigned bases it was also a hint to the procurement AI about where to buy aircraft.

The bug is that campaign designers can't override.
