### ISSUE TITLE
FOB FARP objects showing in generated mission; AI not purchasing helos to fill FARP slots

### ISSUE THREAD

**Issue by sgtfuzzle17** [dcs-liberation/dcs_liberation#1629]
**Describe the bug**
FARP objects placed to give FOBs helo capability will show BLUFOR Invisible FARP objects for OPFOR in the mission. They also don't want to buy helos to fill those FARPs; unsure if that's related or just autopurchaser fuckery. Do note that Lib is seeing them as air slots in the program itself.

**To Reproduce**
Implement FARP capability as standard in dev build. Note that this has been reproduced by me so far in two different campaigns.

**Expected behavior**
These icons should be invisible as standard for OPFOR units/statics in mission. Note that I have my unit map markers setting set to "allies only", so these showing is weird.

[bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/7205386/bug.zip)

**Version information (please complete the following information):**
 - DCS Liberation devbuild v5.0.0-2872-preview
![image](https://user-images.githubusercontent.com/49757384/134227985-2c7d007d-7220-4524-bcc4-0dba40171c9e.png)

**Comment by DanAlbert** [comment]
> BLUFOR Invisible FARP objects for OPFOR in the mission.

 Nope. They're neutral to avoid breaking base captures with invincible objects.

> They also don't want to buy helos to fill those FARPs

Using scenic route, helicopters are not being purchased at FOB Seerik for BAI missions because they are too far away.

Not buying helicopters for CAS is a quirk of turn zero and the fact that purchases are based on what was needed but unavailable in the current turn (predicting what will be needed next turn is not really possible since there's no way to know how many aircraft or ground units will be lost). Since the opposing team has no ground units the planner doesn't try to plan CAS, so no order is placed for CAS. One turn 1 CAS is planned because CAS _is_ needed then, but it's able to find aircraft for CAS that were purchased for other roles in turn 0.

Resolved that by skipping any frontline stance actions if there are no ground units to assign the stance to in the first place; and prevented planning CAS when no targets were available, except on turn 0. CAS will be "planned" (checked for purchase reasons) on turn 0 regardless of target availability. In the unlikely case that the enemy doesn't buy any ground forces this might result in two extra aircraft per front, but that's something that should never happen anyway.
