### ISSUE TITLE
SA-13 not generate in game, so the mission cannot been completed

### ISSUE THREAD

**Issue by Burnyice** [dcs-liberation/dcs_liberation#1666]
The SA-13 Gophers are not generated in the game, so they cannot be destroyed. 
![1](https://user-images.githubusercontent.com/93006161/138502141-e5485981-acbf-4468-8a41-bfe20ea26d63.PNG)

The mission planner always tries to set up dead missions for them, but nothing happens after the AI takes off.

**Comment by Starfire13** [comment]
Please use the reporting template. We don't know what version of Liberation you are on, which campaign you are on, there is no save file attached, etc.

**Comment by Starfire13** [comment]
SA-13s showing up fine in #2942

![Capture](https://user-images.githubusercontent.com/72491792/138529921-50aa6e3b-4575-4c8e-8d01-95c20fe1cc1a.JPG)

**Comment by ali4000** [comment]
I believe this is due to the unit name mixup/DCS bug mentioned in https://github.com/dcs-liberation/dcs_liberation/issues/1450
The problem is not with the SA-13. The problem is with the SA-8 generating a non-existant SA-8 reload vehicle, that will never spawn, but Liberation mistakes it for an SA-13 due to the name mixup/duplication issue. It's harmless because the unit doesn't actually exist, and won't hinder base capture. The AI auto planner might decide to try to DEAD it though, since the unit sticks around in Liberation until its controlling base is captured...

**Comment by RndName** [comment]
#2033
