### ISSUE TITLE
Campaign airfield/role definitions preclude all but the first aircraft type defined

### ISSUE THREAD

**Issue by Slowdive1123** [dcs-liberation/dcs_liberation#1678]
1. Create a new campaign of type "Syria - Operation Peace Spring" using default factions
2. Note that the E-3A is not available for purchase even though it is defined for Bluefor Modern
3. The E-2 Hawkeye is defined as the primary AEW&C aircraft type in operation_peace_spring.yaml
4. Add the E-3A as a second aircraft type
5. Reload Liberation, recreate campaign and E-3A still does not appear
6. Also tested by flipping the F-18 and M-2000 order for TARCAP from

 - primary: TARCAP
      secondary: any
      aircraft:
        - Mirage 2000C
        - F/A-18C Hornet (Lot 20)
       
to

 - primary: TARCAP
      secondary: any
      aircraft:
        - F/A-18C Hornet (Lot 20)
        - Mirage 2000C

7. Reload Liberation, recreate campaign and Mirage 2000C magically disappears from the campaign and is unpurchaseable

Summary:

It appears that only the first aircraft type in the definition for a particular airfield/role is being loaded into the campaign.

**Comment by Starfire13** [comment]
This is not a bug. The aircraft list is hierarchical. This means that if the Mirage is at the top of the list and is available, it is selected as the squadron aircraft. If not, it tries the second aircaft on the list. The reason I have it set up this way is so folks can use either BLUFOR Modern or USA 2005. If you want to use the E-3A instead of the E-2C, either set it as the first aircraft type on the list or simply replace the E-2C with the E-3A.

**Comment by Slowdive1123** [comment]
Interesting. I would then suggest modifying the available aircraft list in the campaign setup based on the airfield/squadron file. Otherwise, the end user will likely get pretty confused if they see the F-18 is available and then get into the campaign only to find out that it is not, due to not being primary in any role category.

Also just to clarify that I understand this correctly. If an aircraft type is not defined as primary for an airfield/squadron role, then that type is not available anywhere in the campaign despite being defined for the faction.

**Comment by Starfire13** [comment]
But the F/A-18 _is_ available. It's just that if you pick BLUFOR Modern, you get only 1 Hornet squadron (because one of them becomes a Mirage squadron). If you pick, say, USA 2005, you get 2 Hornet squadrons.

> Also just to clarify that I understand this correctly. If an aircraft type is not defined as primary for an airfield/squadron role, then that type is not available anywhere in the campaign despite being defined for the faction.

Yes. Eventually, you will be able to swap aircraft type for another that can fill the same role. But for now, you will have to edit the yaml.

**Comment by Slowdive1123** [comment]
Sorry, I should not have used F-18 as an example as it confuses the issue. I simply meant that an aircraft of some type (F-16 for example) might appear in the list of aircraft for a faction such as Bluefor Modern, but then when the player gets into the campaign they cannot purchase any F-16's if they are not defined as a primary type for an airfield/role.

Don't get me wrong, I really dig the squadron functionality, but I think it's confusing due to the old mechanic of being able to purchase any aircraft that is defined for a faction. That no longer appears to be the case. For example, if I want to play the above mentioned campaign and I want to roll all F-16 squadrons, if F-16 is not a primary type for any airfield/role combo then I won't be able to buy them at all. I know I can edit the campaign.yaml and make them primary, but down the road I'm not sure how it'll all work.

I guess I should wait to see the finished UI to fully grasp your intention.

**Comment by Starfire13** [comment]
You could fly a campaign setup for F-16s with Spitfires if you want, if you pick a faction that has them. The faction file will always contain all the aircraft that faction has available to them. A campaign designer isn't going to tailor a campaign to every possible faction. He simply sets certain defaults based on his preferences. This should hopefully no longer be an issue in the release build because players would be able to pick the aircraft they want to fill that role (provided it is implemented by then), instead of sticking with the defaults. In the current dev build, this simply isn't implemented yet.

**Comment by Slowdive1123** [comment]
Understood. Thanks for the explanation. Sorry for wasting your time but I just wanted to note this in case it was a bug. Take care.
