### ISSUE TITLE
Default squadrons for all airframes

### ISSUE THREAD

**Issue by JeffreyCor** [dcs-liberation/dcs_liberation#1722]
With present squadron system as discussed on Discord the air-frames are limited in any given campaign to what is included in the campaign. Can and does leave air-frames unusable within a faction. This is extremely annoying to have to modify each file with what it thought may be used for each campaign.

I suggest on start at least 1 default squadron of each air-frame type is included. This could be an option to limit squadrons to only those defined in the campaign or include default squadrons. This would give a reasonable balance between continuing the user freedom as there has been with the squadron control currently implemented.

**Comment by DanAlbert** [comment]
This is up to the campaign designer. You can mod the campaigns trivially to add what you want if you don't like the campaign.

**Comment by JeffreyCor** [comment]
That was addressed in my post.

**Comment by DanAlbert** [comment]
Right, I'm saying "This is not going to be implemented because..." What you're suggesting doesn't work because the squadrons need to go somewhere and placement can't be usefully done automatically. That's _why_ the campaign designer needs to do this.

Someone could send a patch to add an "add squadron" button to the air wing config menu, but since it's so easy to do that by modding the campaign definition so far no one is interested in spending time on that. If you send a PR implementing it we'll happily review it.

**Comment by JeffreyCor** [comment]
Well, "easy" is certainly subjective and sometimes things that can be done aren't necessarily things that should be done. All I can do it put out the idea.
