### ISSUE TITLE
AIM-9P for F-15?

### ISSUE THREAD

**Issue by MedievalBunny** [dcs-liberation/dcs_liberation#18]
The default loadout for the F-15C has two AIM-9Ps? Is that a (strange) intentional choice or a mistake?

**Comment by Khopa** [comment]
Yes this is not ideal. This will be fixed in the next version.

I changed AIM-9P by AIM-9M, and AIM-120B by AIM-120C for the next version.

I know i could even replace the two remaining AIM-9 by AIM-120, but i do like having some Fox 2 for close range, at least on the F/A-18C.

You can patch your DCS Liberation installation by replacing the file <DCS Liberation directory>/resources/customized_payloads/F-15C.lua by the one provided in the archive here :

[F-15C.zip](https://github.com/Khopa/dcs_liberation/files/4962919/F-15C.zip)

**Comment by Khopa** [comment]
Fixed in 2.0.10, F-15C will spawn with AIM-9M instead of AIM-9P.
