### ISSUE TITLE
Times for waypoints are not consecutive

### ISSUE THREAD

**Issue by Brausepaul** [dcs-liberation/dcs_liberation#1848]
**Describe the bug**
I noticed that after generating a campaign mission, the times for the mission's waypoints are not consecutive. The attached screenshot (in the archive) shows that the time for WP 5 is actually before WP 4.

**To Reproduce**
Sorry, I have no steps to reproduce this.

**Expected behavior**
All waypoints should have consecutive mission times.

**Additional information**
I added several files related to the bug described.

**Version information (please complete the following information):**
 - DCS Liberation 5.0
 
[Bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/7728689/Bug.zip)

**Comment by DanAlbert** [comment]
> Sorry, I have no steps to reproduce this.

The save game is the part we need on this bug and it looks like you attached that, so no worries :)

**Comment by HILOK** [comment]
i had this happen a lot on "PG scenic route", if this info is of any help. it also messed up the ETA/GS waypoint properties in ME: all red.
can't provide any files right now, but i could next week, if needed.

**Comment by DanAlbert** [comment]
@SnappyComebacks am I remembering correctly that you'd seen this and had a fix in mind?

**Comment by HILOK** [comment]
seems to be the case also for other campaigns than scenic route i mentioned above. just checked marianas pacific repartee.
also only A-G missions seem to be affected, as inconsequent timings apply between WYP TGT and WYP SPLIT. looks to me as if SPLIT is placed directly after INGRESS internally (TARGET left out). not sure though: when you look at the pix attached, the problem seems to resolve, if INGRESS is placed closer to TGT. timings seem coherent.
![lib-02](https://user-images.githubusercontent.com/76898536/152681227-c17d2d06-474c-490d-a2fc-fa9e69024d96.JPG)
![lib-03](https://user-images.githubusercontent.com/76898536/152681231-95f3aced-c86d-44ea-a731-f65031d89f2f.JPG)

**Comment by Starfire13** [comment]
The target waypoint is only created for player flights so you can slave TGP to the target. AI flights don't need that. They are given their attack orders on the ingress waypoint.

**Comment by HILOK** [comment]
ok, thanks for the info. anyway the problem remains for players: times on kneeboards are incorrect, and fuel planning becomes inaccurate.

**Comment by DanAlbert** [comment]
This was fixed in 532ac261ff359c36e40e07b922d2da3083c28798
