### ISSUE TITLE
Livery selection for Airwing Configuration Dialog

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1861]
**Is your feature request related to a problem? Please describe.**
The upcoming changes to the airwing config dialog look excellent, but one additional feature it would benefit from is an ability to select a custom livery for each squadron. This could be implemented for just the squadrons not using squadron presets (i.e. the ones with random nicknames), or act as a livery override for preset squadrons if a preset squadron is selected (depending on difficulty), either would be fine.

**Describe the solution you'd like**
Preferably, liveries from both the official liveries in each aircraft's folder in \DCS World OpenBeta\Mods\aircraft\ as well as community made liveries placed in \Saved Games\DCS.openbeta\Liveries\ would be selectable.

**Comment by DanAlbert** [comment]
If we can't preview the livery in the UI, is this still useful?

**Comment by Starfire13** [comment]
I think so. We can still get a pretty good idea of what the livery is from the name (e.g. Jolly_Rogers_CAG, VFA_194_lo_vis, A10C_FedEx, My_Little_Pony_P51), and in my case at least, I have a bunch of favourite liveries I like to switch between, and I would know their names.

**Comment by Raffson** [comment]
I think it would be best to rely on pydcs for this, it already contains some custom liveries as well so that makes it easy in a way. However I'm still in favor of scanning the Saved Games folder so all custom liveries would be supported, which is what I'm trying to figure out at this point.

Though there are some drawbacks with using pydcs. One possible problem is the fact that these custom skins in pydcs won't work if the user doesn't have them installed, but normally DCS will just fall back to the default livery so it's a debatable issue. The second thing is slightly more problematic, i.e. we depend on pydcs to be correct and up-to-date as well as the fact that once an update occurs, liberation also needs to release a new version. You could work your way around this by taking the new livery and adding it to your custom liveries, given that we're scanning Saved Games of course. So all this puts me in a weird spot because on one hand I'd want to go with pydcs, but on the other hand I'm thinking it'd be better to actually scan the required directories at startup.

I think the best way to move forward now would be to get something viable to work for scanning custom liveries in Saved Games, and from there perhaps adjust the algorithm so it could scan the installation folder too. Either way, I would need to base myself on a list of all available aircraft for this, as well as knowing where to find their liveries. Would it make sense to use [resources/units/aircraft](https://github.com/dcs-liberation/dcs_liberation/tree/develop/resources/units/aircraft) for this? It looks like the filenames correspond to what the folder-names should be in Saved Games, and if that's the case it would make my life a lot easier. It only solves half the problem though because scanning the installation folder is a little trickier, mainly because liveries are not located in one single place like they are in the Saved Games folder...

**Comment by DanAlbert** [comment]
If it's possible to do this by scanning, send that PR to pydcs IMO.

**Comment by Raffson** [comment]
> If it's possible to do this by scanning, send that PR to pydcs IMO.

Yeah I've been looking at it for a while now but the fact that the liveries are hard-coded in pydcs makes me wonder... Is it generated code or something? Or is `pydcs\dcs\planes.py` maintained manually?

I know I can make a "scanner" for custom liveries in Saved Games, it'll take a couple of hours to get it right but it's definitely within reach. Once I have all that, there's parts I could reuse in my attempt to scan the install directory.

My point is the following, I don't see how a scanner fits within pydcs, unless you want to use this "scanner" to generate code?

Either way, let me first mess around with the custom liveries, cause that would definitely be a step in the right direction.

Oh yeah and another fun thing to note, the install directory contains liveries in zip-files, ~~those are also hard to scan~~

Edit: turns out zip-files are just as easy 🤣

**Comment by DanAlbert** [comment]
It's generated automatically (look in the tools directory). If you're able to scan, pydcs could do that instead. The less that we have to pull out of DCS with that extractor the better.

**Comment by Raffson** [comment]
> It's generated automatically (look in the tools directory). If you're able to scan, pydcs could do that instead. The less that we have to pull out of DCS with that extractor the better.

I'm confused, what file are you referring to exactly? I'm looking in `resources\tools` but can't seem to find something that relates to aircraft generation...

Edit: nvm, found it in pydcs

**Comment by Raffson** [comment]
Good news, I have something preliminary that scans custom liveries in the saved games folder. ~~Currently not accounting for country restrictions but that'll probably follow soon.~~

**Comment by Raffson** [comment]
> The less that we have to pull out of DCS with that extractor the better.

I'm starting to get real close to a viable solution and I could use some clarification here. Are you suggesting removing the liveries from the extractor all together? What data-structure do you have in mind to store the liveries? Would it have to scan everything at start and keep it in memory, or rather a "scan on demand" type of thing?

Currently I'm putting everything in a dictionary (so scan 1 time only) that looks like this:

Unit -> { LiveryName -> CountrySet | None }

The idea is that if the CountrySet is None, it's a livery for all countries. The only problem left here is the mismatch between "Unit" and the actual DCS ID for that unit. "Unit" refers to the name that corresponds to the livery-folder. Once I have a mapping between the ID and the livery's folder-name, it should be possible to query this dictionary easily for every available aircraft.

**Comment by Raffson** [comment]
Everything should be ready, a PR is open for pydcs and my branch is anticipating for the proposed changes in pydcs 👍 

https://github.com/Raffson/dcs_liberation/commit/a88a79a0e046ad0ebc5bcbdff51c2f331bf3d44b

Before opening a PR I'll wait till pydcs merges the scanner...
