### ISSUE TITLE
AI selection in ME showing wrong aircraft 

### ISSUE THREAD

**Issue by VCW3-admin** [dcs-liberation/dcs_liberation#1889]
### Affected versions

5.0.0

### Development build

ME shows wrong aircraft when selected 

### Description

Morning everyone. Could sleep last night so I was messing with Liberation in the mission editor to find  this issue. I’ll try to explain it the best I can and sorry I’df this has been posted prior but I could not find it.  
in the Mission editor select an Red AI aircraft on the map. 90% of the time it would show me with an A10 when they. Should be J11. Next select another aircraft in the flight list and select on another Red AI aircraft. The aircraft will now show that it is what ever you have selected earlier. 
example: I selected my hornet in the ME and then selected Aa Red AI aircraft to see it was a hornet. Selected another aircraft like. A10 and the same Red AI aircraft is now indicating an A10. Select another one again and it carriers over. 

I thought it might be a bug with the latest DCS update but found that what I saw in the liberation mission was not the same as one created by DCS. 

### Save game and other files

I’ll attach any logs once I get home.

**Comment by Wood-VCW3** [comment]
https://youtu.be/Jo8_0i2yigs

**Comment by Hornet2041** [comment]
not sure if Liberation is causing it but its a DCS mission editor bug at the very least - the aircraft spawn fine ingame as their airframes
![image](https://user-images.githubusercontent.com/55866858/147839559-c27a03f5-bada-4d96-bd65-761fbbc25f8e.png)

**Comment by VCW3-admin** [comment]
As I mentioned in the post I’ve checked DCS missions that were built in DCS ME and all works as normal. It only happens with Liberation missions. So I don’t see how it’s a DCS issue. Unless I’m missing something. 
thanks

**Comment by MetalStormGhost** [comment]
The issue here is that the DCS mission editor will not allow you to select Su-34 (for instance) for China. Liberation does not have this limitation and the gemerated missions work just fine in-game. The problem arises if you need to modify the missions in the mission editor, then you need to obey the mission editor's rules.

If you need to modify the missions in the mission editor, I suggest you change the country of the Liberation faction from China to e.g. CJTF Red. This will allow you to keep the selected airframes (and other units) in the mission editor.

**Comment by DanAlbert** [comment]
We should fix the faction to use CJTF.

**Comment by DanAlbert** [comment]
Actually there's no usable data here. We can't fix the faction if we don't know what faction was used. None of the artifacts were ever uploaded.
