### ISSUE TITLE
Adding the UH-60 mod with CLTD

### ISSUE THREAD

**Issue by GrassyKn0ll** [dcs-liberation/dcs_liberation#1964]
Adding player controllable/ AI UH-60s from the mod that just released the other day (reference https://drive.google.com/file/d/1ANTTOfz-wPBqGvmogJUKOYySMarktZid/view) with CLTD support from troop transport/logistics and light convoy support

**Comment by MetalStormGhost** [comment]
I am adding this support but in order to use CTLD with the UH-60L, you'll need to install Liberation plugins. See the following resources for more information, downloads and installation instructions:
https://github.com/dcs-liberation/dcs_liberation/wiki/Lua-Plugins
https://github.com/VEAF/dcs-liberation-veaf-framework

The #plugins channel on Discord is a good place to discuss Lua script modifications to allow the UH-60L to be used.
