### ISSUE TITLE
UI dimensions change when redrawn on 1920x1080 monitors

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2049]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1937618376

### Description

On a 1920x1080 monitor, the Liberation UI rescales when a new campaign is begun, or when Begin Campaign or Pass Turn is clicked, resulting in some buttons no longer being visible on screen. Workaround is to restore down then maximise window once again.

UI prior to hitting Pass Turn. The fast forward buttons are tiny, but at least the entire UI is visible and usable.
![Capture](https://user-images.githubusercontent.com/72491792/156905439-05fee53d-8ad4-469a-a962-e225783f98a2.JPG)

When Pass Turn is hit, the UI rescales and expands
![Capture2](https://user-images.githubusercontent.com/72491792/156905458-9a865d35-84a8-48b0-b28f-d05659895ef8.JPG)

### Save game and other files

Attaching random save but no save needed to replicate this.
[AEW.C.Planning.Bug.3573.zip](https://github.com/dcs-liberation/dcs_liberation/files/8191795/AEW.C.Planning.Bug.3573.zip)

**Comment by RndName** [comment]
Related #1987

**Comment by Raskil** [comment]
The topPanel ist not redrawn. The change in layout is related to the weather widget in the top panel. Each turn, or when you start a new campaign there is a chance that you get different weather. The width of the weather widget changes with the discription, as you can see from the screenshorts. The scaling of the timelapse buttons happens when qt is able to squeeze them into the width of the pnael. if it's not able to, the top panel is just cut.
According to @DanAlbert the timelaps buttons should be reworked anyways, We should choose a layout that fits into 1080p.

**Comment by DanAlbert** [comment]
Closing in favor of #1987
