### ISSUE TITLE
Waypoint speed is often too low

### ISSUE THREAD

**Issue by s3-chardonjf** [dcs-liberation/dcs_liberation#205]
Many times have I noticed flights going insanely slow with crazy angle of attacks in full afterburners.

Here's a CAP AI flight of F-14's for example, that took off from the carrier and just cruised like this:
![image](https://user-images.githubusercontent.com/29724443/95979641-3b32f300-0e1c-11eb-9e80-21969ad05779.png)

Discord user Smekre also reported a slow tanker
"Noticed that the tanker was way too slow in one mission today. The tanker (135mprs) was doing only 170 kts. Actually managed to fill up my Viper, but that was almost on speed AoA during the whole process :joy:"

**Comment by alcmann** [comment]
Noticed this also.

**Comment by dwischolek** [comment]
Maybe the speeds are set in km/h. 170 kts would be around 300 km/h.

**Comment by Starfire13** [comment]
I'm noticing this problem specifically on the F-14s and F-15s. My F-16 cap flights appear to be travelling at higher speeds. In fact, my Harrier strike flights are actually overtaking my F-15 CAP flights that take off first, because the F-15s are flying soooooo slowly.

Edit: I'm watching an AI F-15 flight now and they've finally sped back up, but the 2 elements of the flight are now flying off in different directions...

Edit 2: This bug is making F-14s completely useless for CAP flights. I'd be over the target and the F-14s I arranged to clear the way would still be near the carrier travelling at 140 knots, and off their assigned flight path too.

**Comment by DanAlbert** [comment]
This should be fixed in dev as of a few days ago, if that's where you were seeing it, so closing.

If this was in 2.1, all the aircraft in 2.1 are set to travel at 600kph at all times. If they're going slower than that, it's either loaded down too heavily or the AI isn't doing as asked. If you see this happen, check the waypoint speeds that are set in the mission editor (note that the speed between the hold point and the join point will be shown as _extremely_ slow in the editor because the editor computes that off the arrival time of the hold point, not the departure time) are reasonable.

If you see slow waypoints in the editor, share the .miz and the liberation save that will generate it with us and we can look. If planes are flying like this and the editor says they shouldn't be, I don't think there's much we can do.

**Comment by DanAlbert** [comment]
Did a bunch more digging and determined that the DCS AI doesn't know how to fly if they're not allowed to use afterburners. If they make a low altitude sharp turn they end up bleeding all of their energy assuming they can burn to get it back and exist the turn at 15+ AoA. If they are supposed to be climbing, they won't pitch down even temporarily to reduce their AoA, so they end up flying at the limit of their stall speed and either maintain altitude or slowly descend into the ground.

Another factor is that the AI is pretty incapable of flying waypoints with AGL altitudes without major pitch oscillations that bleed a ton of energy (not a problem for the carrier, but a major problem for airfields), which then causes the same AoA issues.

IMO both of these are DCS issues; the AI should be able to fly under those conditions. However for the time being we'll need to stop doing those things.
