### ISSUE TITLE
Adding extra waypoint with Add Waypoint button generates error

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2063]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1955044987

### Description

Clicking on the Add Waypoint button on the Edit Flight window generates the following two errors.

![Capture3](https://user-images.githubusercontent.com/72491792/157441331-1a1e1147-ef36-4183-b338-d463ece3e8f1.JPG)

![Capture4](https://user-images.githubusercontent.com/72491792/157441341-6f38c1d3-ed14-446b-86f0-a700cc588c60.JPG)

### Save game and other files

[Normandy #3619.zip](https://github.com/dcs-liberation/dcs_liberation/files/8214596/Normandy.3619.zip)

**Comment by Raskil** [comment]
I would say that pretty much the hole waypoint alteration in the gui is not working anymore: Add RTB Waypoint and Delete Selected throw errors as well.

**Comment by Raskil** [comment]
I've looked into the bug but I'm not able to solve it on my own, because I do not understand the flightplan building fully. From what I can see, I suspect @DanAlbert changes to the flight plan builder in fa8c0d9660fa4d47274f9cd02430b2e70f959805 to raise the issues. I was able to get rid of some bugs by changing the FlightWaypoint object creation calls to the new interface in QPredefinedWaypointSelectionComboBox (at least the waypoint box build properly with all custom waypoints). But I do not get the change into the custom flight plan running.

**Comment by DanAlbert** [comment]
Yeah, I'll handle this one. I'm certain I'm the one that broke it, but haven't had a chance to look yet. I tested some of the behaviors like deleting waypoints, but I guess I didn't cover adding new ones.

**Comment by Raskil** [comment]
@DanAlbert as I wrote earlier, on my build all three buttons (Add RTB Waypoint, Delete Selected, and Add Waypoints) throw errors and do not work.

**Comment by DanAlbert** [comment]
Might be dependent on the type of waypoint being deleted. Deleting target points does have different behavior as long as it isn't the last target point (it won't downgrade the flight plan to a custom "we don't know how to interpret this" flight plan), and that's probably where the bug is.

Or maybe I broke it in a different way than I thought :)

**Comment by Raskil** [comment]
Might be possible, I did not try to remove all types of waypoints. But I was able to provoke an error on all three waypoint buttons :)

**Comment by Starfire13** [comment]
At least to me, pretty much the only thing I would like to have working in this system is the ability to add an extra waypoint or two after the primary target waypoint, so that I can manually set up a secondary or tertiary target for my own use in case I have unexpanded ammo. At the moment, I am manually placing the split and/or refuel waypoints over targets in Liberation and then setting them to ground level in the mission editor, but that's just a tedious workaround.

**Comment by DanAlbert** [comment]
I know. It will be fixed when I have time.

**Comment by Raskil** [comment]
From what I can see, all waypoint maipulations suffer from the same issue, thats why I added the other buttons here as well. Most waypoint actions end up in a call to degrade_to_custom_flight_plan. And that function tries to add a customflightplan with the old flight plan interface, which is of course not working anymore.
@DanAlbert Should I throw you a pull request for my fixes to QPredefinedWaypointSelectionComboBox? That will not fix the issues, but at least the Widget with all the possible waypoints to add loads again.

**Comment by Raskil** [comment]
Ok, I worked a little bit more on it and I got it working. Sorry @DanAlbert  , couldn't resist :)
