### ISSUE TITLE
Loading second save moves enemy carrier to same position as friendly carrier in previous save

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#2078]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1972037759

### Description

I'm not sure if this can be reproduced by anyone else but as it initially loads "blackball plus usaf", i decided to load another save instead and the game moved the enemy carrier to where the friendly carrier was positioned in the previous save.

![image](https://user-images.githubusercontent.com/55866858/158176529-317b8193-54fa-4ea7-91ce-f98082750cea.png)
initial save load

![image](https://user-images.githubusercontent.com/55866858/158176552-1b509eb0-c6c8-4968-91fb-8f9c7b58aed3.png)
second save load

### Save game and other files

[bizarre carrier map bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/8244952/bizarre.carrier.map.bug.zip)

**Comment by Hornet2041** [comment]
update: it doesn't appear to actually generate the carrier in that position in the .miz... just an error on the map

**Comment by DanAlbert** [comment]
This is happening whenever the two games have identical CP names, as is the case with the carriers here. They have the same key here:

```jsx
<LayerGroup>
  {Object.values(controlPoints.controlPoints).map((controlPoint) => {
    return (
      <ControlPoint key={controlPoint.name} controlPoint={controlPoint} />
    );
  })}
</LayerGroup>
```

As far as the map knows these are the same control point because they have the same key. The "move" that appears to be happening here is an implementation quirk due to some workarounds for drag-and-drop bugs in a dependency; it's actually a line drawn from the current position to the current position, but only one of those "current positions" is being updated when the game is loaded.

Theoretically the same bug might cause FOBs that have the same names to show up in the wrong locations after load as well. Airports won't have this issue since they all have unique names and locations.

The fix is probably to generate a UUID for each CP so there's no chance of "duplicates" between games.
