### ISSUE TITLE
A-10 flight does not take off from Incirlik

### ISSUE THREAD

**Issue by s3-chardonjf** [dcs-liberation/dcs_liberation#209]
Repro - Load the liberation save, take off and wait. A-10 won't be moving even though they were scheduled T+3min.

Attached the .miz file as well.
[miz_and_save.zip](https://github.com/Khopa/dcs_liberation/files/5389795/miz_and_save.zip)

![image](https://user-images.githubusercontent.com/29724443/96224311-a5b87000-0f8f-11eb-995a-df70c55d439a.png)

**Comment by DanAlbert** [comment]
After some investigation and some help from the DCS discord, it seems to be because the airfield is neutral. We're not telling pydcs to claim the airfield and none of the ground units spawned close enough to claim it on mission start, so the condition to only start flights at friendly airfields didn't fire.

**Comment by DanAlbert** [comment]
We actually _do_ tell pydcs to claim airfields. I don't know why that mission didn't have that. If I use the same liberation save it generates a claimed Incirlik for me.

**Comment by DanAlbert** [comment]
This was fixed recently.
