### ISSUE TITLE
Can't create missions from carriers.

### ISSUE THREAD

**Issue by TheIrishAce** [dcs-liberation/dcs_liberation#21]
I currently can't create a flight from either of the 2 carriers. I purchased 2 F14's for it but when I press the add flight button type of aircraft is empty.

![Flight](https://user-images.githubusercontent.com/35999336/88300331-43870080-ccfb-11ea-8daf-fefc2d64ac93.png)

**Comment by Khopa** [comment]
Hello, 

After purchasing an aircraft, it will only be available on the next turn, maybe this is your issue ?

If it is not the issue, please post your log file. (which is located in <dcs_liberation_directory/logs folder)

**Comment by TheIrishAce** [comment]
No I'm familiar with the v1 of the mission I've waited 3 turns, still the same also tried a different navy aircraft to the same effect.
I'm currently away from my computer and will get logs later today.

**Comment by Khopa** [comment]
Thanks, that's weird, never seen this bug. 🤔 
If you can put your save file as well when get access to your computer, that will probably be helpful.

**Comment by TheIrishAce** [comment]
[liberation.log](https://github.com/Khopa/dcs_liberation/files/4968647/liberation.log)
![Liberation Problem](https://user-images.githubusercontent.com/35999336/88336549-181d0980-cd2d-11ea-86f3-4dd56f95d60c.gif)

That's the log let me know if you need anything else.

**Comment by Khopa** [comment]
I've been able to figure out the issue. It will be fixed in the next release, but the bad news is that there is no easy workaround to fix your savegame...  i'm sorry.

The carriers on the "Persian Gulf full map" are sharing a same id, hence why the mission planner is so confused, in fact it is probably using the list of available aircrafts from the other carrier. 

So I'd recommend starting a new game on a different theater... 
For the Persian Gulf map, the Emirates and Invasion of Iran setup have been play-tested a bit more thoroughfully.

Thank you for reporting this.

**Comment by TheIrishAce** [comment]
That's alright, I don't mind a fresh start. I'm glad you found the issue.

**Comment by Khopa** [comment]
This issue should be fixed in 2.0.10. 

Feel free to re-open the issue if you encounter it again in the new version.
