### ISSUE TITLE
Could not find ingress point for tarcap

### ISSUE THREAD

**Issue by s3-chardonjf** [dcs-liberation/dcs_liberation#210]
Using latest develop version with the attached save file:
[2020-10-16-1.zip](https://github.com/Khopa/dcs_liberation/files/5395104/2020-10-16-1.zip)

-  delete all flights and packages to start fresh
- right-click the airbase of Aleppo and select to create a new package
![image](https://user-images.githubusercontent.com/29724443/96330526-2772d100-1056-11eb-969b-304dd158c4b2.png)
- Create a TARCAP from Hatay like so:
![image](https://user-images.githubusercontent.com/29724443/96330542-3e192800-1056-11eb-994f-3d49b0cc9680.png)
- Notice the error:
![image](https://user-images.githubusercontent.com/29724443/96330521-12963d80-1056-11eb-9ea9-1bb60cd6a572.png)

**Comment by DanAlbert** [comment]
Should be fixed. You may need to remove/recreate any existing CAP flights if you load a save because I've _mostly_ removed that mission type. I left the definition of the mission type so your saves should still load, but they're gone from the UI, planners, TOT estimator, mission generator, etc.

For the moment TARCAP is no longer allowed at anything but front lines. Later we'll bring that back but that requires some improvements to planning. This is now working the way it was in 2.1, I believe.
