### ISSUE TITLE
Airfields without runways getting assigned as divert airfields causing IndexError on Takeoff

### ISSUE THREAD

**Issue by sgtfuzzle17** [dcs-liberation/dcs_liberation#2110]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2013327364

### Description

Upon hitting the "Take Off" button, the below error is returned:
![ZQhCok2](https://user-images.githubusercontent.com/49757384/159720043-b01cd037-25c3-483c-ba3b-af9806ca8783.png)
While I'm running 6.0-3680, others have reported the same issue on 5.2.0-3691. This is on my new campaign, Tripoint Hostility. I added this as a comment there, but have also opened this bug report in addition at (I think?) the suggestion of @RndName.

### Save game and other files

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/8333765/liberation.log)

**Comment by RndName** [comment]
The issue here is that a flight got 'At Tanf' assigned as divert airfield. 'At Tanf' itself only has two helipads and no runways but as Mig-21s were assigned to this flight the planner wants to get the acitve runway of the divert airfield.

Solution for this bug is to improve the logic which assigns the divert airfield to more carefully check if the airfield is capable or not.

**Comment by RndName** [comment]
Save-game to reproduce [syria_bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/8334179/syria_bug.zip)
