### ISSUE TITLE
Player Apache falls to the ground and explodes as soon as the mission starts

### ISSUE THREAD

**Issue by EagleMountainDK** [dcs-liberation/dcs_liberation#2129]
### Affected versions

5.2.0

### Description

I started a fresh campaign of "The Golan Heights" with the default sides. Added my self in the Apache Squadron and bought units. Pressed the "Start campaign" and used the default plans without touching anything. 
Joining in my slot crashes the Apache as soon as the mission start. Delaying for a moment by joining the observer side did not help anything.
I have attached my log, save game and the mission created when I pressed "TAKE OFF".

### Save game and other files

[Liberation_Save.zip](https://github.com/dcs-liberation/dcs_liberation/files/8358253/Liberation_Save.zip)
[liberation_nextturn.zip](https://github.com/dcs-liberation/dcs_liberation/files/8358254/liberation_nextturn.zip)
[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/8358261/liberation.log)

**Comment by Starfire13** [comment]
Is it falling to the ground because it is colliding with another aircraft on spawn in, or does it just fall out of the sky because it is spawning in the air and you aren't able to get it under control in time? Essentially, is it already dead before it hits the ground?

**Comment by EagleMountainDK** [comment]
No, I'm not really sure how to describe it. As soon as I spawn into the only player AH-64D my view is looking straight into the back of the seat with no option of turning around. The heli looks to be moving backwards in a straight line and pressign F2 gives detonates a AH-64D on the FARP. Not really sure what happens to be honest. 
Very curios if other see the same in when starting my mission.

**Comment by Starfire13** [comment]
Ah. It blows up on the FARP itself then. I've seen that happen on Blackball with specific FARPs. My guess is that when FARPs are placed on a slope, the tail wheel clips into the terrain on spawn and destroys the chopper.

**Comment by EagleMountainDK** [comment]
Hmmm not really sure what happens, since I spawn into my Apache with no control possible, i.e. view change and the like does not work. The heli exploding seems to be my wingman?!?!?!
Please see this clip from TacView of the mission: https://youtu.be/klEKY3mncbU

This is a picture of my Apache in the editor: https://www.twins4ever.dk/pictures/PC/DCS/Liberation/Digital%20Combat%20Simulator%20%20Black%20Shark%20Screenshot%202022.03.29%20-%2015.48.04.79.png

And a picture of the terrain in game: www.twins4ever.dk/pictures/PC/DCS/Liberation/Digital%20Combat%20Simulator%20%20Black%20Shark%20Screenshot%202022.03.29%20-%2015.46.02.66.png

**Comment by EagleMountainDK** [comment]
My last try was to remove my self from the flight and added a new Apache mission with only one helicopter. Now the mission starts with me in the cockpit but the above helicopter still explodes so I think you are right about the placement of the farp causing problems.

**Comment by RndName** [comment]
This one here two different issues in one:
1) The player apache is behaving extremly awkward:
> The heli looks to be moving backwards in a straight line

This even happens if you move the player apache to a airbase helipad.. Something is really broken with it. I was not able yet to reproduce what exactly happened with this flight. Generating a complete new fresh campaign worked as expected...

May has something to do with the Starting time and the setting to enforce the player flights to start ASAP
![grafik](https://user-images.githubusercontent.com/6678803/161266316-d61594dd-a574-4fb4-a98a-8993f747e9dc.png)

Edit: I found the solution. Either set the Package itself to ASAP
![grafik](https://user-images.githubusercontent.com/6678803/161267145-47028f0b-428b-4092-91cd-d863e9d1d657.png)

Or disable "Uncotrolled" for the Player flight within the Mission Editor
![grafik](https://user-images.githubusercontent.com/6678803/161267293-bdfaffed-03a6-4e51-abe6-5b3c35291bd4.png)

I am not sure why this option is set in the first place 🤔 


2) The apache at the base explodes (mostly because of the uneven terrain)

**Comment by RndName** [comment]
> I am not sure why this option is set in the first place 🤔

At least that part is now clear for me. As the startup time of your flight is 11:48 it is delayed. If the delay is greater than 10 mins it will be set to uncontrolled. This will give you the view you see:
> The heli looks to be moving backwards in a straight line

After 11:48 you would be able to use the apache.

The other issue with the exploding apache really seems to be caused by uneven terrain (as far as we currently know)

**Comment by fercyful** [comment]
Hi there! Here the problem is that the wingman explodes beside me at the FARP. I check the mission and me and the AI try to take from the same helipad. Changed the AI one and now both stay alive at the start of the mission :) Also can be the sloped terrain if the system auto assign the starting position for the AI wingman (with bad luck at uneven terrain)... thanks!

**Comment by Starfire13** [comment]
> Hi there! Here the problem is that the wingman explodes beside me at the FARP. I check the mission and me and the AI try to take from the same helipad. Changed the AI one and now both stay alive at the start of the mission :) Also can be the sloped terrain if the system auto assign the starting position for the AI wingman (with bad luck at uneven terrain)... thanks!

If indeed two apaches are spawning on the same helipad, then it is a different issue from this one. File your own bug report with the requisite info and save file please.

**Comment by RndName** [comment]
That’s probably the dcs limitation for FOBs that you can not specify the helipad which will be used.  IIRC dcs assigns them automatically so they won’t spawn inside of each other. We just fake the position from pydcs by setting the coordinates of the helipad but the helipad you see in mission editor must not be the one assigned by dcs later in the mission.
I suspect the issue to be the same with the sloped terrain.
Only way to verify is (as always) attaching save game and miz. Without them it’s fishing in the dark.

**Comment by fercyful** [comment]
> If indeed two apaches are spawning on the same helipad, then it is a different issue from this one. File your own bug report > with the requisite info and save file please.

Thanks for support just post the bug report + Files . Hope it helps.

https://github.com/dcs-liberation/dcs_liberation/issues/2161

**Comment by fercyful** [comment]
> That’s probably the dcs limitation for FOBs that you can not specify the helipad which will be used. IIRC dcs assigns them automatically so they won’t spawn inside of each other. We just fake the position from pydcs by setting the coordinates of the helipad but the helipad you see in mission editor must not be the one assigned by dcs later in the mission. I suspect the issue to be the same with the sloped terrain. Only way to verify is (as always) attaching save game and miz. Without them it’s fishing in the dark.

Thanks for support and great explanation. Almost sure have to be the sloped terrain there... Just wrote the report and send the files. Thanks!

https://github.com/dcs-liberation/dcs_liberation/issues/2161

**Comment by DanAlbert** [comment]
(sounds like this was a DCS issue, so nothing we're able to do)
