### ISSUE TITLE
Aircraft in the air start too low

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-liberation/dcs_liberation#2212]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2286928013

### Description

We ran on build 3841 for five hours tonight and three of those mission the F15c barcap, starting in air due to start at first contact, were at so low altitude majority of them crashed. I have three tacview files showing this. The saved game has progressed through the night and is not setup the way it was when it broke. I would set three sets of f15c barcap, 4x ship, and that meant 12 planes were trying to air start and would start too low. 

### Save game and other files

[tacview](https://www.dropbox.com/s/3caz2hp4j5078kp/tac.zip?dl=0)
[save](https://www.dropbox.com/s/dysecy36y7ik0to/save.zip?dl=0)

This attach system is broken on github and kept refusing to accept anything direct.

**Comment by DanAlbert** [comment]
Possible dup of #2030, but we never figured out the cause of that and this one has more useful data, so leaving it open.

**Comment by holyorangejuice** [comment]
I will add that I was having this issue when I set all three flights to ASAP TOT. I usually space them out 20min,25min,30min TOTs.

**Comment by holyorangejuice** [comment]
https://www.dropbox.com/s/wl9dpvbnz0oylmr/Tacview-20220518-190848-DCS-liberation_nextturn.zip.acmi?dl=0

Happened several times tonight as well with my group. This is the only tacview I have showing it. Once again this happened when I did not manually space out the TOTs.

**Comment by Starfire13** [comment]
So does it still happen when you space out your TOTs?

Btw you can attach miz files directly as long as you zip them.

**Comment by holyorangejuice** [comment]
Not when github is having a heart attack and refuses to accept them. Doesn't appear to happen when I use manual TOTs. Tacviews show the multiple groups spawning close and low. So they crash.

**Comment by DanAlbert** [comment]
Your save doesn't load on the build you linked, or on the latest build:

```
2022-05-29 13:27:48,782 :: root :: ERROR :: Error while loading terrain zones [object Object]
```

**Comment by DanAlbert** [comment]
Hmm. I just saw the same thing on a different save, so might be unrelated.

**Comment by DanAlbert** [comment]
> The saved game has progressed through the night and is not setup the way it was when it broke

Oh. _that's_ why the save doesn't contain any missions. There's nothing we can do with the data given. We need a save game that shows the problem.

**Comment by holyorangejuice** [comment]
[4060error.zip](https://github.com/dcs-liberation/dcs_liberation/files/9043792/4060error.zip)

This issue of AI spawning too low is still happening. Multiple aircraft assigned to tasks in this tacview are killed by hitting the ground on spawn.

This is not the same issue as Syria map air spawning non pilot planes due to lack of parking.

**Comment by Raffson** [comment]
I just inspected the mission in DCS' editor, there are indeed aircraft being generated in-flight at 100ft AGL at 500 kts. That can be a problem, especially in the following case:
![Screen_220705_122741](https://user-images.githubusercontent.com/10977187/177307845-65ef0e53-1d02-4036-96c2-819bc40e2971.jpg)

Let's see if I can figure out why it's generating planes this low...

**Comment by Raffson** [comment]
@holyorangejuice One thing I'd like to verify, did you fast-forward to first contact? Because according to the campaign file those flights should be starting cold, but that's not happening so I'm trying to figure out why...

**Comment by holyorangejuice** [comment]
> @holyorangejuice One thing I'd like to verify, did you fast-forward to first contact? Because according to the campaign file those flights should be starting cold, but that's not happening so I'm trying to figure out why...

Yes. Start at first contact is used. The save file I provided should have identical settings that I used.

**Comment by Raffson** [comment]
> Yes. Start at first contact is used. The save file I provided should have identical settings that I used.

Right, but you have to press take-off before it actually forwards time, at that point it becomes really confusing. On one hand I have the UI telling me the flights are flying to their racetrack, on the other hand the edit-flight window suggests they're still starting cold. But at least I'm pretty sure it's a problem in the generator.

**Comment by Raffson** [comment]
@DanAlbert Ok so I tracked down the problem to the following code:
https://github.com/dcs-liberation/dcs_liberation/blob/2f97d948b872c9b1ba94e64ac4f399ef2c28fa8c/game/missiongenerator/aircraft/flightgroupspawner.py#L131-L158

There's other places where you could make adjustments to solve the problem but I think the code above is the most logical place to handle the issue. The first thing that goes wrong is the fact that those flights starting at 100ft AGL have a bad estimate for their altitude (line 137), specifically they return 0 because that's what the take-off waypoint suggests. The second thing is a couple of F14 flights that ought to start at 7000+ meters AGL but instead they start at ~3900ft AGL. This seems to be a DCS limitation if you choose AGL as altitude type, i.e. you can't spawn higher with AGL mode.

EDIT: disregard the second problem, it seems it's only a limitation of DCS' editor, when actually starting the mission I find those F14s between angels 23 and 24 so that seems correct.

So my suggestion would be something like the solution for #1941 for the first problem, suppose a minimum altitude of 500ft if `alt_type` is "RADIO". ~~The second issue is a little trickier though. One possibility would be to check if the altitude is higher than 3900ft and adjust `alt_type` to "BARO" if that's the case. But that leaves us with a similar issue in the sense that we still don't know if we're spawning high enough, i.e. we might be spawning in the flight at 4500ft AMSL while there's a mountain of 5500ft right in front of it. Unless we actually know what the elevation is for a certain point I don't see how we can eliminate the problem entirely.~~

**Comment by Raffson** [comment]
So now that the second issue is out of the way, I have a fix that's more or less ready. The main question is what minimum altitude should be used in case of AGL. I propose a random altitude between 500ft and 1000ft AGL, that should guarantee some spacing in case planes spawn close to each other, as well as clearing most ground objects.

Specifically the code to be added would look like this:

```
# If 'alt' is less than 500ft AGL, use random value between 500-1000ft
# Otherwise planes might crash in trees and stuff...
if alt_type == "RADIO" and alt < feet(500):
    alt = feet(500 + 500*random.random())
```

I have a branch ready with this to become a PR...

**Comment by holyorangejuice** [comment]
Thank you for this. I'm always grateful when an issue is taken seriously. I know there is a long list of to do and want to add. I run many events per week with our group. I frequently find things to report.

**Comment by DanAlbert** [comment]
We've always taken the issue seriously. We had no way to investigate until yesterday.

**Comment by holyorangejuice** [comment]
> We've always taken the issue seriously. We had no way to investigate until yesterday.

I've been able to replicate it consistently between builds. I thought there was enough info the first time since it isn't unique to a save. Just unique to first contact I guess.

I'm still thankful it was looked into again.

**Comment by DanAlbert** [comment]
We couldn't even load the previous save that was uploaded, as I said when I closed the bug not-reproducible.

**Comment by Raffson** [comment]
@DanAlbert does the proposed solution look good to you?
