### ISSUE TITLE
CAS/SEAD/DEAD mission waypoint altitude too low

### ISSUE THREAD

**Issue by hymlee** [dcs-liberation/dcs_liberation#2219]
For CAS/SEAD/DEAD mission (or perhaps other missions), the altitude of waypoint over the targets is often set to 0ft or a few thousands feets.
AI aircrafts sometimes follow those waypoints and altitude settings and become vulnerable against SHORAD.

Recommended solution:
Altitude of waypoint over the target should be the same as the altitude at ingress and egress waypoints.
There is no need to manually assign specific altitude at target waypoint.
DCS AI would automatically find suitably altitude for deploying weapons
![SEAD](https://user-images.githubusercontent.com/105715207/168792252-350ea7c9-c4f2-46c5-ba09-5a505dc315ea.png)
.

**Comment by Khopa** [comment]
Hello, 

Last time I touched that part of the code, Liberation would not generate the actual DCS flight plan in the same way if it's a player flight or an AI-only flight.

The UI here shows how the waypoints would be generated for player flights. Since it is convenient to have targets as waypoint, and as we don't have other way to include target coords in the flight computer, a 0ft AGL waypoint on the target coords is included for the player.

Waypoint 5 here will not be generated for an AI flight, but there will be a SEAD task in Waypoint 4 pointing to the target. So when the AI reach waypoint 4, it should start its SEAD task. Which normally doesn't involve flying over the target, but as you might know, things are unpredictable whenever DCS AI is involved :)

Could you check the generated flight plan in the mission editor (and close the issue if eveything is fine) ?

Thanks,

Khopa

**Comment by Starfire13** [comment]
The issue with SEAD aircraft going dumb and overflying the SAM site at low altitude actually has nothing to do with the waypoint altitude (the 0 alt waypoint is not a flyover point, and it isn't actually generated for AI flights anyway, as Khopa said). It's actually due to the aircraft being unable to find an emitter source and then going stupid. Mainly a problem with SHORADS since their radars are shorter range. There's been a switch to a different tasking in the dev build to get around the DCS bug. If you wish to stick to 5.2, one workaround is to not use HARMs for SHORADs and stick to DEAD tasking using stuff like Mavericks, JSOW-Cs, SLAM-ERs, etc, to kill them.
