### ISSUE TITLE
Improvement to CAS waypoint

### ISSUE THREAD

**Issue by WS1273** [dcs-liberation/dcs_liberation#2231]
**Problem:**
The following issues are observed for AI flights, and particularly affecting effectiveness of AI Helicopter Flight.
(1) In CAS mission, AI won't search for targets and employ weapon until reaching INGRESS waypoint.
The issue is easily noticeable when the enemy ground force is advancing. AI Helicopter flight in CAS mission will not employ any weapon to the enemy they encountered enroute to the INGRESS waypoint. Until reaching INGRESS waypoint which they are assigned the task to "SEARCH and ENGAGE", they hold their fire and become target practice for enemy AA fire.

(2) If the enemy force is retreating / advancing, at the time AI flights reach the INGRESS/CAS waypoint, enemy forces may have already traveled dozen of miles away from the CAS waypoint. If the frontline takes place in mountainous terrain, AI Helicopter flights, which are often flying very low to the ground, might have their sightline obscured and have a hard time spotting the enemy and might just RTB without providing any support.

**Suggested Solution:**
To deal with issue 1, the solution could be a simple one. The "Search and Engage" task can be assigned one waypoint earlier. So AI flights can search for enemy targets while on their way to the frontline.
![1](https://user-images.githubusercontent.com/106515388/170957678-811008bf-f594-4194-846f-96cc44773a49.jpg)
![2](https://user-images.githubusercontent.com/106515388/170959178-7b7f6b4b-5d06-4cba-97f6-79edf0a4f2ac.jpg)

Issue 2 mainly affects AI helicopter flights but not fixed-wing aircraft, as helicopter sightlines could be easily obscured by mountainous terrain when flying low to the ground. The solution can again be a simple one: Just ascend the height to at least 2000ft AGL which AI helicopter travels to help them spot enemies.

**Comment by DanAlbert** [comment]
Was just about to tackle this, but it occurs to me that this isn't as straightforward as I was hoping it would be. Right now we get away with brainless placement of the ingress/egress points (which are really just bad names for patrol start and patrol end) because they're on the front line, which by definition won't be farther from the front line than the departure airport was, and if it does happen to be in SAM range it doesn't matter; that's where it needs to be.

Moving the ingress point somewhere more useful means we'll need to account for those things. I've been wanting to generalize the code that does that kind of layout. I haven't quite figured out how yet but I want to give it some more thought before approaching this.

As for the other half (in the future, one bug per bug please, it's much harder to manage bugs with multiple requests in them), helo patrol altitude: the risk of that tradeoff is that they'll be much more vulnerable at higher altitude. We can't feasibly do both (patrol low unless nothing is seen, then pop up). I can raise the altitude easily enough, just wanted to be sure you know what you're getting if I do that.

**Comment by DanAlbert** [comment]
This should be approachable now that https://github.com/dcs-liberation/dcs_liberation/issues/3085 is done.
