### ISSUE TITLE
Exception: can't set attribute 'arrival'

### ISSUE THREAD

**Issue by Raffson** [dcs-liberation/dcs_liberation#2243]
### Affected versions

Development build

### Description

Problem: setting the arrival airport for flights is not possible, triggers an exception.

Traceback (most recent call last):
  File "qt_ui\windows\mission\flight\settings\FlightAirfieldDisplay.py", line 76, in set_arrival
AttributeError: can't set attribute 'arrival'

Solution: add setter in /game/ato/flight.py

I can either push this on one of my open PRs, or make a separate branch with a new PR...

### Save game and other files

Any campaign file should do...

**Comment by DanAlbert** [comment]
It shouldn't be possible to set the arrival airfield manually per flight. That's entirely controlled by the squadron now. If that's still a combo box in the flight settings, that's the bug. Should be just a label.

**Comment by Raffson** [comment]
Then it is indeed a bug in the UI since it's still a combo box on my end. I tracked down the code and compared it to upstream/dev to make sure the problem doesn't just lie on my end, but that's not the case. So where would you prefer to have the changes? A separate branch & PR or one of my existing PRs?

**Comment by DanAlbert** [comment]
One change (feature, bug fix, cleanup, etc) per PR. Multi purpose PRs are extremely difficult to review (why did this line change? Which bug does this fix?)

**Comment by Raffson** [comment]
Probably something that got missed, I already have a fix, I'll make a new PR with the changes, starting from upstream/dev of course

**Comment by Starfire13** [comment]
> Then it is indeed a bug in the UI since it's still a combo box on my end. I tracked down the code and compared it to upstream/dev to make sure the problem doesn't just lie on my end, but that's not the case. So where would you prefer to have the changes? A separate branch & PR or one of my existing PRs?

Yeah, that box didn't get removed back when squadrons were implemented. Thanks for removing it. Saves us having to regularly tell folks on the Discord not to use it.

**Comment by DanAlbert** [comment]
Proof that bugs that don't get filed don't get fixed :)

**Comment by Starfire13** [comment]
The Arrival option was removed when Squadrons was implemented, which was what was previously being used to transfer aircraft. The issue was folks were using the Divert option to transfer aircraft (which didn't actually transfer aircraft even pre-squadrons) once "Arrival" was gone; divert simply allowed us to specify that the aircraft would land at a different airfield (with the assumption that it flies back to its home base in between turns). So, I didn't really see it as a bug, it's just that folks were using it wrong after the loss of the Arrival option. It's not a particularly useful option (since the AI will auto-divert when damaged or bingo anyway), so I'm glad it's gone because it appears the only ones using the feature are folks using it for the wrong purpose.

**Comment by DanAlbert** [comment]
Divert does nothing for the AI, and is unrelated to the arrival box, so I'm not sure what you mean.

**Comment by Starfire13** [comment]
Well, the Arrival combo box no longer exists. It's just divert now. Isn't the divert box what is getting removed? If not, I'm confused..

**Comment by Raffson** [comment]
I just took a peek at the code and if I understood right, divert is simply for the players so a waypoint is generated for them in-game right after your "landing at homebase"-waypoint.

**Comment by DanAlbert** [comment]
That's correct. It's a player only waypoint.
