### ISSUE TITLE
WWII map dunkirk error 

### ISSUE THREAD

**Issue by steevivo** [dcs-liberation/dcs_liberation#225]
Hi,

When I launch the button take off I have this error and the game not start :
![Capture_d'écran_102020_014753_PM](https://user-images.githubusercontent.com/5672749/96582219-3cac6180-12db-11eb-8cdd-c20bed25fce2.jpg)

Player : UK 1944
Enemy : Germany 1944

**Comment by Khopa** [comment]
Hello, 

You can fix this issue by creating an empty file there :

**<dcs_liberation_directory>/resources/beacons/thechannel.json**

Open this file with a text editor, and just put an empty json object in it : 

_**thechannel.json**_
```
{}
```

This should fix the issue.
(This should also be fixed in preview builds.)

**Comment by steevivo** [comment]
Hi,
Its ok now 
Thx

**Comment by steevivo** [comment]
Hi,
It's Ok now

Thx
