### ISSUE TITLE
Please add the Leopard 2A6M to the available units

### ISSUE THREAD

**Issue by Furia139** [dcs-liberation/dcs_liberation#2295]
Currently Liberation offers the possibility of using the Leopard 2, Leopard 2A4, Leopard 2A4_trs and the Leopard-2A5, however its does not have the lastest and more modern version of the leopard, the **Leopard 2A6M**.
Would it be possible to add this leopard version to Liberation?

Thanks a lot!!

**Comment by MetalStormGhost** [comment]
The Leopard 2A6M is available in Liberation, it's just confusingly named because ED replaced the original Leopard 2 model with the 2A6M. In order to use the 2A6M model in your faction, you need to use "Leopard 2" as the name of the unit. I suppose this could be improved a bit.

https://github.com/dcs-liberation/dcs_liberation/blob/develop/resources/units/ground_units/Leopard-2.yaml
<pre>class: Tank
description: The Leopard 2 is a main battle tank developed by Krauss-Maffei in the
  1970s for the West German Army. The tank first entered service in 1979 and succeeded
  the earlier Leopard 1 as the main battle tank of the German Army. It is armed with
  a 120 mm smoothbore cannon, and is powered by a V-12 twin-turbo diesel engine. Various
  versions have served in the armed forces of Germany and 12 other European countries,
  as well as several non-European nations, including Canada, Chile, Indonesia, Singapore,
  and Turkey. The Leopard 2 was used in Kosovo with the German Army, and has seen
  action in Afghanistan with the Dutch, Danish and Canadian contributions to the International
  Security Assistance Force, as well as seeing action in Syria with the Turkish Armed
  Forces.
introduced: 1985
manufacturer: Krauss-Maffei
origin: Germany
price: 25
role: Main Battle Tank
variants:
  Leopard 2: {}</pre>

<pre>	[109] = 
	{
		["type"] = "Leopard-2",
		["name"] = "MBT Leopard-2A6M",
		["category"] = "Armor",
		["description"] = "MBT Leopard-2A6M",
		["vehicle"] = true,
		["attribute"] = 
		{
			["HeavyArmoredUnits"] = true,
			["Tanks"] = true,
			[26] = true,
			["AntiAir Armed Vehicles"] = true,
			[2] = true,
			["Modern Tanks"] = true,
			["Armed vehicles"] = true,
			["Ground vehicles"] = true,
			[17] = true,
			[299] = true,
			["Vehicles"] = true,
			["Ground Units Non Airdefence"] = true,
			["Armed ground units"] = true,
			["All"] = true,
			["Ground Units"] = true,
			["Armored vehicles"] = true,
		}, -- end of ["attribute"]
		["aliases"] = 
		{
		}, -- end of ["aliases"]
	}, -- end of [109]</pre>

**Comment by Furia139** [comment]
Thanks a lot for the answer. I will do so.
