### ISSUE TITLE
Error on results acceptance: AttributeError: 'PySide2.QtWidgets.QWidgetItem' object has no attribute 'adjusted'

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#2304]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2625466170

### Description

This window popped up when accepting results. It didn't hinder the results acceptance or appear to affect the campaign in any sort of matter though.

2022-07-06 22:24:04,629 :: root :: INFO :: On Debriefing
2022-07-06 22:24:04,671 :: root :: DEBUG :: Turn processing took 0:00:00.745213
2022-07-06 22:24:04,825 :: root :: ERROR :: Uncaught exception
Traceback (most recent call last):
  File "qt_ui\delegates.py", line 45, in paint
AttributeError: 'PySide2.QtWidgets.QWidgetItem' object has no attribute 'adjusted'

### Save game and other files

![image](https://user-images.githubusercontent.com/55866858/177677266-9c9c561f-202f-418a-ad53-101cf93f76c1.png)
[new campaign july.zip](https://github.com/dcs-liberation/dcs_liberation/files/9059842/new.campaign.july.zip)

**Comment by Raffson** [comment]
Are you able to consistently reproduce this error on your end?

**Comment by Raffson** [comment]
I'm starting to suspect the same sort of problem as #2272, i.e. the state of the campaign isn't valid. `state.json` indicates 17 aircraft were destroyed, but when I try to manually submit results I only get 8 aircraft, specifically 1x CF-188 and 7x Mig-19P. The same sort of thing happens for ground units. As a result of all this I'm starting to suspect the mission results are not fully processed.

I'd like to verify which turn it was before you took off, I assume it was turn 3. Also, what flights do you remember from the ATO? The more info I can get, the better, because without a more detailed traceback it's really hard to pinpoint the problem.

EDIT: another small detail that might help is whether or not the error popped up while the results window was still open, i.e. the window where the "accept results" button appears.

**Comment by Hornet2041** [comment]
no.... i think maybe to reproduce it i should save the campaign file before flying a mission that could produce it. i'll start doing that now just in case

Turn 4 is the one that i pressed take off, accepted results and that window popped up. The flights are pretty much identical to what you see in the attached save, the ATO hasn't changed much in the early turns. 

And yeah, the error window popped up in front of the results window.

**Comment by DanAlbert** [comment]
No reproducible. As always, will reopen if that changes.
