### ISSUE TITLE
6.0 preview 4142 - widget error message

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-liberation/dcs_liberation#2338]
### Affected versions

Development build

### Development build

6.0 preview 4142

### Description

All worked well and I observed a pop up error after accepting results of the first turn. Not sure how big of an error this is. picture of error and save file.
[4142.zip](https://github.com/dcs-liberation/dcs_liberation/files/9173414/4142.zip)
 

### Save game and other files

attached

**Comment by DanAlbert** [comment]
There's nothing actionable here. Can't fix it if I don't know how to repro. Loading the save works fine and that'll all the information given.

We haven't seen any other reports of this though. Was it a one time thing? If you see it happen again, could you upload a more recent save and some repro instructions? If we get that we can reopen, but with the info we have there isn't anything we can do.

In the future, please upload error traces directly to the bug, whether as text (preferable, because then it's searchable) or as a picture. A _zipped_ picture is something that's a pain to get to on a phone, which is where almost all triage takes place, which is why this was accidentally overlooked for so long.
