### ISSUE TITLE
Suggested Additional Yamls for missile date restrictions

### ISSUE THREAD

**Issue by icuham** [dcs-liberation/dcs_liberation#2348]
Some files are attached for suggested additional date restrictions for aircraft weapons.

a2a-missiles/

- [x] R-60M.yaml (fallback to R-60)
- [x] R-60-2X.yaml (fallback to R-3)
- [ ] R-60.yaml (fallback to R-3)
- [x] R-40T.yaml (fallback to R-40R)
- [x] R-40R.yaml (fallback to R-3R)
- [x] R-24T.yaml (fallback to R-24R)
- [x] R-24R.yaml (fallback to R-3R)
- [x] R-3R.yaml (fallback to R-3)
- [x] R-3.yaml

standoff/

- [x] Kh58.yaml (fallback to Kh-25)
- [ ] Kh-25.yaml (fallback to S-24B)
- [x] S-24B.yaml

I tried to test these additional files in the 5.2.0 release but I don't see any changes to loadouts, including for those loads that exist already such as AIM-120C (fallback 120B) or AIM-9M (fallback 9P5).  Hopefully someone can pick this up and integrate it in the correct way.

[weapons.zip](https://github.com/dcs-liberation/dcs_liberation/files/9186472/weapons.zip)

**Comment by DanAlbert** [comment]
Thanks! There's actually a stale PR that addresses some more of this (not sure how much overlap there is). Will take a look at merging both for the 6.0.0 release.

**Comment by icuham** [comment]
If there is anything beyond adding yamls and checking the config box that's needed to adequately test this please let me know. I'd prefer to be able to try it out in the program before dumping these untested, and I'm sure more will be added later.  At the moment I'm assuming that with the yamls in and option on, then all flights have the weapons corrected upon miz generation, not sure if I should also see the update rendered in the liberation interface.

**Comment by DanAlbert** [comment]
It's been a while since I've touched the option so I might not remember correctly, but I believe the Liberation UI should reflect the era-appropriate weapons. I would not be at all surprised if toggling the option didn't update the UI for the current turn though.

All I've ever done for testing these sorts of things is to do like you said: add the yaml, check the box, pick a loadout that uses the unavailable thing and make sure it degrades well.

The hardest part by far is making sure the fallback path is sufficient. About the worst thing that can happen is an empty pylon (though some times that's fine, TGPs don't usefully degrade to anything, for example), so it's important that any fallback is either always available or also has a fallback, and that the fallback path will work will eventually find a weapon regardless if the aircraft.

I'll do some head-scratching of my own when I go to merge this (fair warning: real life has me very busy lately so I won't be able to any time soon, but like k said I do want to make sure this gets into 6.0.0). As long as you've done the same we'll probably be close enough to right :)

**Comment by DanAlbert** [comment]
I'm a noob at Russian missiles, so I'm not sure how to resolve some of the differences between what you have and what @Nosajthedevil did. I've checked off and merged (https://github.com/dcs-liberation/dcs_liberation/pull/2474) the ones that seemed obvious to me, but I don't know how to weigh the R-55 against the R-3 (each of your suggested fallbacks for the R-60).

Your introduction date for the R-24R seems to be wrong. https://en.wikipedia.org/wiki/R-23_(missile) says 1974 at least for the R-23.

The Kh-25 file contains several variants of the Kh-25, not all of which should be considered equal afaik, so I haven't included that yet.

The Kh-58 was merged recently. No changes needed.

**Comment by Nosajthedevil** [comment]
I think the only jet in DCS that uses the R-55 is the Mig-21, which can carry it on pylons 2 and 4. From what I can tell it's an RS-2 (which was a terrible beamrider) upgraded with an R-3S IR seeker head (or R-3R SARH seeker, but I don't think the SARH version of the R-55 is in DCS). Service year was 67, which is why I placed it between the R-3S and the R-60. I think it has a bit longer range than the R-3S. I don't fly the Mig-21, so I don't know if anyone would prefer it vs. just using the R-3S or not.

**Comment by Nosajthedevil** [comment]
I took a quick look at google, the range might not be better, but it appears that the R-55 might have some all-aspect capability and a large warhead. I still have no idea if it's better than the R-3S, so I'll defer to whatever you guys think.

**Comment by DanAlbert** [comment]
If @icuham can weigh in on why that might be a better choice, it's an easy change. I haven't heard anything since I posted the question. Going to close this since I think it's done but will reopen if that changes.
