### ISSUE TITLE
Air Assault flight does not trigger simulation pause upon arrival at destination

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2452]
### Affected versions

Development build

### Development build

#4211

### Description

Filing this for reference purposes.

At the moment, air assault flights will not trigger simulation pause, meaning the chopper will fly to the destination airfield and then RTB with no troops dropped.

See https://discord.com/channels/595702951800995872/790195984105734165/1023090964589461574

### Save game and other files

[Infantry Capture Test #4211 Turn 2.zip](https://github.com/dcs-liberation/dcs_liberation/files/9638004/Infantry.Capture.Test.4211.Turn.2.zip)

**Comment by Starfire13** [comment]
Closing as this should be handled once the combat simulation is improved.

**Comment by DanAlbert** [comment]
Sorry, apparently I didn't explain that well. The air assault thing should definitely be fixed (and I think easily can be, though I haven't looked).

The part that's going to eventually solve itself is the "I clicked take off and it's stuck looking for contact that will never happen".

**Comment by DanAlbert** [comment]
Build URL: https://github.com/dcs-liberation/dcs_liberation/actions/runs/2813316414

**Comment by DanAlbert** [comment]
I'm pretty sure the fix here is trivial but while digging in to make that change in a way to make sure that plain old cargo missions wouldn't interrupt simulation (because that's an unnecessary stop point), I found that the air assault implementation changed a lot about how airlift works, and now I'm not sure what's a bug and what's intended behavior. I'm waiting for @RndName to clarify before I make any changes. Context: https://discord.com/channels/595702951800995872/595706037449785364/1030635644197801994

**Comment by DanAlbert** [comment]
(if I don't hear from @RndName before the end of the weekend I'll go ahead and make the changes that I think are correct)

**Comment by RndName** [comment]
@DanAlbert i tried to find the solution for this issue and how to interrupt the fast forward but i am not able to dig deeper in the combat simulation to fully understand how to properly achieve what we want. Seems that there are some changes needed to add an active combat so that the gameloop gets interrupted. But i dont have the time to find out the right way atm.
How would you implement that?
