### ISSUE TITLE
Static vehicle groups are no longer showing up in the "Add Waypoint" dropdown list

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2564]
### Affected versions

Development build

### Build information

DCS Liberation 7.0.0
Build 4486
Git revision 4414853e4536c63a8a08af40aa5df8fc68ede566

### Description

Static vehicle groups used to be selectable in the Add Waypoint drop down list (e.g. 5.2.1). They're no longer there in #4486.

### Save game and other files

[Vectron's Claw #4486.zip](https://github.com/dcs-liberation/dcs_liberation/files/10055103/Vectron.s.Claw.4486.zip)

**Comment by RndName** [comment]
@DanAlbert i did some research why this is happening because this is a result of the ground object refactor i did. 

The line that changed the behaviour is this one: https://github.com/dcs-liberation/dcs_liberation/commit/d154069877c43eb10b5931a28690c6de7eb0cb98#diff-30ffaada26778ba12c0b151d5c960546b953608f0bbe5e0fe6d943096c206ac9L118-R119 

![grafik](https://user-images.githubusercontent.com/6678803/203780462-dd65c1e1-20dc-408e-aa32-45d26bfe708e.png)

Just by reading the code i would expect that only AA and EWR should be available in this dropdown list. But after debugging 5.2.1 i see that every `VehicleGroundObject` has the `dcs_identifier = AA`.

![grafik](https://user-images.githubusercontent.com/6678803/203780881-eb8469f3-0bb6-49bc-96c6-a11ab00d2cae.png)

Thats why in 5.2.1 also Vehicle Groups and more would appear in that list.

The question from my side is: what was expected to appear in that list?

**Comment by DanAlbert** [comment]
> The question from my side is: what was expected to appear in that list?

IMO it doesn't make sense for individual vehicles to show up there, since vehicles move so precise waypoints aren't useful, but including the target area as an option makes sense. OTOH since it was an option before I bet changing it will make someone angry and I just don't have the energy to fight that battle any more. Up to you.

**Comment by Starfire13** [comment]
Individual ground unit waypoints isn't very helpful anyway since they scatter after the first hit. But definitely having a single waypoint for static groups is very handy for TGP slaving to waypoint.

**Comment by RndName** [comment]
I dont really have an opinion on that one but whatever we want to do with it we also have to think about the other Ground Objects as well. There are theses Ground Objects
- Buildings
- Missile
- Coastal
- Vehicles
- IadsGroundObject 
- Naval

The current code only takes IadsGroundObjects (SAM, EWR, AAA) into account when adding a waypoint for each unit. all others are skipped. And the "target waypoint" is only generated for the Building Ground Object type (Ammo, Ware, Iads Elements...)

We could also use the "Include all objects from the same location" Toggle which is available as well
![grafik](https://user-images.githubusercontent.com/6678803/203995498-3256e514-cb86-48d3-8356-a5fc63111e0e.png) But this seems to only work well when all these objects are already in the list of possible waypoints. otherwise it will not add any more units...

**Comment by DanAlbert** [comment]
@Starfire13 I merged a fix. Could you confirm that this is now working like you expect it to? I never use this feature myself so I'm not really sure what "right" is.

**Comment by Starfire13** [comment]
Yep, appears to be working fine now.
