### ISSUE TITLE
Front line air defenses should be hidden on MFD.

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#2568]
Presently you can see the air defenses that are deployed on the front line on the MFDs.  Should this be hidden as the front line is more organic?

In this image you can see the front line as the four `A` marking AAA on the F-16's HSD.
![image](https://user-images.githubusercontent.com/74509817/203202042-cf14bdec-ed85-4bb0-80fe-308b475e9dbd.png)

I was thinking we just need to set `HIDDEN ON MFD` here?

![image](https://user-images.githubusercontent.com/74509817/203203279-ef6f5971-361d-441d-a33a-712f1d37b71c.png)

**Comment by DanAlbert** [comment]
> Should this be hidden as the front line is more organic?

Yeah, makes sense to me.

**Comment by RndName** [comment]
Well, did ED fix the issues with these settings? See #1570

**Comment by SnappyComebacks** [comment]
> Well, did ED fix the issues with these settings? See #1570

`HIDDEN ON MAP` is not `HIDDEN ON MFD`.  In my quick test, `HIDDEN ON MFD` does appear to work.

**Comment by RndName** [comment]
> `HIDDEN ON MAP` is not `HIDDEN ON MFD`.  In my quick test, `HIDDEN ON MFD` does appear to work.

I know it should have different effects but if you read through the linked dcs issue it was not doing what would be expected. Thats why i liked you that issue because i spent quite some time just recognizing ED messed that up completly

If you tested it then ED seems to have fixed that. Good thing then.
