### ISSUE TITLE
BAI currently plannable against resource sites

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2618]
### Affected versions

Development build

### Build information

DCS Liberation 7.0.0 (also present in 6.0.0)
Build 4551
Git revision 3863b8ef4097a7c103834a529a5b6792a9b21913

### Description

BAI missions are currently plannable against statics like map objects and other buildings, even though it shouldn't be. I suspect this might be one cause of the reports from users that aircraft are not hitting their targets.

As you can see here, both a BAI and a strike flight have been planned for a map object resource site.

![Screenshot 2022-12-04 232758](https://user-images.githubusercontent.com/72491792/205490398-ca6e8003-79e1-43de-acd5-2fd921889580.jpg)

### Save game and other files

[BAI on Resource Site Example #4551.zip](https://github.com/dcs-liberation/dcs_liberation/files/10148473/BAI.on.Resource.Site.Example.4551.zip)

**Comment by DanAlbert** [comment]
Not a regression from 5.x (or probably ever). I think I'm going to avoid including this in 6.1.0 because I'm worried about breaking saves that already have BAI missions planned against these targets...

The fix here probably has some nuance. I think since the ground unit groups were reworked it is actually possible to have vehicles at a resource site, so we probably should allow this mission _sometimes_, but it won't be at all clear to the player (unless they've done something crazy like read the manual) that BAI attacks vehicles, not buildings.
