### ISSUE TITLE
Crash at campaign victory

### ISSUE THREAD

**Issue by rlerallut** [dcs-liberation/dcs_liberation#2690]
### Affected versions

6.0.0

### Build information

DCS Liberation 6.1.0

### Description

Context : 
Dunkirk campaign, captured (in DCS) the last enemy base. Finished the DCS mission, then moved to process the results in Liberation and ... callstack : 
![image](https://user-images.githubusercontent.com/2106199/210929624-b3c4b8cf-32ef-45a9-a21b-8ac8e4a70b48.png)

Problem : 
In Game.initialize_turn, the call to set_bullseye() fails if there is no more airbase on either side (assertion failed in theater.closest_opposing_control_points). Unfortunately, that call happens *before* the check for win/loss conditions in game.initialize_turn 

Expected : 
A splashscreen or a message congratulating me for my skill and persistence in taking the last enemy airbase and winning the campaign ! :))) 

=> I guess you can move the bullseye call a few lines lower, after the win/loss check, that should do it

### Save game and other files

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/10357346/liberation.log)

**Comment by Starfire13** [comment]
Yes, there is already an FR filed for an end of campaign splash screen, rather than ending with an error (I'd link it but I'm on mobile and I hate the GitHub mobile app!). It's one of those QOL things that's just been around for a long time but hasn't been worked on. If you have the skills to fix it, please feel free to submit a pull request. I for one would love a splash screen. 🙂

**Comment by DanAlbert** [comment]
The duplicate is pinned at the top of the tracker.

**Comment by rlerallut** [comment]
This is not a duplicate for nice UI. It's about a crash. Read the issue title if nothing else.

**Comment by Starfire13** [comment]
> This is not a duplicate for nice UI. It's about a crash. Read the issue title if nothing else.

Yes, it's been like that since forever. You get a message in the message box and then an error. It's one of those things that we've just come to live with while waiting for someone to work on it. It's just not high priority because by that point, you have already won anyway so the error message isn't preventing play.

**Comment by DanAlbert** [comment]
And for the inevitable "why isn't that a priority?": because there are so, sooooo many things that bug the shit out of me that happen long before the end of the game. Finishing a campaign is a rare thing compared to all of the other problems.

**Comment by rlerallut** [comment]
Of course. Your software, your choices. I hate to see error popups in mine but our tolerance levels may be different. :) Someone pointed me to the Retribution fork that seems to have fixed that issue (move the win/loss check above the call to set_bullseye).
Anyway, thanks for Liberation, it's always good fun, and best wishes to you all for 2023.

**Comment by DanAlbert** [comment]
Of course we don't like crashes. I just hate other problems _more_ :)

**Comment by DanAlbert** [comment]
(and since you mention that you probably do know how, like Starfire said, feel free to send us a patch)
