### ISSUE TITLE
88 Flak Kdo not generated; will not engage aircraft without Kdo

### ISSUE THREAD

**Issue by clutchtomcat** [dcs-liberation/dcs_liberation#2702]
### Affected versions

6.0.0

### Build information

6.0.0

### Description

The templates and scripts all indicate that the Kdo should be generating with Flak groups, however it is not. There are two scenarios where this happens:

1. Factions using any coalition other than "Third Reich" or "Combined Joint Task Forces Red" do not have access to the Kdo unit, thus user is unable to manually add it to the group.
2. Factions using the "Combined Joint Task Forces Red" are still not generating Kdo with flak groups. Manually adding the Kdo in the Mission Editor allows them to engage*.

Attaching Liberation save file, .miz file, and faction file.

*88s do not properly engage aircraft faster than 350KGS, making them unsuitable for Korean War/Early Cold War scenarios. KS-19 is the better option but I have another bug report open on those not being generated at all. It seems that flak for Early Cold War is a bit buggered at the moment.

### Save game and other files

[Flak18.zip](https://github.com/dcs-liberation/dcs_liberation/files/10526061/Flak18.zip)

**Comment by DanAlbert** [comment]
Your faction needs to be updated for 6.x. It does not include the `preset_groups` field. Adding the following allows the Kdo to generate:

```
  "preset_groups": [
    "Flak"
  ]
```

I don't remember how this particular system works, I just looked at the German 1944 faction since you mentioned that on works. Poking around, I think any layout (`resources/layouts/*`) that has `generic: true` is something that is automatically available to all factions, but others have to be named explicitly in the faction's `preset_groups`. The generic `AAA Site` layout does not support the Kdo, which is why your faction would not generate it. The `Flak` and `Freya` layouts do support the Kdo though.

**Comment by clutchtomcat** [comment]
Odd that they weren't updated with the Preset Groups; none of my factions have it and all of them came in the 6.0.0 package. It looks like they're in the 6.1.0 package now so I'll switch over.
