### ISSUE TITLE
Red AI does not buy planes with certain maps and factions

### ISSUE THREAD

**Issue by Schneefl0cke** [dcs-liberation/dcs_liberation#2711]
### Affected versions

6.1.0

### Description

If I choose the Mariannas campaign, the Red AI will not buy planes (or only 1 single tanker) with certain factions.
One such faction is russia 1955
On the Falklands Gran Polvorin the russian 1950 only buys 8 planes of a single type, regardless of money available.

### Save game and other files

[bugReport.zip](https://github.com/dcs-liberation/dcs_liberation/files/10535819/bugReport.zip)

**Comment by DanAlbert** [comment]
(only triaging to 7 because this behavior hasn't changed in quite some time so probably is not a regression)

**Comment by Starfire13** [comment]
Conversation on discord with Schneeflocke suggests this is due to misunderstandings about the way the autoplanner currently works (e.g. that the autoplanner will not "stock up" aircraft but will only buy aircraft it can immediately task for missions), and isn't actually a bug. However, the conversation did also highlight that certain factions do not work particularly well with certain campaigns, and that users should keep this in mind.

**Comment by docofmur** [comment]
I ran a few test missions with this exact setup and behavior seems to be normal, I read through the discord conversation and this does not seem to be a bug. Not all factions will work on all maps but in this instance it will work if the target distances aren't too long
