### ISSUE TITLE
mission generator fail

### ISSUE THREAD

**Issue by LorenzoBoccaccia** [dcs-liberation/dcs_liberation#2729]
### Affected versions

6.1.1

### Build information

DCS Liberation 6.1.1

### Description

mission fail at generation, with or without fast forward to first encounter

### Save game and other files

save game: [err.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/10674055/err.liberation.zip)
log file:  [liberation.log.zip](https://github.com/dcs-liberation/dcs_liberation/files/10674069/liberation.log.zip)

exception:
Traceback (most recent call last):
  File "qt_ui\widgets\QTopPanel.py", line 288, in launch_mission
  File "qt_ui\simcontroller.py", line 76, in generate_miz
  File "game\sim\gameloop.py", line 67, in pause_and_generate_miz
  File "game\sim\missionsimulation.py", line 51, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 106, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 201, in generate_ground_conflicts
KeyError: UUID('82284feb-1f38-4b56-bfeb-6d3648d86efa')

**Comment by DanAlbert** [comment]
On the off chance you still have it, could you upload the save from the previous turn and the state.json file? I don't know if we'll need it yet, but it's better to ask now when there's at least a remote chance it isn't too late...

**Comment by LorenzoBoccaccia** [comment]
previous turn should be this: 
[last_turn.zip](https://github.com/dcs-liberation/dcs_liberation/files/10674281/last_turn.zip)

state is lost, sorry

**Comment by DanAlbert** [comment]
Thanks! Hopefully we won't need it.

**Comment by DanAlbert** [comment]
My best guess is that the save was corrupted at some point, but not catastrophically enough to stop you from continuing to the next turn. The data in the save (both of them) is invalid, and I see no way for the bad state to have arisen short of a non-fatal crash during turn initialization. Skipping to the next turn does fix the bug (which doesn't _prove_ my theory, but it's a hint in that direction since skipping the turn will reset that particular bit of state).

Unfortunately without the inputs needed to create this bad game state, there's no more investigation we can do. I will fix that terribly unreadable error message to at least name the control point rather than just its UUID though.

**Comment by DanAlbert** [comment]
Actually, no, there's no reason for that bit of data to even be saved. That can be generated during mission generation so it can't possibly be corrupted.

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/2791 fixes it.
