### ISSUE TITLE
NoneType has no attribute 'load_from_dict'

### ISSUE THREAD

**Issue by dimkzr** [dcs-liberation/dcs_liberation#2732]
### Affected versions

6.1.1

### Build information

DCS Liberation 6.1.1

### DCS version

DCS 2.8.2.35759 Open Beta - 27.01.2023

### Description

Getting this error when trying to generate a campaign based on a modified Liberation mission file ("grabthars_hammer.miz" in this case):

![Screenshot - 230209 02_27_42](https://user-images.githubusercontent.com/16318490/217675951-b4744ab8-51b8-438a-9aef-209d2a4003b7.png)

This issue [has been reported about a year ago](https://discord.com/channels/595702951800995872/595706079459934208/954404649111261184) and allegedly fixed. Seemingly resurfaced once again.

### How to reproduce

Opening an re-saving the mission, without even touching anything inside, is enough to trigger the error.

### Save game and other files

[vanilla_and_edited_MIZ_files.zip](https://github.com/dcs-liberation/dcs_liberation/files/10690696/vanilla_and_edited_MIZ_files.zip)

**Comment by DanAlbert** [comment]
I think the problem is that the miz is too new for the version of pydcs we have (both in 6 and in the development branch, currently). The miz contains a reference to an airport 22, but that map has no airport 22 according to pydcs. If I create a fresh mission in the ME, its warehouses file also includes a reference to airport 22, so we probably need a new terrain export for that map.

I'm not sure if pydcs can be safely modified to ignore that error. Liberation doesn't need it while it's generating the campaign, but we're not the only user. I'll send the PR to update the terrain export and pull that back down, but I don't think we can proactively defend against this kind of break. This is just going to happen periodically for maps that are still in active development.

**Comment by dimkzr** [comment]
> The miz contains a reference to an airport 22, but that map has no airport 22 according to pydcs.

Just FYI: there are currently two unfinished airports on Falklands: "CaletaTortel" (beyond the current map boundaries) and "Cullen" (currently exists only as a marker; likely coming in the next DCS update).

**Comment by DanAlbert** [comment]
Yes, Caleta was the problem. The fix is already up in pydcs (https://github.com/pydcs/dcs/pull/292), and I've confirmed it fixes the attached campaign.

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/2772 is the fix on our end.

**Comment by DanAlbert** [comment]
Fixed in 7. Unfortunately pydcs updates (which is where the bug was) cannot be backported without breaking save compat.
