### ISSUE TITLE
Unable to save new zipped campaigns

### ISSUE THREAD

**Issue by dleffler** [dcs-liberation/dcs_liberation#2748]
### Affected versions

Development build

### Build information

All versions since moving to new zipped format

### Description

I ALWAYS receive an error when beginning a campaign or attempting to to save it.

```
[WinError 17] The system cannot move the file to a different disk drive: 'D:\\Temp\\tmp_alppaps.liberation.zip' -> 'C:\\Users\\dleff\\OneDrive\\Documents\\My Games\\DCS.fast2\\Liberation\\Saves\\autosave.liberation.zip'
```
I have a multi-ssd system and the app, DCS, & My Documents and my 'temp' folder are on different drives.

### Save game and other files

[WinError 17] The system cannot move the file to a different disk drive: 'D:\\Temp\\tmp_alppaps.liberation.zip' -> 'C:\\Users\\dleff\\OneDrive\\Documents\\My Games\\DCS.fast2\\Liberation\\Saves\\autosave.liberation.zip'

**Comment by DanAlbert** [comment]
Fix won't be difficult, but FYI having temp and your user directory on different file systems is probably slowing down all kinds of save behaviors (games or otherwise). Saving to temp and moving the result over the old file is a very common practice, because that prevents a failed save from corrupting your existing save. If they're on different file systems they can't be moved; they have to be copied, which is slower.

**Comment by DanAlbert** [comment]
@dleffler can you include the full stack trace? I don't have this setup so I can't test it myself, and without the full context I can only guess at which line is causing the problem. I'm reasonably confident, but since I can't feasibly test this I'd rather be sure before merging a fix.

(and please include the context in the help -> report an issue dialog so I can be sure those line numbers match up)

**Comment by DanAlbert** [comment]
Alternatively, try https://github.com/dcs-liberation/dcs_liberation/pull/2758 and lmk if it fixes it.

**Comment by Variosss** [comment]
> Alternatively, try #2758 and lmk if it fixes it.

I had the same problem as dleffler and this fixed the issue.

**Comment by DanAlbert** [comment]
Good enough for me. Merged. Thanks for verifying 👍
