### ISSUE TITLE
bad IP placement when target is at or near the center of a large, circular threat zone

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2754]
### Affected versions

Development build

### Build information

DCS Liberation 7.0.0
Build 4754
Git revision a73c06223d085d193a446dc408e9103a2da9892f

### Description

On the South Atlantic Map, flight routing requires a great deal of manual adjustment as it doesn't take the most direct and safe route to the target, instead deviating significantly in order to approach their target from the north or the south. Here's an example with 4 flights, all of which do not take a direct route to their target.

![Screenshot 2023-03-13 225927](https://user-images.githubusercontent.com/72491792/224696883-16db8eda-020b-4d43-a0a7-0dabc241b7dd.jpg)

I believe this is an issue with the navmesh.

![Screenshot 2023-03-13 230425](https://user-images.githubusercontent.com/72491792/224697743-e17e45c1-abad-402f-b995-065cd5128b8d.jpg)

The route selected is inefficient, and even taking into account the distance travelled in the "red zone" on the nav mesh, a more direct route would actually cover a shorter distance. For example, this route is roughly 94 nm long.

![Screenshot 2023-03-13 230854](https://user-images.githubusercontent.com/72491792/224697972-78e479b2-7166-4ff5-8f90-3a9954e91ddd.jpg)

But if the flight came in directly from the east, it would actually get to the target in a shorter distance.

![Screenshot 2023-03-13 230930](https://user-images.githubusercontent.com/72491792/224698172-e1f64b5f-5593-4b65-9334-f46acb61316c.jpg)

This issue doesn't occur on other maps (at least, not anywhere near to this extent), and it's particularly on the South Atlantic Map where this is a problem because the distances between most airfields are typically greater than normal compared to other maps, so taking unnecessarily indirect routes will result in fuel problems. I am finding myself having to manually fix flight routes way more than I have to on other maps.

### Save game and other files

[Grabthars Hammer #4574 Routing Example.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/10957031/Grabthars.Hammer.4574.Routing.Example.liberation.zip)

**Comment by DanAlbert** [comment]
The navmesh has nothing to do with how any waypoints other than nav points are placed, btw.

This is because the target is in _almost_ the center of a circle, and the IP is being placed in whichever direction allows the flight the minimal threatened travel distance (i.e. away from the center of the circle). That hueristic works very well for targets that aren't nearly centered, but I'll see if there's a reasonable way to clean this up. 

Assuming there's a SAM in there generating that threat, this is technically safer than the direct route, just marginally enough to not be worth it.

If the threat is generated by the airfield rather than a SAM, it is actually directly centered and the closest point on the threat circle is actually all of the points, and it's picking one arbitrarily.

**Comment by DanAlbert** [comment]
Yeah, enabling the off-by-default debug layers (they're expensive so are compiled out of the UI by default) we can see

![image](https://user-images.githubusercontent.com/315852/224880937-e19144af-36f6-483b-b811-875a548a4cd7.png)

The whole white zone is the "permissible" zone, which just means that it means the non-safety constraints (not too close to the target, nor farther from the home airfield than the target is).

If you plan a mission against the much smaller threat zone, where it's possible to have a safe IP, there's also a green zone for the safe region

![image](https://user-images.githubusercontent.com/315852/224881353-c0712c37-08e9-4ce0-a3b8-bca4cefa5b03.png)

If there's a safe IP available within the permissible zone, the point in that zone that's closest to home will be used. If there isn't, but the area around the home airfield is safe, it's as I said this morning: we pick the IP that allowed the minimum amount of threatened travel.

I'm going to think about this one for a while to see if I can come up with a geometric solution (those have served us far better than the alternatives), but if I can't come up with one I suspect something along the lines of calculating the fastest path out, comparing it to the straight shot home, and preferring the latter if the difference is minimal will work fine.

**Comment by DanAlbert** [comment]
I think we can do something like this:

![224880937-e19144af-36f6-483b-b811-875a548a4cd7](https://user-images.githubusercontent.com/315852/230569229-5336ec87-8dce-4506-97d7-29610084546d.png)

Buffer the threat zone inward by the minimum distance from the permissible zone and the boundary of the threat zone (plus a little wiggle room to make it so _nearly_ centered targets don't have a similar problem), then rather than picking the point we currently do (the point on the permissible zone closest to the edge of the threat zone), pick the point on the permissible zone _and_ within this new zone. In the example above your IP would end up on the blue X.

If there were some other SAM that made the approach from home less safe, like here:

![224880937-e19144af-36f6-483b-b811-875a548a4cd7 (1)](https://user-images.githubusercontent.com/315852/230569529-12b6401d-ff9b-447c-a5e3-5a3aabdff02a.png)

You'd still end up with a slightly closer placement, even if it's still in largely the same spot. Still, in the second example, there's a _lot_ more value in routing around.

That only came to me a few minutes ago (plus the time required for doodling), so it may not actually work for more complicated examples. It's worth trying though. I'll try to do that soonish, but I'm guessing I probably won't be able to this weekend.

**Comment by Starfire13** [comment]
Looks good to me. :)

**Comment by DanAlbert** [comment]
Really wanted to fix this for 7, but the apache bug is forcing me to punt anything that's not a regression, and I'm pretty sure this is a very old bug.

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/3076 implements this. The bad case reported here is definitely fixed. I've also eyeballed the AI generated blue ATOs for turn 1 of Black Sea and Abu Dhabi, and both appear to be marginally improved. I've set it to auto-merge because the only way we'll really prove this out is by letting people try it. If it causes significant other problems it's easy enough to revert.

**Comment by DanAlbert** [comment]
Grabthar's Hammer is looking _much_ better (the highlighted flight is the same target/origin as the terrible routing in the OP):

<img width="404" alt="image" src="https://github.com/dcs-liberation/dcs_liberation/assets/315852/a6328195-73b3-41ad-9645-13fd04adb00f">

**Comment by Starfire13** [comment]
That looks waaaay better!
