### ISSUE TITLE
TALD flights (both F14 and F/A-18) will not launch TALDs unless Release Weapon Type is manually changed to Decoy

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2780]
### Affected versions

Development build

### Build information

DCS Liberation 7.0.0
Build 4775
Git revision 5c72e0754a438af1ea1cb1643528da7ce1df4b42

### Description

Unless the Attack Group commands under the Ingress waypoint have their weapon release type changed to Decoy, both F-14s and F/A-18s will not release TALDs.

For F-14s, the default is Guided (because they use SEAD for TALD flights). For F/A-18s, you can theoretically use either (I have tested that both work provided release type is manually changed to Decoy). This is a bigger problem for Hornets because with the F-14s, they only have one SEAD weapon, which is the TALD. The Hornet has HARMs, so you can't just set weapon release type to Decoy, meaning Hornet either needs its own mission type for TALDs, or the weapon release type needs to be set based on loadout (e.g. if it's set on Liberation SEAD and carrying HARMs, use the standard Auto release type, and it's set on Liberation CEAD and carrying TALDs, use the Decoy release type).

### Save game and other files

Note that if you want to use this save for testing, you will have to manually change the weapon release type for the DECOY and DECOYF14 flights to Decoy.
[TALD Test 3.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11187946/TALD.Test.3.liberation.zip)

I have already manually edited it in this .miz file:
[liberation_nextturn.zip](https://github.com/dcs-liberation/dcs_liberation/files/11187962/liberation_nextturn.zip)

There are four flights in total, 2 Hornet and 2 Tomcat flights. 2 are unedited (they will not launch TALDs) and 2 are edited (these will launch TALDs).

**Comment by DanAlbert** [comment]
The AI can't really handle mixed load outs for ground attack (see the big on the front page), but I think it'd be straightforward to make any flights with decoys use that release mode. Any AI hornet with both TALDs and HARMs will not work the way you want, but maybe it'd work if weade two attack tasks?

**Comment by Starfire13** [comment]
Combined loadouts actually do work for some reason if you set weapon type to auto (but not if you have a pure TALD loadout, go figure), though the AI doesn't really know how to use combined HARM and TALD loadouts anyway. They fire their HARMs at max range, and then follow up with the TALDs, which arrive 5 minutes after the HARMs. So I always separate my HARM and TALD flights.

**Comment by DanAlbert** [comment]
A certain amount of solving this problem is definitely "don't do that" coupled with not having mixed default load outs.

**Comment by Starfire13** [comment]
Agreed.

**Comment by Raffson** [comment]
> but maybe it'd work if weade two attack tasks?

Give that a try, you won't be disappointed 😉

Keep the order of the tasks in mind, as that will have an effect. Imo having a guided attack should precede an unguided attack, seems to produce the best results...

**Comment by Starfire13** [comment]
> > but maybe it'd work if weade two attack tasks?
> 
> Give that a try, you won't be disappointed 😉
> 
> Keep the order of the tasks in mind, as that will have an effect. Imo having a guided attack should precede an unguided attack, seems to produce the best results...

The order in which they fire the weapons isn't really the issue though (but it's good to know the order matters, thanks). Because HARMs travel so much more quickly than HARMs, the HARMs arrive minutes before the TALDs get engaged.

**Comment by Raffson** [comment]
> The order in which they fire the weapons isn't really the issue though (but it's good to know the order matters, thanks). Because HARMs travel so much more quickly than HARMs, the HARMs arrive minutes before the TALDs get engaged.

Yes and no 😅
Regarding this specific issue it's a no, because all that's needed to solve this issue is bumping pydcs now that the decoy weapontype was merged.
But considering mixed loadouts it becomes a yes (ish), because as you sort of pointed out you'd want the AI to release their decoys before firing HARMs. But unless the radar is silent, in which case the SEAD flight will continue to fly towards the target until it found its target before releasing the HARMs, this won't have too much effect due to the travel speed you mentioned. I guess having the flight circle around before releasing the HARMs is a possible solution, or fragging a separate SEAD package and playing with the TOT, but that defeats the purpose of a mixed TALD/HARM loadout.
On the other hand we might be worrying for nothing, because while integrating decoys my tests with F14s against SA-2 batteries(coldwar setup) made me conclude that those TALDs have a ridiculous RCS, they always seem to draw the SAMs attention to the point where the site simply depletes all of its missiles against this TALDs. Theoretically, as soon as the site starts engaging the TALDs, the HARMs should either be off the rails already, or about to leave the rails momentarily, and as long as that SAM's radar is active, the HARM should be able to do its thing, regardless of the TALDs still being 20NM out. Another thing to keep in the back if your mind is to set the minimum altitude restriction for releasing TALDs, because you definitely don't want the AI to drop those under a certain altitude.
But yeah, I think I'm gonna do some testing 😂

**Comment by Starfire13** [comment]
Yeah, the issue is just with mixed loadouts and my feeling is to just not use mixed loadouts for AI flights. I sometimes use mixed loadouts on my own aircraft, but I keep my AI CEAD and SEAD flights separate (different packages) with no mixing of ordnance, and time it so the HARMs from the SEAD flight start hitting after the TALDs from the CEAD flight have gotten close enough (they drop them like 50 nm out so it takes a while before they are in range to do anything). And yes, as long as there are TALDs in range, the SAMs will go after them instead of HARMs, though I don't know if it's due to RCS or just scripted that way.

I have played around with the minimum altitude restriction in the past and found that DCS really just takes its as a loose suggestion, but it's not a big problem most of the time anyway. The CEAD flights will drop their decoys at 20,000 feet by default (which is fine). The only time this gets badly screwed up is if they take evasive action before their launch point. I will sometimes disable evasive behaviour (but keep countermeasures active) for selected SEAD flights because I really wish the AI would not take evasive action. Their idea of evasive action is to just jink all over the damn sky and typically end up low and slow and they might evade one missile, occasionally two, but they invariably get killed anyway without having done much good beyond acting as a very expensive TALD. I would much rather they just stay on target, launch their missiles and bug out. And if they don't make it out in time, at least they've done their job. Cos if they go evasive, they don't do their job AND they die anyway.

**Comment by Raffson** [comment]
> they drop them like 50 nm out so it takes a while before they are in range to do anything

That seems to be the biggest problem indeed. I would say ideally the TALDs get released just before entering the engagement radius, although that can vary massively it's definitely worth thinking about how to perhaps use this value in a smart way.

> I have played around with the minimum altitude restriction in the past and found that DCS really just takes its as a loose suggestion, but it's not a big problem most of the time anyway. The CEAD flights will drop their decoys at 20,000 feet by default (which is fine). The only time this gets badly screwed up is if they take evasive action before their launch point. I will sometimes disable evasive behaviour (but keep countermeasures active) for selected SEAD flights because I really wish the AI would not take evasive action. Their idea of evasive action is to just jink all over the damn sky and typically end up low and slow and they might evade one missile, occasionally two, but they invariably get killed anyway without having done much good beyond acting as a very expensive TALD. 

I initially started playing with that minimum altitude restriction as a specific counter-measure for SEAD flights that would dive down to the deck around ingress as a result of an engagement, and found that in that particular case it works pretty well. AI will climb back up before releasing their decoys. For HARMs we can't really do that, since it's using the 'EngageGroup' task instead of 'AttackGroup', and so we need to force the AI to fly towards the SAM site in order to detect it. You could also set the 'visible' option on, but when if Skynet is turned on as well, AI will simply fire off their HARMs and in some cases those HARMs start tracking a completely different target, so that's no good either. Imo, SEAD should RTB as soon as it released all of its AG ordnance.

> I would much rather they just stay on target, launch their missiles and bug out.

Completely agree with you there, but things get difficult when the loadout consists of TALDs alone. As you've mentioned (either in this issue or one of the others) there's no 'RTB on out of ammo' for decoys, which is obviously annoying. I guess the trick is to filter out the TGT waypoint depending on the loadout, i.e. avoid TGT when using TALDs only.

**Comment by Raffson** [comment]
Perhaps I should clarify what I mean with "filtering the TGT waypoint". In the code there's this flag called "only_for_player", which is basically what I'm referring to. It will skip the waypoint in case of an AI, and so if we can set that flag according to whether or not the AI has anti-radiation missiles loaded up, this might be a viable solution.

**Comment by Starfire13** [comment]
> Perhaps I should clarify what I mean with "filtering the TGT waypoint". In the code there's this flag called "only_for_player", which is basically what I'm referring to. It will skip the waypoint in case of an AI, and so if we can set that flag according to whether or not the AI has anti-radiation missiles loaded up, this might be a viable solution.

Yep, agreed. That's pretty much what I suggested in #2781

**Comment by Raffson** [comment]
> Yep, agreed. That's pretty much what I suggested in #2781

Riiight, I missed that one.

Anyway, I've been testing for the last couple of hours and I'm noticing something interesting. When splitting up the waypoint tasks to use different weapon categories and removing the TGT waypoint, the AI seems to circle between ingress and egress until the ordnance reaches its target, and only after that will it recommit to launch the next category. In a way I would say this makes sense, because the AI will use its TALDs first, circle back and have the SAM fire at the decoys, recommit with HARMs and while at it I tried throwing in some JSOWs as well. Seemed to work although the AI's timing wasn't always ideal. Then again, it beats having your SEAD flight fly into the AO and get shot down. 😂 
Also worth noting that this was specifically for F-18s (and F-14s partially, they hold until the TALDs are destroyed) because I also had an F-16 flight with 2 HARMs, 1 JSOW and 1 AGM-65D, which worked flawlessly over and over again.

**Comment by Starfire13** [comment]
This fix does not appear to be working. Hornet TALD flights are still being created with their weapon type set at auto instead of decoys.

**Comment by zhexu14** [comment]
@Starfire13 , thanks, I've overlooked setting up the ADM141 YAML data for the variant used on the Hornet as I originally only tested on the F14. This omission resulted in the TALD not being picked up by Liberation as a decoy on Hornets. This issue is fixed in this PR: https://github.com/dcs-liberation/dcs_liberation/pull/2869
