### ISSUE TITLE
WW2 fighters with premade squadrons have a smaller default mission set than randomly generated squadrons

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2785]
### Affected versions

Development build

### Build information

DCS Liberation 7.0.0
Build 4777
Git revision 8150176fc62d7ead6faab45a615e522b5afd87fd

### Description

WW2 fighters with premade squadrons are restricted to the following mission types in their squadron YAML.
  - CAS
  - Escort
  - Intercept
  - OCA/Aircraft
  - Fighter sweep
  - BARCAP
  - TARCAP

However, randomly generated squadrons have a larger set of mission types available as by default they can also perform
  - Strike
  - DEAD
  - BAI
  - OCA/Runway

As an example of this problem, here is a campaign with 2 Dora-9 squadrons. However, Liberation comes with only one premade Dora-9 squadron, so one of the 2 squadrons will be randomly generated.

![Screenshot 2023-04-15 203704](https://user-images.githubusercontent.com/72491792/232208927-0b8ad8c8-3b44-4dc5-898d-3d34aef79407.jpg)

### Save game and other files

I am attaching a zip file containing the files of the campaign I am currently working on (.miz and .yaml, and the faction file), where I first noticed the problem.

[final_countdown_2 (2).zip](https://github.com/dcs-liberation/dcs_liberation/files/11239140/final_countdown_2.2.zip)

**Comment by DanAlbert** [comment]
Is the request here that the premade squadrons be changed? There doesn't appear to be a bug here, this was just a choice (whether intentional or not) by the author of the squadron.

Or are you asking for the ability to override the squadron's default mission types?

Or are you saying that the squadron definition is wrong, they should be allowed, but not necessarily auto-assignable? Those are two separate fields in the squadron yaml, and are the reason the UI won't allow you to enable the mission type.

Or are you asking for the `secondary` field of the campaign yaml to override the squadron's preferences?

Or are you asking for the squadron picker to ignore any squadron selection that cannot meet the full set of secondary mission types (which is likely impossible for most factions).

(I have a preference, but before I convince you of it I want to see if you agree)

**Comment by Starfire13** [comment]
My feeling is that unless there is good reason, the permissable mission types for a squadron should include all mission types that air frame can perform. It should be up to the user to then selectively disable mission types they don't want that squadron to perform, during campaign creation. At the moment, all premade WW2 fighter squadrons have a smaller mission set than what they are capable of, and my guess is whoever set up those squadron yamls assumed that was all the missions those aircraft could perform. However, WW2 aircraft only have 1 premade squadron each (apart from the Spitfire which has 2), which means that a lot of the time, you have one squadron of each plane type with a significantly reduced mission set in a campaign unless the user manually looks for the premade squadrons and re-enables those mission types.

**Comment by DanAlbert** [comment]
> My feeling is that unless there is good reason, the permissable mission types for a squadron should include all mission types that air frame can perform. It should be up to the user to then selectively disable mission types they don't want that squadron to perform, during campaign creation

The intent is for players to be able to create real world squadrons that don't deviate from their role, or for larger groups to pre-configure the way their group is organized without having to do so per campaign.

That, combined with what you're asking for, is option 3: "Or are you saying that the squadron definition is wrong, they should be allowed, but not necessarily auto-assignable? Those are two separate fields in the squadron yaml, and are the reason the UI won't allow you to enable the mission type."

Oh, as I just went to fix this, I see that I was previously confused by part of the implementation that doesn't match what you can express in the squadron yaml: the allowed mission types and the default auto-assignable mission types are not separately assignable in the yaml. I think I'll just flip the current handling of `mission_types` to set the auto-assignable types rather than the allowed types, which sounds like it's what you (and everyone else that has ever written one of these) expected.

tbh there's probably more at play in most of the squadron files... I bet the authors thought the field was required. It definitely isn't and should never be used unless you want to intentionally exclude a squadron from some missions...

**Comment by Starfire13** [comment]
> The intent is for players to be able to create real world squadrons that don't deviate from their role, or for larger groups to pre-configure the way their group is organized without having to do so per campaign.

That should be the case if they had explicitly defined that they want that particular premade squadron at that particular airfield in the campaign yaml, yes. But during campaign creation, the first squadron on the list (and thereon down if there are multiples) is always picked. So if the first squadron for that aircraft happens to be a squadron with a restricted mission set (and right now, all the WW2 fighter squadrons have a restricted mission set), then every time you use that aircraft type, you're going to have to go in and manually expand the allowed mission types back to the full mission set that aircraft can fly.

If players want to alter the default mission types for specific premade squadrons, they are free to do so on their own installs. But I think that, as shipped, the WW2 aircraft should come with all the mission types they can fly enabled by default, I mean, practically every aircraft type only has a single squadron defined anyway, effectively serving as a template.
 
> That, combined with what you're asking for, is option 3: "Or are you saying that the squadron definition is wrong, they should be allowed, but not necessarily auto-assignable? Those are two separate fields in the squadron yaml, and are the reason the UI won't allow you to enable the mission type."

Yes, I think there's really no reason to disable an allowed mission type for a squadron. Turning off the auto-assignable check box is sufficient. At the very least, it will be an indication to the player of what an aircraft can do compared to what it's currently allowed to be assigned to do.

> Oh, as I just went to fix this, I see that I was previously confused by part of the implementation that doesn't match what you can express in the squadron yaml: the allowed mission types and the default auto-assignable mission types are not separately assignable in the yaml. I think I'll just flip the current handling of `mission_types` to set the auto-assignable types rather than the allowed types, which sounds like it's what you (and everyone else that has ever written one of these) expected.

> tbh there's probably more at play in most of the squadron files... I bet the authors thought the field was required. It definitely isn't and should never be used unless you want to intentionally exclude a squadron from some missions...

Yeah, I think everyone just copy-pasted from the first version of the squadron yaml, where those mission types had first been defined.

**Comment by DanAlbert** [comment]
> That should be the case if they had explicitly defined that they want that particular premade squadron at that particular airfield in the campaign yaml, yes. But during campaign creation, the first squadron on the list (and thereon down if there are multiples) is always picked.

Yes, that's interop with the a different desired behavior: curated squadrons capable of the task are preferred over auto-generated squadrons for flavor reasons. If we didn't want that behavior, there wouldn't be a ton of value in Liberation including any non-generated squadrons at all.

**Comment by Starfire13** [comment]
I like that premades are preferred. I don't even mind the occasional squadron that doesn't do a specific mission type because they don't do that in real life. But with WW2 fighters, it's every single squadron that's restricted and has to be fixed. It's a lot of ticking boxes on campaign setup. What's more, on the Caen to Evreux campaign, for example, the majority of squadrons are set to perform BARCAP and no other mission type at all because primary is set to BARCAP and there is no secondary mission type defined (though I kinda feel like if there is no secondary mission type defined, the default should probably be 'any'). So in the case of that campaign, there is a heck of a lot more box ticking.

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/2795 should fix it. Mind trying that out and make sure it matches what you expect? I poked around at a few campaigns and it seems to be behaving the way you describe, but if you've got the time to confirm I'd appreciate it :)

> But with WW2 fighters, it's every single squadron that's restricted and has to be fixed

Right, that's why I asked the first question: "Is the request here that the premade squadrons be changed?"

**Comment by Starfire13** [comment]
> #2795 should fix it. Mind trying that out and make sure it matches what you expect? I poked around at a few campaigns and it seems to be behaving the way you describe, but if you've got the time to confirm I'd appreciate it :)

Ok, will give it a try later today. Thanks for the fix.

> Right, that's why I asked the first question: "Is the request here that the premade squadrons be changed?"

Ah. Yes, that was definitely a big part of the request.  :D

**Comment by DanAlbert** [comment]
>> Right, that's why I asked the first question: "Is the request here that the premade squadrons be changed?"
>
> Ah. Yes, that was definitely a big part of the request. :D

👍 

> on the Caen to Evreux campaign... there is no secondary mission type defined... So in the case of that campaign, there is a heck of a lot more box ticking.

More box ticking to deviate from the campaign designer's intent is always going to be true.

I'm not trying to nitpick, I'm trying to figure out if the problem is the implementation of the system or the design of this handful of campaigns/squadrons.

**Comment by DanAlbert** [comment]
> tbh there's probably more at play in most of the squadron files... I bet the authors thought the field was required. It definitely isn't and should never be used unless you want to intentionally exclude a squadron from some missions...

I was wrong about this too. It seems there were a handful of deviations between intended behavior and actual behavior in here... Will fix that as well.

**Comment by Starfire13** [comment]
> I'm not trying to nitpick, I'm trying to figure out if the problem is the implementation of the system or the design of this handful of campaigns/squadrons.

I'd say it's a bit of a combination of both. Yes, the WW2 premade squadron mission types ought to be fixed (I don't believe it was the intention of whoever created those to restrict all of them to that mission set). However, that issue has also highlighted some of the other areas the system can be improved.

I think it likely that the majority of folks are using a premade because it's the one selected for them during campaign creation, and they may likely not notice that particular squadrons have been given a more restricted mission set than what they are in fact capable of. And part of the reason is there is no easy way to switch between different premades. At the moment, we cannot switch between different premades for a squadron from a drop down list like you can for "Base". If we don't want to always use the first premade squadron for the first squadron of that aircraft type (and so on, down the list), we have to delete the squadron and create a new one. This makes choosing between different premades a bit of a hassle. A "reset to aircraft mission defaults" button on the air wing configuration screen could also help to reduce the amount of clicking.

**Comment by DanAlbert** [comment]
Just updated that PR with the rest of the things discussed here. I think it addresses all the complaints. Whether or not those changes are bug fixes or improved features is a bit difficult to nail down :)

One last thing that comes to mind: the campaign's selection of `primary`/`secondary` will combine to override the mission types from the squadron... so I don't think there's any possible way for `mission_types` in the squadron yaml to have any effect after that PR merges? It must be that it was originally intended to be restrictive of capability... but I'm now convinced that if that was my original intent (it's too long ago for me to remember), that was just a bad idea.

I'm going to look through a bit more and see if I can work out any way for the `mission_types` field to have an effect, but I'm pretty sure that's actually dead code and we can remove it entirely.

**Comment by DanAlbert** [comment]
Yes, there's exactly one place where `mission_types` has an effect after that PR: when you click the "add squadron" button and you've chose a premade squadron. I don't think this is at all useful. It would be nice for the reason I named above:

> curated squadrons capable of the task are preferred over auto-generated squadrons for flavor reasons

(also, it's potentially convenient if you have a squadron for an organized group that, for example, doesn't ever want to fly BARCAP but also doesn't want to fiddle with auto-assign preferences and wants to let the auto-planner drive...)

I think that's probably why I built it the way I did? That group could make their custom squadron that omits the BARCAP mission from the list and could be sure that Liberation would never auto assign those players to BARCAP. But since those squadrons were probably picked up and overridden by the campaign anyway, that seems like such a narrow chance of success as to not be worth it... I'm going to just remove this. It's maybe a good goal but the current design for squadron selection would need a larger overhaul to actually make that work in most cases. The only case where it can currently work is if you're already fiddling with your air wing to add a new squadron, in which case that part is already much more annoying than having to uncheck the BARCAP box for that new squadron.

**Comment by Starfire13** [comment]
Would it be better to change it to disallowed mission types then? That way, squadrons would have the default mission types for that aircraft available except for any specific mission types disallowed in the squadron yaml.

**Comment by DanAlbert** [comment]
But then you're back to the other problem: if the only Dora squadron in Liberation disallowed a bunch of mission types, it can be an annoying surprise when the campaign designer had hoped for a flexible squadron and the player didn't look closely.

I expect YAGNI, and the PR I'm about to upload is going to do what people both wanted and expected.

**Comment by DanAlbert** [comment]
Okay, I think I'm done messing with https://github.com/dcs-liberation/dcs_liberation/pull/2795. lmk when you get a chance to test it. Once you tell me I've actually solved your problems I'll merge it :)

**Comment by Starfire13** [comment]
Sounds good, I'll give it a test this evening.
