### ISSUE TITLE
Liberation unable to create YAML-defined BF-109 squadron at Carpiquet unless there is premade squadron available

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2786]
### Affected versions

Development build

### Build information

DCS Liberation 7.0.0
Build 4777
Git revision 8150176fc62d7ead6faab45a615e522b5afd87fd

### Description

This one has rather stumped me, and I don't know what is causing it. I have 2 BF-109 squadrons in a campaign I am building. While the one that Brucheville gives me no problems, the one at Carpiquet consistently gets converted into an FW-190 Anton squadron UNLESS I add a second premade BF-109 squadron yaml, at which point it will work. However, if I only have a single premade BF-109 squadron, the BF-109 squadron at Carpiquet always gets generated as a FW-190 squadron.

This might potentially be related to the "u" with umlaut in the BF-109's name, which has caused it to be referred to in different ways in different files. It is possible that this is an unrelated problem however, but I am mentioning it here as a potential cause. I suspect the lone premade squadron always gets assigned to Brucheville as it has a lower ID number (5 vs 19)

Examples of differing names:
Squadron yaml for Jagdgeschwader 53: "Bf 109 K-4 Kurfürst"
In the Bf-109K-4.yaml under resources\units\aircraft\" "Bf 109 K-4 Kurf\xFCrst"
In the yaml for Khopa's Caen to Evreux campaign: "Bf 109 K-4 Kurf\u00fcrst"

I have tried all three variants, but none of them allowed me to create a randomly generated BF-109 squadron at Carpiquet.

### Save game and other files

[final_countdown_2.zip](https://github.com/dcs-liberation/dcs_liberation/files/11239171/final_countdown_2.zip)

**Comment by DanAlbert** [comment]
If I'm interpreting the debugger correctly, the problem is actually far more general. Whenever you have something like this in the campaign:

```yaml
- primary: TARCAP
  secondary: air-to-air
  aircraft:
  - Bf 109 K-4 Kurf\u00fcrst
```

The suggestion in `aircraft` will be completely ignored if there is a premade squadron of a different aircraft type that meets the rest of the constraints. That's definitely not the intent.

**Comment by DanAlbert** [comment]
No, it is the name in the aircraft. `"Bf 109 K-4 Kurfürst" != "Bf 109 K-4 Kurf\u00fcrst"`.

`Bf 109 K-4 Kurf\u00fcrst` is not converted by the yaml parser. According to the spec it sounds like it should be if it's quoted in the campaign file, but that doesn't work either.

The reason people have been trying to escape that in the first place rather than just writing ü is because by default Python opens files in the system encoding (okay, it's probably mostly because it's annoying to type on most keyboards), not UTF-8. On Windows (at least, US English Windows), that's:

```python
>>> import locale
>>> locale.getencoding()
'cp1252'
```

Opening the files with an explicit UTF-8 encoding and replacing the escape sequence with ü fixes the problem. We actually get the encoding right almost everywhere. This bug exists only in log config (where it doesn't really matter much), campaign yamls, and theater yamls. https://github.com/dcs-liberation/dcs_liberation/pull/2788.

(We could globally change the default so it's impossible to write more classes of this bug by changing the locale to `en_US.UTF-8` at launch, but I'm not really sure how that might impact folks with Windows installs that use a non-latin derived alphabet, so I'm not brave enough to submit that.)

The reason this was a little annoying to debug is because we don't log this failure. I've added that:

```
2023-04-15 13:02:44,771 :: root :: WARNING :: Bf 109 K-4 Kurf\u00fcrst is neither a compatible squadron or a known aircraft type, ignoring
```

This is only logged rather than an error because there are valid ways to hit this code path (e.g. if you were evil and named a squadron `Bf 109 K-4 Kurf\u00fcrst`, but that squadron wasn't capable of operating from this base).

**Comment by Starfire13** [comment]
Should resources/units/aircraft/Bf-109K-4.yaml be fixed as well then?

**Comment by DanAlbert** [comment]
That one apparently works.

```python
>>> from pathlib import Path
>>> p = Path() / "resources/units/aircraft/Bf-109K-4.yaml"
>>> p.exists()
True
>>> f = p.open(encoding="utf-8")
>>> import yaml
>>> d = yaml.safe_load(f)
>>> d["variants"]
{'Bf 109 K-4 Kurfürst': {}}
```

(thanks for flagging it though, since it used a different escape sequence I hadn't checked it)

Though I'm going to update it (and many others) just for searchability/readability anyway. https://github.com/dcs-liberation/dcs_liberation/pull/2793
