### ISSUE TITLE
Normandy 2.0 Support

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2804]
**Is your feature request related to a problem? Please describe.**
Normandy 2.0 is now available. It is not a separate map from Normandy 1.0. Owners of the original DCS: Normandy 1944 map will receive a free update that enhances the whole area of the original map to the same high detail level as in DCS: Normandy 2.0. The free update will also include the new much larger DCS: Normandy 2.0 total map area and airfields but at a lower level of detail.

**Describe the solution you'd like**
Support for new Normandy 2.0 map

- [x] pydcs terrain export
- [x] update pydcs
- [x] landmap
- [x] icon for new game wizard
- [x] beacon data
- [x] daytime map
- [x] timezone
- [x] weather data
- [x] minor campaign version bump (do this once ready for campaigns)

**Comment by DanAlbert** [comment]
We need a volunteer to create the landmap. Without that this won't be included in 7.

**Comment by Starfire13** [comment]
Might be good to post a message about this on discord with a link to the wiki page by FinCenturion containing the instructions, for higher visibility.

**Comment by DanAlbert** [comment]
Feel free :)

**Comment by DanAlbert** [comment]
(I'll update the FAQ channel to guide folks here as well)

If you're interested in doing the work, see https://github.com/dcs-liberation/dcs_liberation/wiki/Creating-shape-files-in-QGIS-for-map-data. Leave a comment here if you're doing the work to let others know. Don't ask me for help, I don't know how.

Everyone else, use the subscribe button at the right (or below for mobile) to subscribe for updates.

**Comment by Nosajthedevil** [comment]
I'm taking a stab at it - but not making any promises. 

There's a bit of a learning curve with QGIS, I think the current wiki assumes the user has some knowledge about setting it up and using it. I do not, but I've made it to step 3.1 so far -although the ocean map dissolve has been running for 8 hours now and is only at 37% - so I'm hoping I'm doing this correctly.

Also, the wiki doesn't say what you are supposed to do with the landmap .shp files once you generate them. Should I just send them to you? I tried to take a look at the files that were pulled in when Falklands were added, I haven't spent much time there but reading some of the comments I'm wondering what the old method was and if it is easier...

**Comment by Starfire13** [comment]
> I'm wondering what the old method was and if it is easier...

The old method requires someone to draw all the out of bound areas on the map manually. It's very tedious and error prone (it's easy to miss spots that should be marked but aren't). At some point, we'll want to convert all the old maps to this new method, once the way to do it is figured out. You might also want to look up previous conversations with FinCenturion on discord for more info.

**Comment by DanAlbert** [comment]
> I'm taking a stab at it - but not making any promises.

Thanks! I appreciate the effort either way.

> Also, the wiki doesn't say what you are supposed to do with the landmap .shp files once you generate them. Should I just send them to you?

Yeah. Zip them up and upload here or to discord is fine.

>> I'm wondering what the old method was and if it is easier...
>
> The old method requires someone to draw all the out of bound areas on the map manually. It's very tedious and error prone (it's easy to miss spots that should be marked but aren't).

This, but if you want to try that, I don't really care which form I get... I think. There are some things that can't possibly be expressed using the old system. It's not possible to represent islands, for example. Normandy 2.0 might not have a problem with that since the map doesn't extend to the north end of Britain. Jersey, Guernsey, the Isle of Wight, etc would have to be "ocean", or the "land" would have to extend out to cover them.

**Comment by Nosajthedevil** [comment]
Ah ok, I'll keep plugging at it later this week or next week. This way is probably pretty easy once you get the hang of QCIS. Processing takes forever, but it's not like you have to actually do anything while it's running. 

Dissolving the ocean data is at 56% now after maybe 10 hours. I think the problem is that the ocean data I pulled in is for the whole world, I imagine there was a way to cut it down to just the actual map area we needed before dissolving it. Or maybe not, I'm guessing at a lot of this.

**Comment by DanAlbert** [comment]
> I think the problem is that the ocean data I pulled in is for the whole world, I imagine there was a way to cut it down to just the actual map area we needed before dissolving it. Or maybe not, I'm guessing at a lot of this.

Same, but that _sounds_ quite plausible.

**Comment by Nosajthedevil** [comment]
I wouldn't wait for this to be completed before pushing 7.0 if you are trying to get it out.  Dissolving the ocean data is just now at 74% after a day and a half. Pretty sure I did something wrong or that there's a way to do this that will just dissolve for the area that's in the Normandy map. I'll figure it out eventually, but it might be a week before I can spend much more time with it.

Scratch this - I spent 2 minutes watching a video on how to select and delete areas. After this dissolve was completed in 23.77 seconds (I'm a little annoyed with myself, but it happens). I'll move on to the next step sometime this weekend. I don't think there are any high elevation areas in Normandy that will need to be excluded, need to doublecheck, but I can avoid the last step I think.

**Comment by DanAlbert** [comment]
> Scratch this - I spent 2 minutes watching a video on how to select and delete areas. After this dissolve was completed in 23.77 seconds (I'm a little annoyed with myself, but it happens).

😁  That's good news though. I'll go ahead and do the rest of the work just in case. The landmap is a very safe thing to cram into the release at the last second, so if you manage to get in done in time (seriously no pressure, I wasn't planning on having this in 7), why not?

**Comment by Nosajthedevil** [comment]
Quick question - Is there a way to export the actual DCS map into a format that can be viewed externally? I want to try to convert it into something I can pull into QGIS. 

All of the data that's available is recent and might not line up closely with 1944. It would be helpful to add in a layer with the actual DCS map so I can doublecheck that things aren't too far off. I might try converting a screenshot if no one is aware of anything a bit easier. I don't know if it matters that much if it's off a little, but I imagine some towns are very different now.

**Comment by DanAlbert** [comment]
Not afaik. If there were we'd be able to autogenerated these.

**Comment by DanAlbert** [comment]
(and yes, you're correct, that's why we'll never be able to use real world elevation data either)

**Comment by Druss99** [comment]
I believe this is what y'all are looking for. If not, I have a pretty good understanding of how to do it now and I can make adjustments. When I find the time I will try and update the wiki that fin started on.

[Normandy Sea.zip](https://github.com/dcs-liberation/dcs_liberation/files/11548993/Normandy.Sea.zip)
[NormandyLand.zip](https://github.com/dcs-liberation/dcs_liberation/files/11549004/NormandyLand.zip)

**Comment by DanAlbert** [comment]
I'll take a look later tonight and find out. From the last time we did this, the iterative work we needed to do was reducing the feature resolution into something the game could handle (very high res features mean a _lot_ of vertices needing to be handled by some code that isn't scaling very well). My understanding was that it wasn't particularly difficult to do that though.

**Comment by DanAlbert** [comment]
I'm running the import now to see what we've got, but the one obvious thing: this is missing the exclusion map. The land map defines land areas, and the sea map defines sea areas (duh), but we also need an exclusion map to mark land areas that are not usable: cities, forests, significantly hilly areas (not many of those in Normandy, of course).

The import is taking a very long time, btw, which means the shapefiles need to be simplified (I think the term was "dissolve"?). There's some discussion in discord here that might give you some ideas of how to tune things: https://discord.com/channels/595702951800995872/595706037449785364/1018576925943406652. This one in particular might be some useful clues for tricks? https://discord.com/channels/595702951800995872/595706037449785364/1016958484715155466

The importer has been running for about ten minutes and still hasn't finished _reading_ the data, so definitely need to reduce before this is viable. For reference, the phase that still hadn't completed after 10 minutes takes 0.03 seconds for the falklands data.

**Comment by Druss99** [comment]
Sorry for the delay, one of the files corrupted so I decided to restart entirely, these files sit around 3.5mb, should be small enough I hope.
[ExclusionAreav2.zip](https://github.com/dcs-liberation/dcs_liberation/files/11557907/ExclusionAreav2.zip)
[NormandyOceanv2.zip](https://github.com/dcs-liberation/dcs_liberation/files/11557908/NormandyOceanv2.zip)
[NormandyUsableLandv2.zip](https://github.com/dcs-liberation/dcs_liberation/files/11557909/NormandyUsableLandv2.zip)

**Comment by DanAlbert** [comment]
For reference, the Falklands land shapefile is 350KB. This one loads a good deal quicker though. I'm having other problem with it, but they're the kind that look like my problems rather than yours. I'll let you know if I find any issues.

**Comment by DanAlbert** [comment]
I'm not sure if this is a difference in the data available, a difference in the landscape itself, or a difference in how it was reduced. Here's what the exclusion map for a populated area (Rio Gallegos) looks like in the Falklands:

![image](https://github.com/dcs-liberation/dcs_liberation/assets/315852/b88de03b-af30-48fd-ae44-892d463bc527)

And here's some of the area around London:

![image](https://github.com/dcs-liberation/dcs_liberation/assets/315852/8ac4ada0-2115-4801-8bfe-70e062fedec1)

Or Amiens, a city of about the same size as Rio Gallegos:

![image](https://github.com/dcs-liberation/dcs_liberation/assets/315852/9221b613-eb37-439d-97c7-0c2618f113f4)


The latter is likely prohibitively expensive for Liberation. I haven't been able to test that yet because some part of this geometry is not even importable. I think that's actually a bug in the library I'm using? It doesn't appear to be my bug, and I don't think there's anything I can do to work around it. Hopefully it's something that won't be present in another reduction anyway?

**Comment by Druss99** [comment]
I will see what I can do, I probably need to reach back out to fin and see what he would suggest because with the data I have I do not see a way to condense it down in a manner that creates a useful end product, all of my current options would either destroy almost all the data or not remove enough data. Right now the exclusion zones consist of water, commercial districts, residential districts, retail districts, and industrial districts, removing commercial districts removes about 90% of the data and would allow ground units in downtown london but removing any of the other districts removes so little that it wouldn't make a  difference. There may be a way for me to combine features within a certain distance of each other to make the data less messy or possibly delete more chunks under a certain area threshold (I already deleted any bits smaller than 1,000 sq meters but I may be able to do an even larger reduction). Either way hopefully I will have an update in the coming days.

**Comment by Druss99** [comment]
I still haven't heard back from Fin so here's what I came up with:

I ended up pulling some additional data from OSM that allowed me to delete a lot of the smaller exclusions. I also forgot to buffer the exclusion zone to combine small areas and then buffer them back down to proper size. After doing both of those things we are down from 3mb to about 300kb which should be more than usable I hope. Again if there are any issues let me know, I am not a QGIS expert and this was quite a messy process, I think when Sinai releases I will approach things a little differently with the things I have learned and hopefully it won't require 4 or 5 versions like this one. 

Lastly you should be able to use the same ocean file from before, it has not changed.

[NormandyUsableLandv5.zip](https://github.com/dcs-liberation/dcs_liberation/files/11584782/NormandyUsableLandv5.zip)
[NormandyExclusionAreav5.zip](https://github.com/dcs-liberation/dcs_liberation/files/11584783/NormandyExclusionAreav5.zip)

**Comment by DanAlbert** [comment]
Does this look like what you expect? 
<img width="468" alt="image" src="https://github.com/dcs-liberation/dcs_liberation/assets/315852/a8e466bf-c562-4af1-ae9c-14730e1c1c63">

**Comment by Druss99** [comment]
That looks correct to me!

**Comment by DanAlbert** [comment]
Looking at https://forum.dcs.world/topic/324181-normandy-20-faq-updated/#:~:text=DCS%3A%20Normandy%202.0%20is%20significantly,%2C%20roads%2C%20fences%2C%20poles%2C, your map doesn't cover a large enough area?

**Comment by DanAlbert** [comment]
(it's probably good enough for any campaign, but I want to be sure that I'm not misunderstanding the map area)

**Comment by DanAlbert** [comment]
Thanks for confirming so quickly :) I'll go ahead and check this in and we can expand it later if desired.

> It is not a separate map from Normandy 1.0. Owners of the original DCS: Normandy 1944 map will receive a free update that enhances the whole area of the original map to the same high detail level as in DCS: Normandy 2.0. The free update will also include the new much larger DCS: Normandy 2.0 total map area and airfields but at a lower level of detail.

@Starfire13, am I understanding correctly that we do not need to distinguish between the two maps at all in Liberation? Players that don't own Normandy 2 can still fly from the new airfields, they'll just look like crap up close?

**Comment by Druss99** [comment]
No you are not. I do not own Normandy 2.0 so I went based on a forum post
for the coordinates of the map area.

**Comment by Starfire13** [comment]
> @Starfire13, am I understanding correctly that we do not need to distinguish between the two maps at all in Liberation? Players that don't own Normandy 2 can still fly from the new airfields, they'll just look like crap up close?

That is my understanding, yes.

**Comment by Starfire13** [comment]
From the FAQ

![image](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/0ade7cc9-5ec9-4503-9af8-09e1967301f9)

**Comment by Starfire13** [comment]
The missing world objects thing may potentially be a problem for map object strike targets, if they exist in one version and not the other.

**Comment by DanAlbert** [comment]
Aha, thanks. I don't fly WW2 so I'd ignored all the news about it, apparently including the FAQ :)

https://github.com/dcs-liberation/dcs_liberation/pull/2933

**Comment by Druss99** [comment]
Looking at it I definitely went too far on the right side and not far enough on the left, luckily I did not cut off any airfields or any terrain near any airfield so hopefully it works, I will be more careful in the future about the exact map boundaries.

**Comment by DanAlbert** [comment]
You don't need to be exact, FWIW. Going too far is fine (and preferable to not far enough). I think you're right though and this is probably good enough :)

Support for Normandy 2 is now merged into develop and https://github.com/dcs-liberation/dcs_liberation/pull/2934 cherry-picks it to 7.1. Thanks everyone for stepping up to help with the landmap! That's the hardest part by far.

**Comment by Starfire13** [comment]
I already have a campaign ready to go that uses the new airfields, so will test this out.

**Comment by Nosajthedevil** [comment]
> Looking at it I definitely went too far on the right side and not far enough on the left, luckily I did not cut off any airfields.


That's interesting, when I attempted the map I had the opposite problem. I noticed that you projected to utm 31 (east side of the map). I projected to utm 30 since that's how the original normandy was set up. I wonder if that's why they were off just a bit but in different directions. Doesn't matter if it works though.
