### ISSUE TITLE
AI airspeed

### ISSUE THREAD

**Issue by chrispy4819** [dcs-liberation/dcs_liberation#2835]
I'm currently in a liberation campaign in the A-4 skyhawk. I like to fly wingman to the AIs and practice my formation skills. Currently the way waypoints are generated has the AI A-4s flying faster than I can at max power and identical loadout. I will fly 375kts IAS, and when I check the F10 map, they're cruising at like 550kts IAS. They lose me in no time. The issue of AI outperforming humans in the same plane is an issue to DCS itself and is well-documented, but this does however shine a potential feature improvement.

It'd be nice to be able to tweak waypoint details like speed and altitude. In the same missions I'll notice AWACS planes almost stalling trying to maintain 120kts at altitude. I'm not sure what the answer is, but it seems like attention to AI airspeed is needed.

**Comment by DanAlbert** [comment]
There are no airspeeds in the missions we generate (aside from loiter speeds), we generate waypoints with TOTs for cross-flight mission coordination. There's no planned airspeed to allow players to adjust. ETAs can't feasibly be adjusted per waypoint because the ETAs of other waypoints are set to match, and all that happens during mission generation. The only thing that could be fine would turning those flight plans into custom flights that don't have any of the liberation behaviors, and if that's what you want the ME is already there.

Loiter speeds (the AWACS problem you mentioned) are moddable in the aircraft yaml. It's not likely that the chosen speed is too low. It's much more likely that the AI failed at flying well.

If you want to file a bug for the mis-estimated ETA (or mis-estimated cruise speed), there's a slim chance we can do something about that, but with the AI the answer is generally that they neither follow orders well nor self-direct well.

**Comment by chrispy4819** [comment]
Thanks for your response, Dan. While I understand that the user selects TOT and waypoints, and the rest is driven, I'm not seeing how speed is not baked in somewhere. If all the flights in the package were hot air balloons, surely the airspeeds on their INGRESS and JOIN waypoints would be less than 450kts. All the flights in a package have to be coordinated in their fixed waypoint times, but it's still an open solution without selecting either takeoff time or airspeed(s).

**Comment by Starfire13** [comment]
DCS calculates speed based on the waypoint timings provided. Liberation does not set speeds. That said, the AI is not great at sticking to the speeds (or altitude for that matter) that DCS itself generates.

**Comment by DanAlbert** [comment]
Open the mission editor and look at at the waypoint speed/tot works. You can't reliably fix a tot without unlocking the speed. That's what we do: we pick a TOT and DCS decides the speed to best meet that requirement.
