### ISSUE TITLE
Planned flights from previous turns still exist on subsequent turns in .miz

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2864]
### Affected versions

Development build

### Build information

DCS Liberation 7.0.0
Build 4949
Git revision 03671bbfb0622cb6346481bad582862c81598207

### Description

All flights planned on each turn of a campaign still exist in the .miz file generated from subsequent turns.

I have an example here over 3 turns, each of which only has a single friendly flight planned in Liberation. You can see how the flight planning accumulates per turn in the generated mission file.

Turn 1 Liberation
![Screenshot 2023-05-15 192628](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/7d39361f-850e-45cb-bcb2-d7757b7d3396)

Turn 1 Mission Editor
![Screenshot 2023-05-15 192643](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/609269fb-4724-4339-976c-5968dce07054)

Turn 2 Liberation
![Screenshot 2023-05-15 193021](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/6a61ac3c-7af3-41ae-97df-0b5984707423)

Turn 2 Mission Editor
![Screenshot 2023-05-15 193039](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/a4760ef3-83be-4f6b-ad1e-db84ec86e07d)

Turn 3 Liberation
![Screenshot 2023-05-15 193210](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/0591b4de-c52c-485c-a5cc-c1b1aba67bb8)

Turn 3 Mission Editor
![Screenshot 2023-05-15 193231](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/2394ff51-b7ba-42d1-9333-9aa20bd3274e)

### Save game and other files

[Vectron's Claw #4949 Test Turn 1.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11476430/Vectron.s.Claw.4949.Test.Turn.1.liberation.zip)

[Vectron's Claw #4949 Test Turn 2.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11476432/Vectron.s.Claw.4949.Test.Turn.2.liberation.zip)

[Vectron's Claw #4949 Test Turn 3.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11476433/Vectron.s.Claw.4949.Test.Turn.3.liberation.zip)

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/2851 is probably the culprit. I expect pydcs adds the units to the Country (which is very surprising behavior to me, I thought it was just a country identifier, not a container, but that does match the miz structure so I'd believe it), and since we carry that over each turn we keep those units.

The fix is simple enough: copy before adding to the miz.

**Comment by DanAlbert** [comment]
Yes, that's exactly it. Better than that even: take off -> abort -> take off also causes it.

**Comment by DanAlbert** [comment]
I'm not brave enough to untangle this on the pydcs end. I'll just revert the change that broke this on our end and live with the worse interface until I feel like doing that. https://github.com/pydcs/dcs/issues/314 tracks that.

> The fix is simple enough: copy before adding to the miz.

I didn't go this route because I'm not very confident that won't cause different problems, and it'd be exceptionally error prone since nothing would enforce that the right copy was the one used in the miz. I rejected a `Country.reset()` for similar reasons on the other end.
