### ISSUE TITLE
Rename generated kneeboard pages with 01_ prefix

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2879]
At the moment, generated kneeboard pages are named page00.png and page01.png. I suggest they be named 01_page00.png and 01_page01.png instead, in order to place them in front of all the various theatre and airfield maps to cut down on the amount of page flipping required to access them.

**Comment by DanAlbert** [comment]
afaict that doesn't work. https://github.com/dcs-liberation/dcs_liberation/pull/2987 does this (I tried `00_` and `01_`), but in both cases the first page was the A-10 HOTAS controls (which I think is a custom thing I've installed somewhere), followed by the Caucasus airfield charts. Going backward instead of forward, the generated kneeboards are past the DCS-generated flight plan pages.

[kneeboard_prefix.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11729645/kneeboard_prefix.liberation.zip) is my save and https://github.com/dcs-liberation/dcs_liberation/pull/2987 is the build. Does your suggestion not work, or did I misunderstand the intent?

**Comment by Starfire13** [comment]
Yes, a lot of the custom player-made pdfs and such have 00_ in front specifically to place them at the beginning. I have an ALIC table with 00_ in front so that always appears first. It works fine when I rename them manually. I will test it out.

**Comment by DanAlbert** [comment]
Does not work. See the PR for more discussion.
