### ISSUE TITLE
Apache longbow pylon error

### ISSUE THREAD

**Issue by chrispy4819** [dcs-liberation/dcs_liberation#2880]
### Affected versions

6.1.1

### Build information

DCS Liberation 6.1.1

### Description

I added a squad of apache longbows to a FOB. Upon pressing "take off" to generate the mission file, an error pops up saying "Plane AH-64D_BLK_II has no pylon 5." See image below for details.
![image](https://github.com/dcs-liberation/dcs_liberation/assets/132604185/18586a49-f940-4989-bdcb-0389e0f362ca)

### Save game and other files

[Arabia2005_A10CII.zip](https://github.com/dcs-liberation/dcs_liberation/files/11511911/Arabia2005_A10CII.zip)

**Comment by Starfire13** [comment]
I'm guessing this is because the new update adds the swappable ammo box and aux fuel tank for the Apache, and that means pylon assignments have changed. You won't be able to use Apaches until Liberation is updated to support that (and the radar hellfires, for that matter).

Temporary workaround is to plan your mission using another chopper type, and then manually switch them to Apaches in the mission editor after the .miz has been generated.

**Comment by DanAlbert** [comment]
Ow. I was really hoping to time the update with the F-15E. Am I understanding correctly that all campaigns with apaches in them are currently busted?

**Comment by Starfire13** [comment]
I'm at work so I can't verify, but will test it this evening. It does appear to be so though.

**Comment by DanAlbert** [comment]
Well that's quite terrible. I'll get this fixed in the dev build ASAP (doing it right now) and 7 is just going to ship with fewer features than I'd hoped.

**Comment by DanAlbert** [comment]
(FAQ channel updated)

**Comment by DanAlbert** [comment]
You _might_ be able to work around this by clearing the pylon 5 slot for your apache loadouts (the ones used by liberation at least), btw. I haven't tried.

**Comment by Starfire13** [comment]
Possibly, though my guess is the aux tank/ammo box is now an additional pylon. And you have to carry one or the other in that slot. Previously, the Apache was fitted with the aux tank by default so there was no need for that pylon.
