### ISSUE TITLE
AssertionError encountered when deleting a flight from a mission package

### ISSUE THREAD

**Issue by dwhysong** [dcs-liberation/dcs_liberation#2911]
### Affected versions

7.0.0

### Description

First mission, I'm having issues with multi-group packages not working together (SEAD flight is getting shot down by enemy fighters while there escorts are still taking off 100 miles away, etc.). Tried to re-order the flights as I noticed the takeoff times are in-order, but you can't do that. So I tried deleting the first 3 flights in the WALLAROO strike package, the idea being that I'd re-add them to make those planes takeoff later. The exception occurred after deleting the 3rd group from the package.

It would be a nice feature if the game could detect traffic issues and show a warning, or alternately have planes wait at the hold point until the package is fully ready. Time-on-target would be broken, but that's still probably better than what I'm seeing now.

### Save game and other files

![image](https://github.com/dcs-liberation/dcs_liberation/assets/38592617/b13f165a-d34f-48d8-bfa4-b14a7c3c97c7)
[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/11570705/liberation.log)
[falklands.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11570710/falklands.liberation.zip)

**Comment by Starfire13** [comment]
Liberation does not and cannot set take off times as there is no way to predict how long it takes to taxi and then be given take off permission. This varies significantly based on airfield, parking spot (which DCS also does not have control over, and congestion.

You also cannot get one flight to wait for another. Essentially, every flight in a package is doing their own thing. They are grouped up into packages to simplify synchronisation of TOTs. I actually usually place nearly all my flights into separate packages as I often want their TOTs to vary  (e.g. I might want a TARCAP flight to get on station 10 minutes to provide air cover before my strike flight arrives, rather than arrive at the same time).

**Comment by DanAlbert** [comment]
(There are DCS features that are _supposed_ to enable escort/follow behaviors, but they do not work correctly. See the DCS bug I filed years ago that is mentioned on our front page)

**Comment by DanAlbert** [comment]
Cannot reproduce the error. Loaded the save and was able to delete all four package members without issue.

**Comment by DanAlbert** [comment]
Tried one more thing based on the trace. It's got nothing to do with deleting those flights. It only has an error if you delete a flight that has a details window open at the same time. That dialog ought to be modal so that's impossible.

**Comment by dwhysong** [comment]
> You also cannot get one flight to wait for another. Essentially, every flight in a package is doing their own thing. They are grouped up into packages to simplify synchronisation of TOTs. I actually usually place nearly all my flights into separate packages as I often want their TOTs to vary (e.g. I might want a TARCAP flight to get on station 10 minutes to provide air cover before my strike flight arrives, rather than arrive at the same time).


I've done this in missions by defining a zone around the hold point, and having flights orbit there until the other groups are in the zone. I use a trigger condition to set a flag when all flights are present, and that flag is the stop condition for the orbit tasks.
