### ISSUE TITLE
Transport ship Samuel Chase available for WW2 AAA and Shorad

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2938]
### Affected versions

Development build

### Build information

DCS Liberation 8.0.0
Build 5071
Git revision 90bda9383d6fdf66c23a2b79cce697c631d4ea7e

### Description

The LS Samuel Chase can show up with AAA or SHORAD in WW2 scenarios.

![Screenshot 2023-06-01 152255](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/14e20687-bb23-4df4-bc5e-b70c83ebbfda)

![Screenshot 2023-06-01 153012](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/72103984-779d-42a9-85a8-062a18cc0950)

### Save game and other files

[Final Countdown #5071 Turn 3.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11621319/Final.Countdown.5071.Turn.3.liberation.zip)

**Comment by Starfire13** [comment]
Btw, the Samuel Chase is only available if  WW2LST is included under preset group. But regardless, it shouldn't be popping up on the buy list for AAA.

**Comment by DanAlbert** [comment]
I believe this is happening because the Samuel Chase yaml gives it the `Logistics` class. Maybe it's supposed to be `Boat`. Alternatively it's supposed to be `Logistics` and the group generator ought to be checking for land vs sea units. It's very simple to just change the unit class. No naval layouts use `Logistics` so they won't lose anything. The Higgens is `Boat`, but so are the Castle and Schnellboot, so it seems all types of "smaller than frigate, intended for combat or otherwise" are grouped as `Boat`.
