### ISSUE TITLE
AJS-37 Strike Mission on buildings drop a single bomb (M/71 High-Drag) every pass instead of low altitude carpet bombing

### ISSUE THREAD

**Issue by ObsceneNickname** [dcs-liberation/dcs_liberation#3020]
### Affected versions

7.1.0

### Description

As per the title, if you set a strike mission for AJS-37 on some enemy buildings, the deafult loadout is M/71 High-Drag. You would expect a single low-altitude drop of all the bombs on the target waypoint but instead the AJS drop a single chute bomb from medium altitude every pass. Of course with poor accuracy also. I don't know if the problem is dcs related or not

### Save game and other files

I don't think there's the need of a save file

**Comment by Starfire13** [comment]
The aircraft on strike missions will drop one bomb on each target waypoint (there is one per building). If you pick something like the GBU-38 that has guidance, the AI will drop one bomb on each target in one pass. If you use iron bombs, then they'll have to come in on multiple passes. The only aircraft that will do carpet bombing on strike missions are the heavy bombers like the B17 and the B52.

As for the default loadouts, I see those as just a suggestion. They work, but can be non-ideal depending on what you use em for. I use my own custom loadout presets for all aircraft rather than relying on the defaults.

**Comment by DanAlbert** [comment]
> I don't think there's the need of a save file

It says required right there in the form.

**Comment by ObsceneNickname** [comment]
> The aircraft on strike missions will drop one bomb on each target waypoint (there is one per building). If you pick something like the GBU-38 that has guidance, the AI will drop one bomb on each target in one pass. If you use iron bombs, then they'll have to come in on multiple passes. The only aircraft that will do carpet bombing on strike missions are the heavy bombers like the B17 and the B52.
> 
> As for the default loadouts, I see those as just a suggestion. They work, but can be non-ideal depending on what you use em for. I use my own custom loadout presets for all aircraft rather than relying on the defaults.

Yeah, that make sense, thanks for the reply. Maybe it's a better solution to use the BK-90 on buildings but even with those cluster bombs I get modest results.



> > I don't think there's the need of a save file
> 
> It says required right there in the form.

Sorry, didn't mean to be rude or something, I just wrote that rapidly. I'm a huge fan of liberation. I thought there was no need to add the save file since it's not an issue in a specific situation but rather a generic one. I will add a save file as soon as I can.

**Comment by Starfire13** [comment]
> Yeah, that make sense, thanks for the reply. Maybe it's a better solution to use the BK-90 on buildings but even with those cluster bombs I get modest results.

Generally, cluster bombs don't work well on buildings. It's not what they're designed for. You could try using a different aircraft for strike missions, perhaps.


> Sorry, didn't mean to be rude or something, I just wrote that rapidly. I'm a huge fan of liberation. I thought there was no need to add the save file since it's not an issue in a specific situation but rather a generic one. I will add a save file as soon as I can.

That's alright. But yes, we always want a save file so that we can replicate the issue, and test that any fix implemented works on the save provided. There have been times in the past where significant time had been wasted trying to replicate a reported issue because no save file was provided, and we want to avoid that.

**Comment by DanAlbert** [comment]
Please don't second guess us. If we say we need something, trust us. It wastes everyone's time to do otherwise. Developer time is extremely scarce. Spend it wisely.

**Comment by ObsceneNickname** [comment]
In this save file 2 viggen are tasked to strike mission on enemy buildings. Default loadout. There are 4 enemy fighter that could stop them if they are not shot down. Viggens drop a single chute bomb every pass from 6000 m.
[viggen-strike.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11834649/viggen-strike.liberation.zip)
I apologize again for the misunderstanding and thank everyone involved for the magnificent work done on liberation

**Comment by Starfire13** [comment]
Thanks for the file, but there's nothing to be done about this right now as this is just the way the DCS AI attacks with iron bombs. If you want them to hit their targets in a single pass, you'll have to pick some aircraft with GPS guided bombs. I usually use GBU-38s or GBU-31s.

If you want them to carpet bomb like the B52, that *may* be possible someday in the future when selectable mission profiles are implemented, but honestly most of those bombs would just miss anyway. It would be kinda pointless. The B52 makes up for the lack of accuracy somewhat with a massive bomb load. The Viggen does not have anywhere near that bomb load. If you want the AI to do single-pass Mach 0.95 hedgerow height bombing runs the way an actual Viggen would, that's not gonna happen. The DCS AI simply cannot fly the Viggen that way.

**Comment by DanAlbert** [comment]
Duplicate of #270
