### ISSUE TITLE
Squadrons for the old AI F-15E cannot use old unit name

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#3033]
### Affected versions

Development build

### Build information

DCS Liberation 9.0.0
Build 5258
Git revision 658a86dff57c411136adbcc4f8a242274c85f994

### Campaign name

Black Sea

### Blue faction

USA 2005 (default)

### Red faction

Russia 2010 (default)

### Modifications to default settings

None

### Description

The F-15E.yaml contains two variant names - "F-15E Strike Eagle" and "F-15E Strike Eagle (AI). However, the former (which was retained for compatbility reasons) no longer works. The new name does work, however. Campaigns that have not been changed to use the new variant name will have F-15E squadrons generated as another type of aircraft.

### Log file

Here's a zip from my log where I started a Black Sea campaign. The relevant line is, I think, "Not using squadron because USA 2005 cannot use F-15E Strike Eagle".

[Liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11859207/Liberation.zip)

**Comment by DanAlbert** [comment]
I'm going to revert that change. This aspect hadn't occurred to me. I'd prefer to fix this by expanding the `variant` field so that it can alter the display name independently of the "ID" (when it was first implemented, there was no reason for them to differ, but that's not really working now that there are AI-only variants of some aircraft).
