### ISSUE TITLE
Add/update <mod name> A4-E Skyhawk

### ISSUE THREAD

**Issue by 1951Hamstersgo** [dcs-liberation/dcs_liberation#3038]
* Mod name:
* Mod URL:
* Update or new mod?
WHY DO YOU KEEP LEAVING THE A4-E SKYHAWK OUT OF THE US AIRCRAFT 1965-1975 AIRCRAFT CHOICES IN FACTIONS?

**Comment by Starfire13** [comment]
Why should US Army factions include the Skyhawk, which was never used by the US Army?

**Comment by 1951Hamstersgo** [comment]
Sorry, my writing is not good.  The A4-E "should be included" in all the US years from 1965-1975. Please include the A4-E for all the years it was operational.

________________________________________

**Comment by Starfire13** [comment]
Those are US ARMY factions. The US Army did not fly the A4-E. The A-4E is already available in the 80s US Navy faction, though no one has created a 60s or 70s US Navy faction. If you prefer to throw historical accuracy out the window (and you are free to do so if you wish, of course), just add it to the US Army faction on your end. It is very easy to do this.

**Comment by 1951Hamstersgo** [comment]
In Liberation when I choose the years USA 1965-1975 I cannot find the A4-E Skyhawk other than 1973 Israel. ?

I just downloaded Retribution and they have it correct!  It's available 1965 through 1975!

I would prefer to use Liberation.  But, no A4-E Skyhawk.

________________________________________

**Comment by Starfire13** [comment]
The US Army does not use the Skyhawk.

**Comment by 1951Hamstersgo** [comment]
The US Navy and US Marines used the A4-E Skyhawk. On Carriers and on land.
https://en.wikipedia.org/wiki/Douglas_A-4_Skyhawk

A4-E was used in Vietnam War 1965-1973

1980's the A4-E Skyhawk was used by the Blue Angels.

1990's the A4-E Skyhawk was used at the Top Gun Training School in Nevada. Watch the first Top Gun Movie.

Retribution has it correct.  Liberation does not.

I guess you want me to use Retribution, and not Liberation.


________________________________________

**Comment by Starfire13** [comment]
Yes but those 2 factions are US Army factions, not US Navy or US Marine Corps factions. It says so right there in the faction file. If you want to use the A-4 in the army, as I said, just add it to the faction file. It's a single line copy and paste.

**Comment by 1951Hamstersgo** [comment]
I decided to now use Retribution.  They seem to be further along, and they have more campaigns to choose from. Plus, the A4-E Skyhawk is available for all of them.


________________________________________

**Comment by Starfire13** [comment]
Ok

**Comment by DanAlbert** [comment]
> Yes but those 2 factions are US Army factions, not US Navy or US Marine Corps factions.

I was surprised by this, but that's definitely what it says:

https://github.com/dcs-liberation/dcs_liberation/blob/develop/resources/factions/usa_1975.yaml

But I doubt the original author (it's very old, probably Khopa if not shdwp) probably mean "US armed forces" rather than "US army", since by that strict interpretation the US _army_ doesn't fly most of the rest of the aircraft in those factions either.

Perhaps the intent was strictly army + air force (but not USMC or USN), but the tomcat is in there :)

If someone wanted to send a PR fixing the descriptions to be "US armed forced" and add the aircraft, I'd merge that (mods are something I very specifically do not spend my time on, because anyone can do mods, but most of the other bugs/FRs that are open can only be done by a developer, so those get my priority).

@1951Hamstersgo, FWIW, your posts read as rather combative to me. ALL CAPS means yelling, and it seems to imply Liberation was doing this maliciously rather than just being the honest oversight that it appears to be. I hope that wasn't your intent, but that's how it appears.  There's a feature request to be had here (possibly "add more combined US armed forces factions"?), but "creative differences" does not mean "wrong".

**Comment by 1951Hamstersgo** [comment]
Sounds like you have a personal problems.  Take time off?  Need a vacation?  Drink?  Meds?

I am using Retribution right now.  It works great. No problems.  US Forces have the A4-E Skyhawk for "every year" in service.

I am a happy camper.


________________________________________

**Comment by DanAlbert** [comment]
Personal attacks are completely unacceptable.
