### ISSUE TITLE
waypoint drag and drop not redrawing correctly

### ISSUE THREAD

**Issue by habibivoodoo** [dcs-liberation/dcs_liberation#3059]
### Affected versions

Development build

### Build information

DCS Liberation 9.0.0
Build 5290
Git revision 895f31d3d3e072f662c740b308eea3ea3234c61a

### Description

Waypoint paths dont function properly when dragging and dropping on the map/setup

### Save game and other files (save game required, bugs without saves will be closed)

[PG 117th Lib.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11890508/PG.117th.Lib.liberation.zip)

**Comment by DanAlbert** [comment]
In the other bug (you didn't need to file a new one, it's fine to attach saves to existing bugs) you said:

> errors appear in mission planner/setup for liberation.

That's really the most interesting part. What error?

**Comment by Starfire13** [comment]
Someone else (Kerbo) posted a gif of the bug on discord: https://discord.com/channels/595702951800995872/595706079459934208/1123335530097156158

**Comment by DanAlbert** [comment]
But what is the error message?

**Comment by habibivoodoo** [comment]
I guess thats the wrong verbiage. Error messages dont appear but as Starfire said, you can see the pathing of the waypoints is not correct when dragged and dropped.

**Comment by DanAlbert** [comment]
Oh. I thought you meant an error message, which would have been a very different thing. I had tried doing this myself without the save file and did not see any error message, which is why it got closed (this is why we ask for a save game, it's too damn hard to figure out what you're describing otherwise).

**Comment by DanAlbert** [comment]
Is this actually new? The code that handles this hasn't changed in quite some time (aside from the first time just a few minutes ago when I made some minor tweaks to accommodate some tests). If this actually only cropped up in the preview builds today like the comment in discord seems to imply, that's quite surprising. It'd also be quite surprising if this has been broken for long though, since I imagine people.donthisnrather frequently...

**Comment by Starfire13** [comment]
I can't confirm that I am also seeing it on my end till I get home after work. But I was not encountering it on yesterday's builds at the very least. But so far, two users have reported encountering this today, and as far as I'm aware, no one has reported this specific bug before today.

**Comment by DanAlbert** [comment]
I was able to repro, but I haven't had a chance to go digging through older builds to see if it's new or not. If this is a regression from 8.0.0 I'd say it's a blocker. Both answers would surprise me though.

**Comment by DanAlbert** [comment]
> But I was not encountering it on yesterday's builds at the very least.

I overlooked the load bearing sentence. Okay. That's damned odd. Will definitely not ship until it's resolved then.

**Comment by DanAlbert** [comment]
Amusingly it was the fix for https://github.com/dcs-liberation/dcs_liberation/issues/3037. Apparently that bogus double takeoff waypoint was actually relied on in the UI...

**Comment by DanAlbert** [comment]
Easy fix, fortunately: https://github.com/dcs-liberation/dcs_liberation/pull/3060. Should be in the preview builds in 30 minutes or so.

**Comment by DanAlbert** [comment]
Merged, will be in the next build.

Sorry for the break and for the confusion in triage, and especially thanks for the quick reports! Would have been quite bad to have shipped with this bug tomorrow :)
