### ISSUE TITLE
Strike Targets Not Showing Dead On Next Turn Or Registering in State.JSON at all

### ISSUE THREAD

**Issue by habibivoodoo** [dcs-liberation/dcs_liberation#3073]
### Affected versions

Development build

### Build information

8.1 new release

### Campaign name

Operation Peace Spring

### Blue faction

Blefor Modern

### Red faction

Iraq 1991

### Description

attempted to strike target EEL just east of Incirlik. Visually confirmed fuel tanks were being destroyed and the model was changing to the rubble model, and scoreboard was showing shacks on ground targets in game. After accepting results, shows 0 structures shacked and they are all still on the map alive. 

### Log file

[8.1 syria.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11997497/8.1.syria.liberation.zip)
[8.1 syria.liberation after attempt 2.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11997511/8.1.syria.liberation.after.attempt.2.liberation.zip)

[state.zip](https://github.com/dcs-liberation/dcs_liberation/files/11997505/state.zip)

**Comment by Starfire13** [comment]
I don't think the two saves provided are the right ones because neither save has an attack tasked against EEL. I generated the same campaign and created my own flight to attack the same resource site (named OWL in my campaign, as you can see in my screenshot below), and ran it twice; one time using Mk-84s (which is what Coyote said he used on the Discord), and a second time using JDAMs. On both attempts, destroyed fuel tanks were picked up by Liberation, and the tanks stayed dead on the next turn. Unless Coyote can tell us how to replicate this, my feeling is this is user error and not a bug.

I have told Coyote I am closing this for now unless he can provide a way to replicate the problem.

![Screenshot 2023-07-10 215322](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/f3b6a0a8-a738-4b2f-ba96-4e330c6b4362)

![Screenshot 2023-07-10 215428](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/6659320a-10a3-42df-9153-b4a87daca696)

![Screenshot 2023-07-10 215519](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/fcf4d63f-e659-47aa-8a9e-57d18fb25f9c)

**Comment by habibivoodoo** [comment]
[8.1 Syria Strike EEL.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/12005829/8.1.Syria.Strike.EEL.liberation.zip)

here is the save with the strike EEL selected as you asked for. my squadron is about to run this mission for a THIRD time. I watched my 2000lb gbus hit the objective tanks both times and Liberation showed 0 scenery objects destroyed. Not sure how to prove what im seeing on my end is accurate.

**Comment by habibivoodoo** [comment]
![Screen_230710_123445](https://github.com/dcs-liberation/dcs_liberation/assets/116920043/d263a19f-2a4b-4d52-a968-45a900a712e7)
loadout taken for strike

**Comment by habibivoodoo** [comment]
![Screen_230710_130547](https://github.com/dcs-liberation/dcs_liberation/assets/116920043/fc037a89-eb3d-49a3-bf1a-08d7e2eb4965)
![Screen_230710_130552](https://github.com/dcs-liberation/dcs_liberation/assets/116920043/ff78c673-33aa-434a-9b79-18b9a4bf1619)
![Screen_230710_130554](https://github.com/dcs-liberation/dcs_liberation/assets/116920043/91d1fb6f-bb57-464b-859c-e99e7f9c9b6a)

**Comment by habibivoodoo** [comment]
![image](https://github.com/dcs-liberation/dcs_liberation/assets/116920043/7bf954c7-f156-45c4-a799-52d753e7d1b3)

are these not considered scenery targets?

**Comment by DanAlbert** [comment]
We need the state.json and the liberation_nextturn.miz that match that save game.

**Comment by Starfire13** [comment]
@habibivoodoo 

Try running this:

[8.1.Syria.Strike.EEL2.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/12008963/8.1.Syria.Strike.EEL2.liberation.zip)

Don't edit it. Just leave it to run on its own. Let me know what the results are.

**Comment by habibivoodoo** [comment]
> We need the state.json and the liberation_nextturn.miz that match that save game.

[state.zip](https://github.com/dcs-liberation/dcs_liberation/files/12009068/state.zip)
[liberation_nextturn.zip](https://github.com/dcs-liberation/dcs_liberation/files/12009083/liberation_nextturn.zip)

**Comment by Starfire13** [comment]
I am still getting kills registered using the new save file provided. I don't think there is a bug here.

![Screenshot 2023-07-11 093045](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/da2d5fbf-6865-44cc-9621-e8edfaf42831)

**Comment by habibivoodoo** [comment]
Im suspecting the issue is related to me running this mission on a dedicated server

**Comment by DanAlbert** [comment]
The common cause of this is accidentally copying the wrong miz to the server, or applying the wrong state.json file. There isn't really any way liberation can help you with that.

**Comment by Starfire13** [comment]
My understanding is that Coyote is running both the client and the server on the same machine, and so there is no file transfer transfer needed. He says the state.json is correct when running just the regular dcs client, but not when he is running both the server and the client on the same machine. I have no idea why that would be. So far, nobody else has reported this issue.

**Comment by DanAlbert** [comment]
I used to do that and had no problems.

**Comment by DanAlbert** [comment]
If you want to be sure your state.json is being written, delete it before launching the mission. If the state.json isn't being written, follow the dedicated server instructions on the wiki (you must fix MissionScripting.lua every time DCS updates). If it is being written and those events just aren't being recorded (but others are), that's a DCS problem (scripting behavior difference between dedicated server and game) and there's nothing we can do about it.

**Comment by habibivoodoo** [comment]
I have followed the steps on the wiki prior to all this and confirmed the missionscripting.lua is proper for lib. It tracks ALL the other kills and stats. It just seems to either register scenery objects as ground objects during the mission, or nothing at all. On one test, the AI strike flight hit their target, and somehow every other scenery object on the entire map died simultaneously. something truly bizarre and new is occuring here.

**Comment by habibivoodoo** [comment]
I have tried sanitizing my PC, DCS folder, and DCS Server folder, saved games folders, etc of all traces of liberation, and started fresh with 8.1. Same results. For whatever reason when I run a lib mission on dedicated server, the state.json does not come out properly as it should running lib on my local machine. I have no idea how to figure out where the disconnect/mistranslation is occuring or why

**Comment by habibivoodoo** [comment]
I will also note, I was not having these issues prior to 8.0-8.1 i.e. prior to the strike eagles release/impending release. I remember when the strike target issue was resolved about a month ago, which I believe I even reported, so I have been actively running Libs since those updates with no issue until 8.1

**Comment by habibivoodoo** [comment]
[state.zip](https://github.com/dcs-liberation/dcs_liberation/files/12017061/state.zip)
[8.1 test dedicated.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/12017062/8.1.test.dedicated.liberation.zip)
![Screen_230711_094706](https://github.com/dcs-liberation/dcs_liberation/assets/116920043/a73792dc-d6e4-458e-885d-ef5318853b4f)
![Screen_230711_095322](https://github.com/dcs-liberation/dcs_liberation/assets/116920043/bb1d8ee7-cf3d-4832-94f7-8161f5b33acf)
![Screen_230711_095334](https://github.com/dcs-liberation/dcs_liberation/assets/116920043/fc74ba7f-ec84-4f59-813c-8efec1a99701)


still doesnt work. This bug should be re-opened. Regardless of whether or not this is run on dedicated server or local. this is a liberation issue

**Comment by habibivoodoo** [comment]
YOU might have a great computer and running on local is no performance hit for you. But it is for me and many others which is why we use dedicated server. Multithreading is not some magical fix for everyone.

**Comment by DanAlbert** [comment]
> this is a liberation issue

A behavior difference between the dedicated server and the client is a DCS issue. It's not in our power to fix.

**Comment by habibivoodoo** [comment]
The dcs dedicated server simply runs the mission the same as if I ran it on my "client". They are both on the same machine even. Following the 'WIKI' about liberation and dedicated server steps to the letter. 

Its in your power to investigate instead of ignore. You guys can load up a dedicated server and test it for yourself since youre providing documentation on how to use liberation with dedicated servers. At least research it. Why am I doing all the work and being passed off?

**Comment by DanAlbert** [comment]
Because you've quite thoroughly proven there's nothing we can do. Starfire _did_ investigate. You've convincingly shown us that there is a behavior difference in DCS where the dedicated server is not handling these triggers correctly. I cannot fix DCS. It doesn't matter how badly I'd like to help you (I would), I can't.

> You guys can load up a dedicated server and test it for yourself

What would that accomplish? I believe you.

**Comment by habibivoodoo** [comment]
Well im just guessing with my limited knowledge of coding and such that somewhere in the last month of updates, something got altered. Those triggers used to work in dedicated server properly. When exactly I'm trying to pinpoint. I believe it was right after we got the strike target fix, and before the f15e implementation.

**Comment by DanAlbert** [comment]
I _have_ looked at the code. We do not have a "is dedicated server" check anywhere in Liberation. They are identical missions with identical interpretation on our end, the only difference is that DCS is not handling that trigger correctly. I cannot fix the dedicated server because I don't have access to that code.

It breaking around that time is not unlikely because DCS updates also happened around that time.

**Comment by habibivoodoo** [comment]
I have filed a report with ED as well. I am sure they won't even bother to investigate it. They will probably say it's a Liberation issue lol.

**Comment by DanAlbert** [comment]
The code in question, for the record:

* [Trigger creation](https://github.com/dcs-liberation/dcs_liberation/blob/adabb617f39ca19410e5e39540481470a23f04a6/game/missiongenerator/tgogenerator.py#L290)
* [Initialization of that field](https://github.com/dcs-liberation/dcs_liberation/blob/adabb617f39ca19410e5e39540481470a23f04a6/resources/plugins/base/dcs_liberation.lua#L13)
* [The interpretation of the state.json](https://github.com/dcs-liberation/dcs_liberation/blob/adabb617f39ca19410e5e39540481470a23f04a6/game/debriefing.py#L124-L142)
* [The commit that previously fixed this behavior](https://github.com/dcs-liberation/dcs_liberation/commit/c74b603d81ea8c124fd1c4c6990171caae2409ff)

@zhexu14 in case they see something the rest of us don't (they're the expert on this part of Liberation now), but everything above looks right to me, Starfire has proven that this works in a non-server environment, and Liberation itself has no awareness of how the miz is being run so we _can't_ alter behavior based on dedicated/self host.

> I have filed a report with ED as well. I am sure they won't even bother to investigate it. They will probably say it's a Liberation issue lol.

Link that here?

**Comment by habibivoodoo** [comment]
https://discord.com/channels/542985647502393346/1128379628768206881

**Comment by habibivoodoo** [comment]
As predicted they say it's a Liberation end issue lol

**Comment by DanAlbert** [comment]
Not really what they said, and they weren't really given a bug report, so they don't have a lot to go on.

**Comment by zhexu14** [comment]
I'm wondering if the reason the deaths are not being tracked is that the strike is hitting the wrong buildings?

The way the mission is set up is that only a small subset of the fuel tanks are actually tracked. The "special" buildings are marked in the attached DCS ME screenshot by the nice looking, DCS ME crosses and labelled "Botas Oil Tank X".

From the screenshots provided by @habibivoodoo, I think I've narrowed down the vantage points and from there, I've tried to guess which buildings were actually hit -- these are shown by the hand-drawn X's. Unfortunately, it seems that by sheer luck there is no overlap between the hit buildings and the ones that are tracked.

![screenshot](https://github.com/dcs-liberation/dcs_liberation/assets/64713351/0e1f44ec-7d14-446c-bcc1-fb0f95028983)

**Comment by Starfire13** [comment]
This was what I had suspected as well after seeing those screenshots, but @habibivoodoo insisted that the correct buildings were being hit on subsequent tests and so I'm taking their word for it. I have no way to verify, but I'm inclined to believe this is the case since JDAMs were used for some of the tests. I think it's unlikely that multiple JDAMs would all miss their targets. JDAMs are typically quite accurate.

**Comment by habibivoodoo** [comment]
I promise it's not accuracy. I have videos and more screenshots of the specific way pointed targets being destroyed with 0 effect in results. We aren't missing this many times.

**Comment by habibivoodoo** [comment]
I'm not sure what I'm not providing in my log files. I enabled debug logging on local and dedicated server and they said it's not enabled. Can anyone explain how to do that in case I'm doing it wrong

**Comment by DanAlbert** [comment]
I don't know how to enable debug logging either. Have you googled it? There are still Lua errors in your log files that have nothing to do with liberation as far as I can tell.

**Comment by habibivoodoo** [comment]
I have googled it yes. What errors are you seeing and how would they correlate with this issue?

**Comment by DanAlbert** [comment]
Can you not read the logs?

**Comment by habibivoodoo** [comment]
Yes sir, I can read. I dont know what errors YOU are seeing that are considered errors. My game runs fine.

**Comment by habibivoodoo** [comment]
and if the errors in question have nothing to do with liberation or this issue, why are they even being focused on?

**Comment by DanAlbert** [comment]
I had pointed them out to you in the discord thread. I can't open the logs on my phone so can't copy them here right now.

Right now those lua errors are the best explanation for the problem. It seems extremely unlikely (if that script breaking is breaking this part of kill tracking, it should also break _every_ part of kill tracking), but I have no other ideas. It's also surprising to me that our skynet has been broken for who knows how long and no one has reported it.

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/3078 fixes the skynet lua error. I'm still pretty skeptical that that's the problem (even with that fixed, I see lua errors from built in things like the F-15 modules, so we're not the only offender here), but it's worth a shot (and was worth fixing either way).

**Comment by DanAlbert** [comment]
I cleared up some space so I could install the dedicated server, and [this mission](https://github.com/dcs-liberation/dcs_liberation/issues/3073#issuecomment-1631168886) (reduced somewhat so I don't have to wait 40 minutes since DS can't speed up time) worked just fine for me. Bombs were dropped, kills were recorded.

I just loaded the one from https://github.com/dcs-liberation/dcs_liberation/issues/3073#issuecomment-1629576947 to confirm. No changes to the save game other than turning the players into AI. Will take an hour to get results.

We can definitely rule out the skynet error, btw. There was no error in the save from the second comment.

**Comment by habibivoodoo** [comment]
Well this is absolutely bonkers then. So for whatever reason, whenever I run this mission it doesn't work but for everyone else it does? Fuck me. What should I try and do then?

**Comment by habibivoodoo** [comment]
Could it be something as stupid as liberation preferences not pointed to the correct place? I've tried pointing liberation to both my dedicated server folders and my local DCS folders. Neither fixed the issue. Apart from fully reinstalling DCS idk what to do here.

**Comment by habibivoodoo** [comment]
And also can you share your settings you have for your DCS dedicated server? Is it resume on load/with clients/manually, etc? 

I am wondering if for whatever reason, liberation thinks the turn is ending when I load the mission onto the server.

**Comment by DanAlbert** [comment]
An hour and fifteen minutes later, two AI flights bingo'd out and the third missed the target because it did a level CCRP drop with iron bombs.

**Comment by habibivoodoo** [comment]
> An hour and fifteen minutes later, two AI flights bingo'd out and the third missed the target because it did a level CCRP drop with iron bombs.

That's fkn rough. This is part of the pain I've been going through as well trying to debug this lol. Welcome to the circle of hell

**Comment by habibivoodoo** [comment]
Also why I changed their loadouts to 2000lb jdams with pens

**Comment by DanAlbert** [comment]
Modified the miz to move the AI closer, gave them JDAMs (and made them F-16s because the F-15E S4+ AI can't handle LGBs yet). Worked fine.

* [liberation_nextturn.miz.txt](https://github.com/dcs-liberation/dcs_liberation/files/12035563/liberation_nextturn.miz.txt)
* [state.json.txt](https://github.com/dcs-liberation/dcs_liberation/files/12035567/state.json.txt)

The only explanations I have are that this is either an environment issue on your end or user error, neither of which are in our power to fix.

> And also can you share your settings you have for your DCS dedicated server?

1. Installed the server
2. Patched MissionScripting.lua
3. Launched server
4. Launched the web GUI
5. Changed the server name (just so I could find it)
6. Added the mission
7. Pushed start
8. Connected client
9. Took spectator slot.
10. Wait for booms
11. Look at state.json

> liberation thinks the turn is ending when I load the mission onto the server.

That's not a thing. state.json continues updating while the mission is running.

**Comment by habibivoodoo** [comment]
An environment issue such as what? Fuuuuck this is a waste of time lol. I spent all this time testing to get "it's user error"?

**Comment by habibivoodoo** [comment]
I'd love to hear an example of what user error I could be doing to cause this because I've shown with evidence multiple times that I'm doing the exact same steps you are. If it's an "environment issue" can you give me some clues as to what those might be and how to fix them?

**Comment by habibivoodoo** [comment]
So damn quick to hit that "Closed" button on the issue lmfao. Glad you got it working for you dude. Great help.

**Comment by habibivoodoo** [comment]
So just remember folks, as long as the devs don't have bugs, they don't exist.

**Comment by DanAlbert** [comment]
I only said it was a possibility. I'm out of guesses. It's closed because there's nothing more we can do here.

Please remember that this project is maintained with extremely limited volunteer time. There are hundreds of other bugs open that also need our attention. Bugs that can't be reproduced get closed. It doesn't mean we don't believe you, it just means we won't be doing more unless something changes. If you continue investigating and come up with something else we should try, it'll get reopened. If you don't want to do that, we understand. Like I said, we're all volunteers here, and that includes you.
