### ISSUE TITLE
Support for F-15E (Suite 4+) Steerpoints

### ISSUE THREAD

**Issue by oliverw** [dcs-liberation/dcs_liberation#3088]
The Razbam F-15E (Suite 4+) supports "special" steerpoints like 

- Initial point
- Target

as explained [here by Notso](https://www.youtube.com/watch?v=ChCVd2JvwAE&list=PLwKSNTU2afuA_G07xII__IsKRTgyenQaN&index=5). These steerpoint variants are not just of cosmetic nature but have actual use in the jet as outlined by [Notso in this Video](https://youtu.be/2s2o3qNyKiM?list=PLwKSNTU2afuA_G07xII__IsKRTgyenQaN&t=606).

It would be nice to have this in Liberation.

**Comment by DanAlbert** [comment]
This is section 8.18.5 in the manual:

> Set up the flight plan as you normally would, placing waypoints. Make sure that the aircraft is set to “Client” or “Player” for the whole operation to work.
>
> To set the desired waypoints as Target Points, add #T next to their NAME:

> More than one target point can be set up using this method. It is worth noting that the waypoint immediately before the target point will show up as Ingress Point on the TSD.
>
> To add any offset or aim points, you will need to open the NAVIGATION TARGET FIX POINTS submenu

**Comment by oliverw** [comment]
So, what you are suggesting is to load `liberation_nextturn` in the editor and fix the steer points prior to flying the mission?

**Comment by DanAlbert** [comment]
I'm not suggesting anything. Those are notes for whoever implements this.

**Comment by oliverw** [comment]
> I'm not suggesting anything. Those are notes for whoever implements this.

Okay got it, won't bother you again.

**Comment by DanAlbert** [comment]
Not sure why this was closed. This still needs to be done.

**Comment by DanAlbert** [comment]
Another interesting bit from the manual:

> Only Target Points are designated by the system - even if Offset Point (1.01, 1.02 etc) is selected, the main Target Point will be used by the CC to compute delivery data.

So it sounds offset points definitely aren't meant to be used for marking multiple targets in a single area.

Neither the manual nor the videos above (the first one wasn't very helpful at all, but the second one does a good job of showing _why_ target points are useful) explain was target offset points or aim points are actually for, so I think those will just go unimplemented in Liberation until that's explained. If anyone can tell us what target offset points or aim points are for, that'd be helpful (file a new FR if you do, this one is complete).

**Comment by DanAlbert** [comment]
I found the answers for aim points and offset points by accident: https://youtu.be/ycthNP-FLfI

tl;dw they're for marking landmarks used for PVU in missions without GPS. It isn't something we can feasibly do because we have no way of knowing where landmarks are. The only thing I can think of would be to preset a _lot_ of landmarks per map. It'd take pretty significant effort to do so, and would raise the already very high cost of adding support for new maps. I think for that case yes, the answer is that if you choose to play a campaign where your EGI doesn't work, you'll need to go into the DCS ME and add those points yourself.

It would be counterproductive for us to add those planning features to liberation itself because there's no guarantee that the DCS map and our map match (and for most landmarks like buildings they certainly do not), and a wrong landmark is far worse than the pain of opening this mission editor.
