### ISSUE TITLE
Bug in TOT offset for CAS flights

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#3107]
### Affected versions

Development build

### Build information

DCS Liberation 9.0.0
Build 5365
Git revision e1dba91b253ea63965a16fe9a34a2a6e9b0aac49

### Description

I have a package with 3 flights (it's the last one on the list in the save file).

First flight is a SEAD escort flight with a start time of 12:00:00

Second flight is a CAS flight with a start time of 12:03:09

There is no TOT offset on this flight, so this start time offset was automatically added by Liberation (unsure of reason why). Incidentally, if I click the "Ahead of Package" checkbox and add 3 minutes to it to try to get it to take off earlier, it actually delays the flight.

Third flight is a CAS flight with a start time of 12:08:09. I've added +5 min to the TOT offset. However, looking at the waypoint timings in both the Liberation UI and in the mission editor, the ingress waypoint timing for both CAS flights is identical.

### Save game and other files (save game required, bugs without saves will be closed)

[Bright Star #5365 Turn 1.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/12138543/Bright.Star.5365.Turn.1.liberation.zip)

**Comment by DanAlbert** [comment]
> First flight is a SEAD escort flight with a start time of 12:00:00
>
> Second flight is a CAS flight with a start time of 12:03:09
>
> There is no TOT offset on this flight, so this start time offset was automatically added by Liberation (unsure of reason why).

SEAD flights have a hold point. Those were never added for CAS because there's far less need to coordinate with the TARCAP (which is by default the only other mission type that'll be in a CAS package) than there is for the strike-type flights that are more or less always going into enemy territory.

Since the SEAD flight will take longer to get to its IP, it has to start first.

> Incidentally, if I click the "Ahead of Package" checkbox and add 3 minutes to it to try to get it to take off earlier, it actually delays the flight.

But if you add three minutes and _then_ check the box, it behaves correctly. So there's one bug :)

> Third flight is a CAS flight with a start time of 12:08:09. I've added +5 min to the TOT offset. However, looking at the waypoint timings in both the Liberation UI and in the mission editor, the ingress waypoint timing for both CAS flights is identical.

Sounds like maybe TOT offsets for CAS were only half implemented. I'll have a look.

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/3108 fixes those two and a bonus bug.
