### ISSUE TITLE
"First input geometry is empty" error upon clicking Begin Campaign in Operation Vectron's Claw

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#3156]
### Affected versions

Development build

### Build information

DCS Liberation 9.0.0
Build 5470
Git revision eebb1723335cc7353da60bbc4cf819b32f6437d0

### Campaign name

Operation Vectron's Claw

### Blue faction

USA 2005

### Red faction

Russia 2010

### Modifications to default settings

All settings on default

### Description

Starting a new Vectron's Claw campaign and clicking "Begin Campaign" causes this error. If you disable automatic package planning, the error does not occur.

![Screenshot 2023-08-20 115723](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/5d697580-e4ce-4829-bea2-ae47d36aab77)

### Log file

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/12387024/liberation.log)

**Comment by DanAlbert** [comment]
The problem here actually isn't the hold point, it's that the IP is being placed bizarrely and that's messing up everything else

<img width="550" alt="image" src="https://github.com/dcs-liberation/dcs_liberation/assets/315852/c01f03ee-4d5e-42af-b99a-549342da1408">

The thing way in the south is the IP. I don't know why.

**Comment by Starfire13** [comment]
What's that giant dark grey circle? It looks like the auto planner is trying to place the IP just outside that circle.

**Comment by DanAlbert** [comment]
Every grey circle is an excluded area. The giant one that's around everything else is supposed to be a way to make sure that waypoints don't get placed too far away. I think the origin point is just so damn far from the target that that arbitrarily large circle is too small.

That does seem to be the case, because if I increase it from 1000 km to 2000 km, the mission can generate again. Amusingly it's actually so damn close to not being a problem that had that off-map spawn been just a bit closer to the main part of the theater it wouldn't have been a problem.
