### ISSUE TITLE
Mission Crashes MP

### ISSUE THREAD

**Issue by Dampenstein** [dcs-liberation/dcs_liberation#33]
Hey!

I am trying to run DCS Liberation Campaign with my group BorderZone. We are having trouble to host it with more then 3 people on the server. Even with 3 persons it lags alot for the host.

We tried to run it with 7-8 people the game just freezes and crashes. Last time we tried it I fired an FOX 3 when it hit the plane i was aiming for the game just froze for me and everybody else then crashed. 

is there any way to host it on a dedicated server? I dont know what causing it to crash but we tried multiple PC's and always the same thing. 

- Dampe BZ

**Comment by MedievalBunny** [comment]
The mission files can be quite large and complex. Do you have culling enabled in settings?

**Comment by Dampenstein** [comment]
Nope culling is not enabled. What does culling do?

**Comment by MedievalBunny** [comment]
Culling can reduce the size and complexity of a mission by parametrically removing units that are more than the specified distance away. That way your computer isn't wasting resources simulating tanks and aircraft that are 300 miles away from where you're flying. I typically set it to 200km and it seems to run well. I also uncheck "Generate infantry squads along vehicles" since infantry usually don't mean much to a jet fighter. 

Both options can be found in the settings window.

**Comment by Dampenstein** [comment]
Thats awesome, ill try that on our next mission day!

**Comment by DanAlbert** [comment]
Not enough info, and haven't heard if anyone else encountering this in months. Assuming fixed.
