### ISSUE TITLE
BEGIN CAMPAIGN reported an error

### ISSUE THREAD

**Issue by Pil-Nick** [dcs-liberation/dcs_liberation#3347]
### Affected versions

10.0.0

### Description

After version 10.0.0, when I configure and click BEGIN CAMPAIGN, I always get the error message shown below. Even if I am using the first Caucasus mission and all configurations are the default configuration, this error message will still appear.

![report](https://github.com/dcs-liberation/dcs_liberation/assets/79027768/8b96cbfa-f336-4389-9c8a-ff4f5abd2567)

### Save game and other files (save game required, bugs without saves will be closed)

[test.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/14478516/test.liberation.zip)

**Comment by zhexu14** [comment]
@Pil-Nick , do you by any chance have non-ASCII characters (e.g. Chinese characters) in any of the following paths:
- The directory where you installed DCS, 
- Your "Saved Games" directory or
- The directory where you installed Liberation?

Having non-ASCII characters in these paths can be problematic.

**Comment by Pil-Nick** [comment]
No, here are my three paths:
G:\liberation
G:\SteamLibrary\steamapps\common\DCSWorld
C:\Users\PilNick\Saved Games\DCS

**Comment by zhexu14** [comment]
Do you have any mods or custom aircraft payloads that have non-ASCII characters? Basically the error is happening because Liberation is trying to load some .lua files that define payloads that units can have but can't understand a character. The places it looks are:

<DCS install dir>\MissionEditor\data\scripts\UnitPayloads
<DCS install dir>\CoreMods\aircraft\<aircraft name>\UnitPayloads
<Saved games dir>\MissionEditor\UnitPayloads
<Saved games dir>\Mods\aircraft\<aircraft name>\UnitPayloads

**Comment by Pil-Nick** [comment]
OK, problem solved. It should be my C:\Users\#\Saved Games\DCS. There are many residual files in it. I deleted it and restarted DCS to generate this folder, and then restored the backup settings file. Now dcs_Liberation can be used normally.
