### ISSUE TITLE
Application crashes when starting an AI-only mission

### ISSUE THREAD

**Issue by NiJeTi** [dcs-liberation/dcs_liberation#3355]
### Affected versions

10.0.0

### Build information

DCS Liberation 10.0.0

### Description

If no player slots available and you decide to start an AI-only mission to advance in campaign the app loads CPU and freezes.

### Save game and other files (save game required, bugs without saves will be closed)

[Cyprus Liberation.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/14547235/Cyprus.Liberation.liberation.zip)

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/14547236/liberation.log)

**Comment by Starfire13** [comment]
It's because you have turned on fast forward but neither side has any aircraft that enters hostile airspace or encounters hostile aircraft. So, first contact (which ends fast forward) never occurs. Liberation is basically fast forwarding forever. Just turn fast forward off. However, there is really no point running this mission because nothing is going to happen. You'll just have a few BARCAP flights circling your territory and the enemy has a few BARCAP flights circling his. The reason is there are no frontlines, and no control points being threatened. There is essentially no conflict. That will change once you capture (or cheat capture) one of the control points on Cyprus.

**Comment by NiJeTi** [comment]
Thanks for clarification!
