### ISSUE TITLE
Redfor (China) 2010 factions receives multiple Shandong carriers in Marianas

### ISSUE THREAD

**Issue by Drew-Dodson** [dcs-liberation/dcs_liberation#3368]
### Affected versions

10.0.0

### Description

When generating a new campaign vs Chinese Redfor in the Marianas the Chinese get multiple Shandong Carriers despite there only being one in the world. US Navy only receives one carrier group.

### Save game and other files (save game required, bugs without saves will be closed)

[bug_report.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/14910271/bug_report.liberation.zip)

**Comment by Starfire13** [comment]
If there are multiple carrier spawns in the campaign, they get filled with whatever carrier the faction has access to. Multiple times if necessary.

I assume you are playing Pacific Repartee, which has 3 opfor carriers. That's the way Fuzzle set it up. Obviously not realistic, since the campaign start date is 2006, and China didn't even have one carrier back then, let alone 3. However, I don't think letting realism take a backseat to fun is a problem if that is the campaign designer's intent. After all, you can fight Nazi Germany in Las Vegas with F-15Es if you really want to, so it's not like we strictly enforce realism.

Ultimately, not really a bug.
