### ISSUE TITLE
Unable to create new flights for F16s

### ISSUE THREAD

**Issue by skeletonwburg** [dcs-liberation/dcs_liberation#364]
I can't create a new flight for 2 F16s from Incirlik after I deleted the DEAD REINDEER package from the save below. I can create a new package, for example SEAD at BANDICOOT with the Harriers but I can't use the F16s.

Liberation Error: 
`Traceback (most recent call last):
  File "qt_ui\windows\mission\flight\QFlightCreator.py", line 98, in create_flight
AttributeError: 'QFlightCreator' object has no attribute 'error_box'`

[SyriaInvasion.zip](https://github.com/Khopa/dcs_liberation/files/5536442/SyriaInvasion.zip)

I am using 2.2.2 Build 346

**Comment by DanAlbert** [comment]
Fixed by https://github.com/Khopa/dcs_liberation/commit/a81254cd1830cd8ad57ac41de017d94e1c9eb0a5 (to fix the crash) and https://github.com/Khopa/dcs_liberation/commit/75769df8e2e149504ff5abe2889e315fa95f4f57 (to handle the bad case that led to it). It was like you said: aircraft that had missions planned were sold and the inventory wasn't notified. It'll now pop up message box if you try to sell aircraft that have an assignment.
