### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by jazzbre** [dcs-liberation/dcs_liberation#37]
Hey guys, thanks for your hard work on this, it's great!
But one thing I can't find anywhere, and that is, how to actually build this repository (the files that gets packed in RC*.zip for example).
I'd like to build a local develop branch so I can test stuff and fix something :D.

Thanks!

**Comment by jazzbre** [comment]
- pip install everything in requirements.txt file
- run pyinstaller pyinstaller.spec
- dist folder should be created with all needed files

Anything else?

**Comment by Khopa** [comment]
Hi, 

I will write an extensive guide later, but currently if you have checked out develop branch, some stuff might not work because i'm using my own modified pydcs version. 

So you'd have to checkout my pydcs version here : 

https://github.com/Khopa/dcs/tree/add_manual_heading

And copy the dcs folder in your python installation site-packages directory, or in your virtualenv, 

To run from source, my setup is : 

![image](https://user-images.githubusercontent.com/2546901/89716583-7ba26a80-d9ae-11ea-83f0-b7941942a764.png)

And to make releases, my config is : 

![image](https://user-images.githubusercontent.com/2546901/89716562-4ac23580-d9ae-11ea-902e-50ddd08cb9d2.png)

**Comment by jazzbre** [comment]
Cool, it works! Thanks for this 💯.

**Comment by jazzbre** [comment]
Hey @Khopa, I can run the campaign and everything but when I try to run the mission in DCS, it says:
2020-08-08 18:43:14.567 ALERT   LUACOMMON: Error: GUI Error: [string "mission=..."]:392: attempt to index global 'Values' (a nil value)
GUI debug.traceback: stack traceback:
	[C]: ?
	[string "mission=..."]:392: in function 'fun'
	[string "./MissionEditor/modules/me_mission.lua"]:1566: in function 'load'
	[string "./MissionEditor/modules/me_toolbar.lua"]:696: in function 'func'
	[string "./Scripts/UI/ProgressBarDialog.lua"]:154: in function 'updater'
	[string "./Scripts/UpdateManager.lua"]:64: in function <[string "./Scripts/UpdateManager.lua"]:40>

It looks like Values array is not available in the mission lua file (it looks like ["value"]=Values.AAM in mission.lua), did I forget to do something? I can't find where this stuff gets injected into lua file.
If the dcs is not from your special branch it doesn't even start the mission so that isn't it.

**Comment by Khopa** [comment]
My bad, i thought i had pushed my latest changes on my pydcs fork, but it was not the case. .

I now have pushed them; but this mean you have to replace your local pydcs by the one there again, sorry.
