### ISSUE TITLE
Some minor bugs

### ISSUE THREAD

**Issue by Mustang137** [dcs-liberation/dcs_liberation#38]
Hi Kohpa,
Just a list of things I've seen over the past week....

1. AI pilots eject when they call bingo fuel
2. Tankers traveling at or near stall speed making AAR impossible
3. Bluefor ground units spawning in the center of runways which shuts down the base for the duration of the mission
4. Culling of units under 120kms seems to stop a lot of AI flights. I had one mission where my wingman and I were the only aircraft flying (except for AWACS and Tanker)

Cheers and many thanks

**Comment by Khopa** [comment]
1 - AI should RTB on Bingo in RC10 (at least it should be setup to.)

2 - I will increase tanker speed for RC10

3 -> Bluefor ground units spawning in the center of runways which shuts down the base for the duration of the mission
Yes this can happen at times... :/
This is a painstaking job to add exclusions zone for each airfield to prevent ground unit spawn, it has been on my todo list for a while ... 

4 - This will be fixed in RC10, there will always be flights generated for both side regardless of the culling settings.

**Comment by Mustang137** [comment]
Roosterfeet on the DCS forums thinks that the fix for AI wingman running out of fuel is related to the following....

"Setting restricted afterburner use in the mission editor seems to help some. It might be my imagination but I'm pretty sure they use AB less with this on. You can find it under advanced waypoint actions. Click add, and select set options. If you set it on waypoint 0 it should remain in effect for all additional waypoints unless you later set it to off. I think it's supposed to restrict but not eliminate afterburner use.

Khopa could potentially set the mission to spawn with this on by default and maybe EPLRS for Aircraft like the F-18 while he's at it"

**Comment by Khopa** [comment]
Closing, 

2,3,4 should be fine now in latest version. 
1 i can't find a 100% reliable solution for, the AI is setup to RTB on Bingo fuel; and restrict afterburner usage. But sometimes they just do not seem to care.

If you are still having one of these issue, please open a new issue for each problem. 😉
