### ISSUE TITLE
Ferry flights for new aircraft

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#384]
Rather than new aircraft magically appearing at airbases, they could be flown in from off map. Would improve the ambience and also give an opportunity to interdict reinforcements.

The AI would need to account for the safety of the airfield to avoid ferrying all their planes to their deaths.

**Comment by DanAlbert** [comment]
Moving out of 2.3 so we can make sure we've worked out the kinks in transfers first.

**Comment by DanAlbert** [comment]
Most campaigns don't actually use off-map spawns, so there's nowhere for the aircraft to come from. We could either require that all maps have one, or close this wont-fix.

@bgreman I see you self-assigned this. wdyt? The ferry mission type is already done, so the remaining work here is small, it's just a question of whether we _should_.

**Comment by bgreman** [comment]
I was thinking of it as ferry flights not from off-map but between bases that could be player (or under some criteria, AI?) planned.  Sounds like you have this in place for transferring entire squadrons, and since individual airframes shouldn't be able to be ferried under that system, I think this one just goes poof.
