### ISSUE TITLE
Skynet warns of unsupported SAM Site

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#405]
In a mission generated from 2.2.1 on the Invasion Of Iran Campaign in Persian Gulf, Skynet throws a warning in a popup when you enter the mission saying "WARNING: you have added an SAM Site that Skynet IADS can not handle:  RED|SAM|157.

Attached is the campaign and mission.  I did move two waypoints on a friendly BARCAP flight, but that shouldn't effect anything related to this issue.

[405_InvasionOfIran.zip](https://github.com/Khopa/dcs_liberation/files/5570823/405_InvasionOfIran.zip)

Edit, on the subsequent mission, I get more of these warnings. (From three different units this time)

**Comment by DanAlbert** [comment]
It's _probably_ not a real issue. This happens when you kill the search radar of a SAM but leave the rest alive and then start a new mission. aiui the SAM should revert to whatever behavior it's capable of without its on SR.

* For SAMs with TELARs like SA-11s they should revert to the degraded mode with the launcher using its own search radar.
* For SAMs with separate search and track radars I think they degrade to using the track radar, but I'm not sure about that.
* For SAMs with a combine search and track radar and no TELAR the SAM is rendered inoperable.

I'll check with the skynet maintainer just to be sure.

Regardless, the warning is annoying. I think @walterroach is planning on cleaning up the way we generate group names, and a side effect of that would be the ability to avoid this.

**Comment by SnappyComebacks** [comment]
Oh that would make sense.  Unless I missed out on some SAM death's that I'm unaware of from that mission, I think destroying the launchers of an SA-11 and leaving the SR and CC created the two new messages (when I mentioned that there were three messages after completing the mission).

**Comment by DanAlbert** [comment]
I think that's also possible. I think skynet shows the message whenever it doesn't have a complete SAM group.

**Comment by walder** [comment]
Skynet prints this message when the group is not a complete group that it can use. In that case the SAM site will not be part of Skynet. 

As @DanAlbert mentioned that happens when a unit of the group that is required is damaged or hasn't been added in the mission editor. When developing Skynet I did not take in to account dynamic missions :-).

Anyway its on the backlog to improve the debug messages of Skynet.

**Comment by DanAlbert** [comment]
Some other work for 2.3 actually requires us to get better at naming things anyway, so I think we can fix the naming so the warnings don't happen at the same time.

**Comment by DanAlbert** [comment]
This is a bit more complicated than I first thought because this happens whenever the SAM is missing _any_ of its required components (SR, TR, or launcher), and only when the particular variety of SAM requires those components. We don't have that data currently. Nothing impossible, but it's rather time consuming so moving to 2.4. We lived with these warnings in 2.2 so not the end of the world to keep them in 2.3.

I think the best way to do this would be to move the decision of whether or not a SAM gets added to Skynet to our Lua code and get an `IsCompleteSam` API added to Skynet (assuming @walder agrees; it would just be factoring the existing condition in `SkynetIADSAbstractRadarElement:setupElements()` out into its own function).

**Comment by walder** [comment]
it's best to just ignore the message for the moment. If one of the units is missing or damaged the Site is useless basically in DCS and therefore Skynet. @DanAlbert I have planed for a refactoring of `SkynetIADSAbstractRadarElement:setupElements()` , had a factory Class/Table in mind to create SAM sites. FYI: In the next release of Skynet all debug messages will be output in the dcs.log file, making them less annoying. Only the network status and contacts will be output on screen in game. Will post detailed change log when released.

If you need a table of required units per SAM site in DCS for Liberation, feel free to use the file: https://github.com/walder/Skynet-IADS/blob/master/skynet-iads-source/skynet-iads-supported-types.lua . It will be part of Skynet long term and updated with the HighDigitSAMs Mod in development. Besides it features the official Nato names, something not in the DCS database at the moment.

**Comment by DanAlbert** [comment]
I won't argue with you telling me to do less work 😁

Will leave this open until we're able to take that update. Thanks for chiming in!

**Comment by DanAlbert** [comment]
Was done when we imported the latest skynet.
