### ISSUE TITLE
AI purchaser should fill incomplete squadrons

### ISSUE THREAD

**Issue by MedievalBunny** [dcs-liberation/dcs_liberation#41]
I've got several enemy airbases in my current campaign that are some variation on this example:

![Capture](https://user-images.githubusercontent.com/19675397/89610084-475c6c00-d83f-11ea-9ab7-186b7894fcc2.JPG)

The AI will not create singleton flights, and they don't seem to be interested in purchasing single reinforcements to make whole flights out of the airframes they have. I've seen the AI buy 2x MiG-29s at a base that had 1x Su-27 and 1x Su-33 a few times, which is quite an inefficient use of resources. Most of the time, these singleton jets just sit unused at a base for many turns in a row until the base is captured.

**Comment by Khopa** [comment]
Yes that's true, the current enemy unit recruiting process is rather random, and the AI will never plan a flight with a single plane.

**Comment by MedievalBunny** [comment]
It'd be cool if the AI would start generating singleton flights if certain conditions are met. Like, that's all they have left and the front is within a certain distance. It just seems a bit silly for them to keep half a dozen jets on the ground doing nothing as the base is about to fall.

**Comment by DanAlbert** [comment]
A quick fix worth doing for 2.4 would be having the AI just sell off any aircraft it doesn't use before buying for the next turn.

**Comment by DanAlbert** [comment]
Short term fix is in. If there are an odd number of an aircraft type remaining at a base after planning it'll sell one to even it out, since the single aircraft will be ignored by planning. Avoided selling _all_ unused aircraft because we want to keep targets for OCA strikes.

Leaving this open because we could instead be replenishing those squadrons.

**Comment by sith1144** [comment]
This has gotten worse with the new squadrons system. It refuses to buy certain aircraft. Looking at the campaign I am working on (see attachment) the OPFOR is supposed to have su-24s, mi-28s, ka-50s, and su-25Ts on the airfields right next to the front, but it refuses to buy this even when it has plenty of spare money and the further back squadrons are full. Giving it 5000 money at campaign start results in it buying, say, 26 su-34s for a single squadron at Sochi and not a single of the aforementioned planes, with over 2000 money left per the intel screen. IMO the squadrons system should prioritize letting every squadron get at least a single flight into the air. This would offer the campaign designer finer control over OPFOR, which I thought was rather the point. The campaign designer can customize the diversity and quality of enemy air forces. By prioritizing giving every squadron a single flight diversity of aircraft is guaranteed but otherwise the purchasing logic preferring "good" aircraft can stay as is. 
[Operation Lighthouse.zip](https://github.com/dcs-liberation/dcs_liberation/files/7590707/Operation.Lighthouse.zip)

**Comment by DanAlbert** [comment]
Not really relevant any more. This effectively does happen now.
