### ISSUE TITLE
requirements for CTLD implementation 

### ISSUE THREAD

**Issue by Moguy164** [dcs-liberation/dcs_liberation#412]
I would like to implement the CTLD plugin into liberation, however it requires that the group names and unit names stay consistent over the campaigns/missions, i was told changing the names would mess up the debriefing. 
so my question is how can we change the names so that they are compatible with the CTLD?

**Comment by Quinn-Malachite** [comment]
Group names of transport units don't matter. The pilot names of any transporting unit needs to be written into a list in the scripts. Pickup and drop-off zones (for AI) also need to be pre-written into the script as a list.

(There is also an advisory that player transport units should be single unit groups, otherwise the other members of the group will get radio commands they shouldn't have but this is not as important for an initial implementation)

The trick really is, can Liberation write to the script while making the mission? If it can then it can write in those pilot names and the zones it has made somewhere for pickup and dropoff of troops. If not then presumably a pre-written script could be made with zones and pilot name and then liberation could name as required, but this results in a much deeper level of change to liberation.

**Comment by walterroach** [comment]
Besides naming for CTLD to work during the mission, there's the question of persistence from mission to mission.  Currently if you move units from point a to point b, the next mission wouldn't reflect that.

**Comment by Moguy164** [comment]
and liberation can't read the position of units? or at least add the units to the list of units at the front line

**Comment by walterroach** [comment]
Not "can't", but "doesn't".

**Comment by Khopa** [comment]
Hey, 

Just adding that @davidp57 created a plugin for his VEAF framework. This include some CTLD feature, but not sure how exactly. 
See : https://github.com/VEAF/dcs-liberation-veaf-framework/releases
