### ISSUE TITLE
AI bomber flights from offmap spawn point fly very slowly (#454 preview)

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#414]
[Files.zip](https://github.com/Khopa/dcs_liberation/files/5576149/Files.zip)

AI B-17 flights from Red Sea/UAE offmap spawn point are stalling out of the sky enroute to the target. https://steamuserimages-a.akamaihd.net/ugc/1655598478808002104/23C9C36A8F0D48FE506D463652D59FD6A08DB97B/

Contrast that with AI B-17 flights from Incirlik that took off from the airbase. https://steamuserimages-a.akamaihd.net/ugc/1655598478808032501/C560EBB5C3AF181059B3DF30AAC6C85A8128F022/

**Comment by DanAlbert** [comment]
I think it's because we estimated the speed much higher than they are capable of. I've seen AI go very stupid if they have no chance of making their TOT.

They fly just fine for most of their flight plan, although slowing down considerably from the speed we spawned them at, until (not related to reaching a waypoint) they start oscillating speed and pitch a lot until they're too slow and fall. Removing the TOTs on one of the flights leaves them to fly almost the same flight plan five minutes sooner and they do fine, so it's not an issue of running out of fuel.

**Comment by DanAlbert** [comment]
> They fly just fine for most of their flight plan, although slowing down considerably from the speed we spawned them at, until (not related to reaching a waypoint) they start oscillating speed and pitch a lot until they're too slow and fall

Sounds like a DCS bug tbh. Closing on the assumption that this hasn't happened recently. This bug is quite old, and I haven't heard anything like it since.

**Comment by Starfire13** [comment]
Yeah, I haven't noticed this happening in quite a long time.
