### ISSUE TITLE
SA-15 point defense for SA-10

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#417]

**Comment by qwertymanisalive** [comment]
I don't think SKYNET can handle mixed SAM units in a group. One possible workaround is to spawn 2 separate SAM groups, one SA-10 and one SA-15 group close to each other?

**Comment by DanAlbert** [comment]
I thought skynet wasn't too picky, but I haven't tried. I bet if it's not valid to put an SA-15 among an SA-10 that'd be something @walder is interested in improving at some point though.

**Comment by qwertymanisalive** [comment]
I looked at one of walder's demo missions on his github to make sure I knew what I was talking about and it looks like he only has one type of SAM unit for each group. There are no SA-10 units mixed in with SA-15 units. 

However he does place SA-15 groups close to SA-10 groups for point defense, but they are 2 separate groups. 

https://github.com/walder/Skynet-IADS/blob/master/demo-missions/skynet-test-persian-gulf.miz

**Comment by SnappyComebacks** [comment]
> 
> 
> I thought skynet wasn't too picky, but I haven't tried. I bet if it's not valid to put an SA-15 among an SA-10 that'd be something @walder is interested in improving at some point though.

I'm not sure if it's a fluke as I've only done this twice but when I've done rocket attacks with Skynet (unguided ccip rockets) from an F16 on SA-10s with Strelas + Shilkas in the same group, the short range defenses are silent.  I fly in terrain masked and destroy the SA-10s tracking radars then it feels like I have free reign over the target AO and can fly as high as I want.  Directly above and around the Strelas/Shilkas.

**Comment by DanAlbert** [comment]
The docs are pretty clear: https://github.com/walder/Skynet-IADS#point-defence-1

So they do need to be in a separate group, and we need to be able to associate those two groups in the lua. Filed https://github.com/walder/Skynet-IADS/issues/32 to see if the simpler option is viable, otherwise we probably need to un-plugin skynet and just generate the whole config rather than trying to put it together dynamically.

Putting them in separate groups would also be a little trickier because we'd have to build some support to avoid putting the two groups on top of each other. Doable, but not something we can do currently.

**Comment by DanAlbert** [comment]
Although we can totally do this for non-skynet, and the skynet behavior is suboptimal but still will use the point defenses when the group is active, so we should do the simple thing now, at least. Forked improved skynet behavior to https://github.com/Khopa/dcs_liberation/issues/470

**Comment by walder** [comment]
The one SAM type per group is mainly because Skynet turns SAM sites on and off via the group's controller. So all units in that group turn off or on at the same time. 

The second reason for only having one type in a group is due to distance calculation. Let's say a SA-2 and a SA-15 where in the same group. As soon as a contact is in range of the SA-2 Skynet turns on the whole group including the SA-15 that will start to emit its radar, giving away its location even though the contact is far out of range of the SA-15. So mixing SAM types in a group will lead to unexpected behaviour with Skynet.

**Comment by DanAlbert** [comment]
Makes sense, thanks for the explanation! Just in case it wasn't clear, it's our _use_ of skynet leading to suboptimal behavior. Skynet definitely appears to be doing the sensible thing :)

**Comment by qwertymanisalive** [comment]
This is relatively new to Mission Editor but it is possible to reduce engagement range of SAM groups so that they don't fire until you are well inside the kill zone. So it's possible to see the search radar on RWR and keep flying towards the SAM unit without anything lethal happening until you have no escape! :-(

In this setup I've also changed the probability for another level of unpredictability.

![Screen_201127_171014](https://user-images.githubusercontent.com/39744809/100494876-f5e03180-30fa-11eb-9d10-eefba17db7b9.png)
![Screen_201127_171057](https://user-images.githubusercontent.com/39744809/100494880-07293e00-30fb-11eb-9491-4903c207b932.png)
