### ISSUE TITLE
Hornet Target Waypoints Not At Ground Level

### ISSUE THREAD

**Issue by walterroach** [dcs-liberation/dcs_liberation#425]
In Mission Editor, Liberation generated waypoints are set at some arbitrary MSL near ground level rather than 0 AGL, which causes their location to display laterally incorrect in the jet.  Not sure if this is a DCS bug or Liberation, but putting it here to investigate.  If you set the Liberation generated waypoint to 0 AGL in ME and then continue the mission, it appears properly in game.

**Comment by qwertymanisalive** [comment]
I'm not sure if this is related but I noticed that SATNAV was not activated on the Mission Options page in Mission editor for a Modern campaign I was running. 

The JDAMs missed by a mile on the first attempt but when I activated SATNAV and reran the mission 100% hits with the JDAMs. 

I will try to replicate again and see if this is consistent in further missions.

**Comment by DanAlbert** [comment]
Not a complete fix, but it sounds like https://github.com/Khopa/dcs_liberation/commit/17b0cee50720bfa9203504112cb6070fec75dd92 and https://github.com/pydcs/dcs/pull/102 will fix JDAMs reaching their targets, even if the pod is looking at the wrong spot. Someone in discord reported that fixed things at least for the JF-17.

**Comment by unixwitch** [comment]
i'm not sure if this is the same issue, but i've been flying the Hornet on some strikes missions today in 2.2.1 and noticed that the target waypoint elevation was set to 0, which made the TGP point to completely the wrong place.  i estimated the actual elevation was about 6000ft, entered a new waypoint at the same coordinates with that elevation, and found the targets. 

this seems pretty easy to reproduce (it happens every time) so i can provide saves/missions if needed.

i was using JSOWs, but i designated the target with the TGP rather than using the waypoint coordinates, so i don't know how this would have affected the JSOW.

**Comment by DanAlbert** [comment]
Yep, same bug. Already fixed, just not released.
