### ISSUE TITLE
Liberation Campaign on a Dedicated Server

### ISSUE THREAD

**Issue by GitGeg** [dcs-liberation/dcs_liberation#43]
Is there a procedure or process that enables a liberation campaign mission to be run from a DCS.openbeta dedicated server?

- Can the dcs_liberation software be managed locally and the mission synced over?
- Can the dcs_liberation campaign be run on a server?

And lastly....

-Is there a discord or a forum to ask these questions so I am not cluttering up the issues page on GitHub?

**Comment by Khopa** [comment]
Hi, 

No but, there are way to hack your way through this with release 2.0RC9.. but it is not straightforward though, and i have not tested it...

On the server you have to edit the file **<dcs installation_directory /Scripts/MissionScripting.lua** and replace it by the file provided in **<dcs_liberation_directory>/resources/scripts/MissionScripting.lua** (on your computer this is done automatically)

The liberation mission generated on your computer will be configured to write a "state.json" file at the root of your DCS Liberation directory (the one on you computer.). So it will only work on your server if you have the same directory structure (so you have to create a fake "dcs liberation" directory on your server.

For instance, if on your computer, the DCS Liberation directory is in : **D:\DCS Liberation 2.0RC9**, make sure to create the same directory on the server. (If you have the possibility to do so.) 
  
Then you have to retrieve the state.json file from your server once you have played the mission, and copy it over your local DCS liberation directory on your computer while DCS Liberation is waiting for mission results. And it should detect the mission result. 

It will be a bit easier with the upcoming 2.0.10 release, since I added a "submit manually" button to submit the mission result to DCS liberation even if the mission has been done from another computer : 

![image](https://user-images.githubusercontent.com/2546901/89716379-bc997f80-d9ac-11ea-89da-5c4731b704bc.png)

If i have time, i will also add an advanced setting to setup the location of the "state.json" file manually.

-------------------------------------------------------

The Discord server is there  : h t t p s : / / d i s c o r d . g g / bKrtrkJ

**Comment by DanAlbert** [comment]
A handful of changes to help dedicated server use went in for 2.1 and 2.2. https://github.com/Khopa/dcs_liberation/wiki/Dedicated-Server-Guide documents the recommendations.

Any further improvements will come from a client/server mode, which there's ba separate bug open for.
