### ISSUE TITLE
Enemy force multiplier need re-enable

### ISSUE THREAD

**Issue by foxwxl** [dcs-liberation/dcs_liberation#440]
The enemy force multiplier inside campaign setup is currently disabled and not selectable. Need a fix.

Thx.

**Comment by DanAlbert** [comment]
Fixed in 2.3. Not that this only controls how many aircraft the AI will buy. The planning algorithm has never been affected by this, so  you'll only see a difference if it allows them to plan flights that they previously couldn't. That should result in a pretty large increase of offensive sorties from red, but they'll still be flying the same number of CAPs. Those offensive sorties will include escorts though, so A2A contacts will increase anyway.

**Comment by DanAlbert** [comment]
(I also cherry picked the fix to the 2.2 branch, so it'll be in 2.2.2 if we end up doing that)
