### ISSUE TITLE
C101 firing single rounds per attack

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#493]
Forking from https://github.com/Khopa/dcs_liberation/issues/492

Also, The C101 appears to only fire single shots from its cannon when attacking ground targets. This might possibly be because it only has external gunpods rather than an internal gun, and it's being treated similar to a rocket? The Viggen, for example, also only fires single rockets from its rocket pods in Liberation.

**Comment by Hornet2041** [comment]
this is a DCS issue that is shared with the Harrier's gunpod. I don't think there's anything that can be done on the Liberation side for this. very long time dcs bug now.

**Comment by DanAlbert** [comment]
I'd guess that changing the task to "expend all" or whatever it's called would work, but that depends on https://github.com/dcs-liberation/dcs_liberation/issues/269

**Comment by Hornet2041** [comment]
no, that would just ensure the airplane makes as many passes on the target as there are rounds in its pod, instead of dumping it all at once.

![image](https://user-images.githubusercontent.com/55866858/123571378-127b3f80-d798-11eb-83d5-89c92c6df874.png)
[testing gunpods.zip](https://github.com/dcs-liberation/dcs_liberation/files/6722943/testing.gunpods.zip)

**Comment by DanAlbert** [comment]
Bummer. Nothing we can do about this then. Closing.
