### ISSUE TITLE
WW2 Factions still producing Duplicate TGO error

### ISSUE THREAD

**Issue by walterroach** [dcs-liberation/dcs_liberation#534]
Reported by Skeleton on Discord, #517 error still occurring with WW2 factions:
![unknown](https://user-images.githubusercontent.com/37820425/101827847-6b360400-3af6-11eb-987d-ce6348887ee7.png)

> The Error still occurs in Build 634, but only in WW2 scenarios. If I use modern factions in BattleOfBritain for example it works. Allies 1944 vs. Germany 1944 is not working.

**Comment by Khopa** [comment]
Fixed here : https://github.com/Khopa/dcs_liberation/commit/b74d8b12d0ce17a4391769bf321b9d75818b1b72

The issue was that the Blitz truck on german flak site was named AAA#1 like one of the guns.
These kind of issues might still exists in other group generator. So this error might come back if we are not careful with unit naming in group generators.
