### ISSUE TITLE
Install new Release

### ISSUE THREAD

**Issue by daniele777** [dcs-liberation/dcs_liberation#603]
Sorry i previus install a version in exe package .--but now? How to install new release?
thx

**Comment by Khopa** [comment]
Download the zip release : 

![image](https://user-images.githubusercontent.com/2546901/102516445-229abf80-408f-11eb-81ad-64238d19f1b9.png)

Unzip it somewhere convenient for you. And that's it, dcs liberation is installed.

**Comment by daniele777** [comment]
Can i unistall previus release ?
Ok i try new release but when i create new campagn i don't saw carrier or airfield to add unit...how to do ??

**Comment by Khopa** [comment]
You can delete the previous version manually. The installer was just copying file. We removed it, because people would let it install DCS Liberation in the "programs files" directory, which caused issues with system files right. (The DCS process wouldn't be able to write the state file for some people)

> Ok i try new release but when i create new campagn i don't saw carrier or airfield to add unit...how to do ??

It should work the same way as the previous version. 
What terrain and faction did you use ?

**Comment by daniele777** [comment]
I'll try for Persian gulf...ops Sorry factory usa 2005 no carrier .... Caucaso OK!

![Cattura](https://user-images.githubusercontent.com/8341788/102520180-b2db0380-4093-11eb-8238-76240bd48783.PNG)

**Comment by DevastatorCM** [comment]
after updating to 2.3, I am not able to open my current liberation file. Open file from menu is not working

**Comment by DanAlbert** [comment]
Saves from earlier releases are not compatible.
