### ISSUE TITLE
assertion failure on base capture

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#644]
Got this when capturing a base on 2.3.3-preview:

```
2020-12-21 19:05:00,560 :: ERROR :: Could not process base capture 18||2||Sochi-Adler
Traceback (most recent call last):
  File "C:\Users\dan\src\dcs_liberation\game\event\event.py", line 214, in commit
    self.redeploy_units(cp)
  File "C:\Users\dan\src\dcs_liberation\game\event\event.py", line 342, in redeploy_units
    cp.base.commision_units(moved_units)
  File "C:\Users\dan\src\dcs_liberation\game\theater\base.py", line 102, in commision_units
    assert value > 0
AssertionError
```

None of my units were redeployed.

[not captured.liberation.txt](https://github.com/Khopa/dcs_liberation/files/5727560/not.captured.liberation.txt)
[not_captured.miz](https://github.com/Khopa/dcs_liberation/files/5727559/not_captured.txt)
[state.json](https://github.com/Khopa/dcs_liberation/files/5727551/state.txt)

The save is unfortunately from the turn after processing so may not be useful.

**Comment by Khopa** [comment]
Oh i see the problem.

This assertion used to make sense when this method was only invoked when buying units, i think we can remove it safely.

In the case of redeployment of units, it is possible to have zero in values, if some units were lost in battle and the count went back to zero. A unit count number equals to zero will not cause any error anyway.

I think this bug has been there for a while... (at least since automatic redeployment was implemented)

I'm fixing this for 2.3.3

**Comment by Khopa** [comment]
Fixed in https://github.com/Khopa/dcs_liberation/commit/72c233cb0d81c4e61ec5d3c27f521cb728c13741
