### ISSUE TITLE
Mission roles should match appropriate aircraft

### ISSUE THREAD

**Issue by clutchtomcat** [dcs-liberation/dcs_liberation#687]
I get a lot of weird mission roles for aircraft that aren't designed to do that role, for example SEAD for the Harrier when there's two dozen Hornets and Vipers--much more suited for SEAD--available for fragging. In the WW2 scenarios I get lots of BAI fragged for Spitfires, loaded 113% of their max takeoff weight, when there are plenty of B-17s and A-20s sitting unused. The aircraft should be fragged for missions suitable for that particular airframe.

**Comment by DanAlbert** [comment]
Current logic is to find the closest aircraft capable of performing the job. In 2.4 it will buy the best aircraft for the job at the closest airfield that is practical, so I think this is already sufficiently complete.

The only change could make would be to prefer better but more distant aircraft. Since the closest airfield is already being chosen that seems of dubious value.

**Comment by clutchtomcat** [comment]
> Current logic is to find the closest aircraft capable of performing the job. In 2.4 it will buy the best aircraft for the job at the closest airfield that is practical, so I think this is already sufficiently complete.

If we take the SEAD example, Harriers shouldn't even be considered for SEAD at all, because they are not realistically capable of SEAD. So regardless of whether they are closest, they should not be chosen for SEAD in the first place. There needs to be role limitations for aircraft.

**Comment by DanAlbert** [comment]
And I'm saying that's already somewhat how the system works. It's not exactly that way because doing it exactly that way would cause the system to prefer aircraft that have to travel hundreds of miles to get to the target over ones that are already closer. It's already weighted to buy aircraft in a way that prefers not-harriers for SEAD.

**Comment by clutchtomcat** [comment]
Then it appears there's some kind of ranging issue, because I get the wrong aircraft for the role while suitable aircraft further away sit unused, not fragged for any missions at all, with lots of "not enough aircraft in range" messages in the log. With external tanks they should be well within range.

**Comment by DanAlbert** [comment]
> **In 2.4** it will buy the best aircraft for the job

Unless you're on the preview build you don't have the feature yet.

> With external tanks they should be well within range.

Not how mission planning works yet. There's another FR open for that.

**Comment by clutchtomcat** [comment]
> > With external tanks they should be well within range.
> 
> Not how mission planning works yet. There's another FR open for that.

Ooof okay. That's where my expectations are getting poked.
