### ISSUE TITLE
transfer equipment out of captured bases

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#693]
Capturing a base pretty severely breaks the faction because they lose so much equipment.

Ground forces are already retreating from the base so they should just transfer to the next base.

I'm tempted to say that inactive aircraft should be captured, but until the AI is smart enough to redeploy aircraft out of soon-to-be-captured bases we should just transfer those too.

**Comment by Hornet2041** [comment]
inactive aircraft do get flipped though 🤔 i thought it was intentional 🤓

**Comment by benedikt-wegmann** [comment]
I would like to vote for making this a selectable option. I like that capturing an airbase also has a chance of some OPFOR aircraft falling into my hands. :thinking:

**Comment by HILOK** [comment]
what's the status on this topic? yesterday in invasion of iran lite, my side captured shiraz, where redfor had about 60 airplanes (not that they couldn't see that coming, as blue troops where practically knocking on their door at the beginning of the turn 😂)
result was redfor down to 8 planes.
kerman would have been available for transfer to redfor...or does it have to do with the number of shelters available?

**Comment by DanAlbert** [comment]
> does it have to do with the number of shelters available?

Yes.

**Comment by HILOK** [comment]
thanks. are there any plans to change that in the future?

**Comment by DanAlbert** [comment]
No, why?

**Comment by HILOK** [comment]
i am probably missing something here, but since you're asking: 
for once, as you say in the OP,  "Capturing a base pretty severely breaks the faction because they lose so much equipment.", which brings a severe misbalance into the game.
second, wouldn't any real army try to save their assets, especially the ones with high mobility, and evacuate as much as they can?

**Comment by DanAlbert** [comment]
But where would they go if there's nowhere in range to put them?

**Comment by Hornet2041** [comment]
pretend opfor sabotages their aircraft and the parking spaces they're in by denying the usage of the aircraft slots at the captured airbase for a round or two?

**Comment by HILOK** [comment]
> But where would they go if there's nowhere in range to put them?

do i understand correctly that the only issue is the number of shelters? would it be possible to allow using other parking spaces as well? maybe spawn/despawn a/c on same parking slots, as we have currently on carriers?
only trying to make a suggestion here, how to keep the game challenging after a main base has been captured.

**Comment by DanAlbert** [comment]
It's all parking. If the airport is full they are not transferred.

**Comment by HILOK** [comment]
ok. this is the part i dont understand. i just looked up the parking spots at kerman: 42. there were 6 a/c already there at the time my faction took over shiraz, technically plenty of room to transfer air assets to it. could you please explain?
thanks

**Comment by DanAlbert** [comment]
Out of range maybe? File a bug if you think you found a problem. My guesses aren't going to get us anywhere.

**Comment by HILOK** [comment]
danalbert, please understand that i am not here to rant, and only trying to improve this awesome piece of software that i have been enjoying since v2 came up (donator btw).

my point is, capturing a base, where the opponent has most of its air assets can basically break OPFOR, as you describe in the OP. apparently, despite the fact that there would be space available on other AB in range, air assets are not transferred before a base is taken, and therefore lost. the campagin goes on, but without real air resistance. maybe someone could look into this.

what is your point exactly?

**Comment by DanAlbert** [comment]
Yes, that's why I'm asking you to file a bug. We need the data that the template asks for in order to investigate.

**Comment by HILOK** [comment]
ok.please specify: what exactly do you need? i dont know what "the data that the template asks for" is. thanks

**Comment by DanAlbert** [comment]
Click "new issue" and follow the instructions.
