### ISSUE TITLE
RuntimeError: Duplicate TGO unit: aa|2|Armor#1

### ISSUE THREAD

**Issue by vanson77** [dcs-liberation/dcs_liberation#727]
Another Duplicate TGO Error.
Campaign Startet with developer build 939, occured while playing on latest build 970.
Please note that i disabled EWRs in frations, because i started campaign while issue 708 was not resolved at this time.

[black_sea_939.zip](https://github.com/Khopa/dcs_liberation/files/5772535/black_sea_939.zip)

**Comment by walterroach** [comment]
Unfortunately, campaigns started between build 924 and 945 are susceptible to this bug since the ID counter causing it was reset the first time you hit the "Pass Turn" button (even though it doesn't cause an issue until TGOs are created later).  

This should never occur on campaigns generated on builds 945+

**Comment by vanson77** [comment]
Okay, makes sense. I will start a new campaign, and if error occurs again i will open a new issue.
