### ISSUE TITLE
state.json file gives wrong results when MP mission is hosted in local

### ISSUE THREAD

**Issue by Aigle-2** [dcs-liberation/dcs_liberation#740]
**Describe the bug**
When my group plays liberation (I usually hosts), results at the end of the mission make no sense. (It works fine in singleplayer)

**To Reproduce**
1. Generate mission 
2. Host in MP with local server
3. Play mission and leave server 
4. Manually upload state.json file to the software
5.  Compare results : there are none. (ex : 4 grounds units instead of 10+ planes and 20+ ground units)

[state.zip](https://github.com/Khopa/dcs_liberation/files/5778506/state.zip)

**Version information (please complete the following information):**
 - DCS Liberation V2.3.4

**Comment by walterroach** [comment]
Are you closing Liberation in between steps 2 and ~~3~~ 4?

**Comment by Aigle-2** [comment]
I close the server/close DCS then upload state.json to liberation

**Comment by DanAlbert** [comment]
But are you closing Liberation at all? In the current release the miz file is valid only while the window that opens when you click "take off" is open. For example, if you:

1. Click "take off"
2. Close the new window because you're not ready to play yet
3. Put the mission on your server
4. Then later click take off again and play the mission you generated earlier

Your results will be invalid. You must play the generated mission before closing the window that opens when you click take off. If you close the window, the next time you click the button a different mission will be generated and Liberation bis expecting the new mission, not the old one.

**Comment by Aigle-2** [comment]
I see. I must not close the window with the abort mission button. We will do some test, and check it out.

**Comment by DanAlbert** [comment]
Closing since that seems like the likely explanation (I host MP games on my machine frequently without issues). Will reopen if that's not the case.

**Comment by Aigle-2** [comment]
It worked. Thanks.
