### ISSUE TITLE
Reduce BARCAP engagement range when near the enemy

### ISSUE THREAD

**Issue by MaHuJa** [dcs-liberation/dcs_liberation#742]
**Describe the bug**
[image](https://user-images.githubusercontent.com/3055693/103881481-c994d900-50da-11eb-8a0b-49629852cf90.png)

**To Reproduce**
Using version f2e35c (current dev)
West georgia campaign, blue vs Georgia. (Also, note the relative lack of air defenses.)
(I'm using a custom faction.)
Create new package on a strike target. (Pure CAS, friendly-targeted CAP does not suffer from this.)

Occurs both from Kobuleti and Carrier.
Enemy flight plans

**Expected behavior**
Sane flight lengths. 
Maybe as much as 10-20nm back, especially as there are no significant air defenses.

**Additional information**
DCS Liberation save file
[24pre.zip](https://github.com/Khopa/dcs_liberation/files/5781104/24pre.zip)

**Version information (please complete the following information):**
Image from f2e35c, which is current dev branch. Has been seen in previous versions.

**Additional context**
May be related to #701

**Comment by DanAlbert** [comment]
Would you prefer your flights loitered in the threat range of enemy CAPs? That's a serious question. The reason the hold/join/split points are out so far back is because anything within 90nm of an enemy airbase is within the engagement range if that airbases BARCAP.

**Comment by MaHuJa** [comment]
At least now I can see what's happening. But how would you intend to instruct players on how this works, so they don't mistake this feature for a bug? I'm certain it will be surprising and considered a bug by much of the user base, as it was for me. Just the way it goes outside the map...

This is a 'safe' preset[1], but those ToT times... 
Other liberation players I know already find *current* ToT times long when they want to go in and have some fun. Instead of holding and twiddling thumbs, they would rather have time for a second mission.  Yeah, there's reasons for it, so they're putting up with it, but usually heading in immediately, in front of friendly AI.

Also, I do not feel confident sending AI on that path without extra fuel.

I'm seeing this 90nm does not apply in a ww2 vs ww2 scenario. So I guess the distance is part of a faction's doctrine? **This is something you'd need to read off the opposing side's data**, though? Because in this particular case, Georgia only has L39s for CAP. I expect it won't have the 90nm hunting range. But will red keep the appropriate distance from my planes? (When #683 is fixed.)
Or, if blue is the ones with the lower tech level...

[1]
Ideally, this would be selectable, on a package level. Hold distance: "Safe" "Medium" "Near" "Overhead" etc, or explicit ranges "90nm".  If you have solid BARCAP of your own, and it's well covered by a SAM bubble, it's less of a problem, so you may want to have it closer in that case.  Default (= red team selection) could come from doctrine as it appears to do now.

> Would you prefer your flights loitered in the threat range of enemy CAPs?

In my order of preference:
1) Make it selectable
2) Remove it until you can make it selectable     <--- Yes
3) Leave it in but make it read from the opponent side. Add UI to explain it (most of (1) though)
4) Leave it in, and wait for the duplicates of this issue.

**Comment by DanAlbert** [comment]
> Ideally, this would be selectable, on a package level. Hold distance: "Safe" "Medium" "Near" "Overhead" etc, or explicit ranges "90nm".

Good candidate for the ever growing https://github.com/Khopa/dcs_liberation/issues/270, although more fine grained threat zones is already another open FR.that would do this automatically.

> But how would you intend to instruct players on how this works, so they don't mistake this feature for a bug?

We can add it to the manual. Truth is nothing we do is going to help everyone, but I don't know what else we can do other than tell people. The display options menu does have an option for showing CAP threat ranges, and it'll show that your join/hold/splits are set right to the edge of that range.

> but those ToT times...
Other liberation players I know already find current ToT times long when they want to go in and have some fun.

Most of our campaigns are not well designed for the current version of the game. The fact that you have to backtrack out of the threat zone means that you don't have any useful airfields. On a campaign that had been built more recently like Black Sea you just wouldn't use an airfield like this. You'd take off from a more distant airfield that resulted in a shorter flight.

Most of the reasons for the long durations are that we're still working on package coordination. Until Liberation is a lot more mature the choices are between being annoyed at your hold time and being very annoyed that all your AI flights are always dead because they're in stupid places or are alone at a time they should not have been. We're not adding delays to make the game boring, we're adding delays to make the AI behave. In my games the retreating holds have made things more challenging because the AI isn't constantly losing all their planes because they're loitering where I can easily shoot them before they become a problem.

As you say, players that don't want to deal with that don't have to follow their TOTs and can just skip waypoints they don't like. I do that all the time. That's a perfectly fine solution while we continue working on this (Liberation is far from a finished game).

> Also, I do not feel confident sending AI on that path without extra fuel.

Automatic fuel planning (including stops for gas, which requires us placing tankers at these safe distances, which is why the safe distance features came first) is already on the todo list. Until then you have the option of planning different missions or altering loadouts.

> Georgia only has L39s for CAP. I expect it won't have the 90nm hunting range

That 90nm isn't related to weapon range. That's just the range at which an enemy CAP flight will commit. The end of their race track can be up to 50nm from the airfield and they'll commit to anything within 40nm.

> In my order of preference...

Thanks, this does help. Going to wait until we get more feedback to make a decision (which is essentially 4 for the time being, but hopefully we have enough feedback before we release). We got a lot of feedback where people were angry about their hold points being in harm's way, so the current behavior was also made at user request.

I'm pretty strongly against 2 in its "ignore completely" form. The other way to come at this is to change the protection range for airfields. That 90nm works both ways. How far out do you want your friendly BARCAPs to engage enemies? If you don't care about bombers or fighters until they're within 50nm we can make that bubble 50nm instead, but I don't think anyone is keen to reduce their defenses.

3 is the current behavior, FWIW.

**Comment by DanAlbert** [comment]
Have been thinking about this quite a bit. I think this is a symptom rather than the problem. Flights are avoiding threatened areas, mostly projected by BARCAPs, but I think we're probably planning BARCAPs too aggressively for airbases that are near the enemy. A 90nmi engagement range is far too aggressive if there is an enemy airfield within 90nmi. I think reducing the protected range makes sense for those cases.
