### ISSUE TITLE
Ammunition depot strike flight generated additional waypoint to SAM site far away

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#745]
Before filing, please search the issue tracker to see if the issue has already been reported.

**Describe the bug**
A strike flight targeting an ammo depot has odd waypoint generation, with an extra waypoint generated leading to SAM site far away.

**To Reproduce**
Unsure how to reproduce. Doesn't occur for other targets I tried. Have attached .liberation file. Take a look at strike flight for KILO#95
![Capture](https://user-images.githubusercontent.com/72491792/103895536-ae5eb380-5144-11eb-9d8d-5ac82632f9f8.JPG)
[Dubai Or Not Dubai That Is The Question.zip](https://github.com/Khopa/dcs_liberation/files/5781689/Dubai.Or.Not.Dubai.That.Is.The.Question.zip)

**Comment by Malakhit** [comment]
This is happening because both the Ammo Dump and the SAM Site are called KILO#95.

Ammo Dump:
![image](https://user-images.githubusercontent.com/31387062/103917917-104bf880-5106-11eb-9af1-d9fb03d05c78.png)

SAM Site:
![image](https://user-images.githubusercontent.com/31387062/103917961-1b9f2400-5106-11eb-9c19-ed5cd58acc2b.png)

Not sure how this has happened, will keep investigating.

**Comment by Malakhit** [comment]
This should now be fixed, thanks for raising the bug report.
