### ISSUE TITLE
Non-package aircraft should prefer hard shelters.

### ISSUE THREAD

**Issue by Malakhit** [dcs-liberation/dcs_liberation#748]
In order to try to prevent OCA strikes, a faction should try to store unused aircraft in shelters where possible.

To do this, we'd need to add a list of parking spots that include a hard shelter, and then for each unscheduled aircraft, have them spawn in those parking spots if possible. This'd be more realistic, and also have the added bonus of making bunker-busting munitions more worthwhile.

**Comment by Mustang-25** [comment]
If you're looking at defining the different parking slots, could you also do the same for helo-only slots? There is a problem at Aleppo with Liberation trying to put fixed wing at the helo slots and they just end up air spawning and crashing. See #690 

Also note that some of the HASes have size limits so that will need to be taken into account.

**Comment by DanAlbert** [comment]
DCS doesn't export the data needed for this.
