### ISSUE TITLE
Feature Request: Detect Script Installation

### ISSUE THREAD

**Issue by loneregister** [dcs-liberation/dcs_liberation#76]
Hi Khopa,
Great work here.  Really enjoying the hell out of it.

I would like to suggest that the program waiting screen (where it's launched the mission, and is waiting for the results) have two green lights on it that are red, if the script is not detected properly in the installation directory as you expect.  As you know if the script is in the wrong directory, you will not know it until the mission completes and you are greeted by the script error message. :(

Thanks!

**Comment by Khopa** [comment]
Hello LoneRegister, 

Thanks 😀 

Thing is, I have no way to know whether the user has configured the good installation directory. Say, he has both stable and openbeta version installed; and he made DCS Liberation point to stable version directory and then try to play with the open beta version. It's not going to work, even though everything will seem correct to DCS Liberation... 

So i devised that the best way to implement such safety, would be to display a message in game if it is detected that the state file cannot be written, so from next version, if something is wrong, you'll see this message while playing shortly after the mission has started :

![image](https://user-images.githubusercontent.com/2546901/90698244-90b9ac00-e280-11ea-9168-9a5852c2ccd6.png)

(This message will keep appearing regularly in order to incite the player to exit the mission and fix the problem.)

Khopa

**Comment by loneregister** [comment]
OMG! you are amazing.  Because I am 'merde' at following directions, I have flown 4 missions (all of them with awesome kill ratio's etc.. (of course), and had the script wrong.).

Thank you, very, very much.

**Comment by Khopa** [comment]
Closing, since this has been added to 2.1.0. 😄
