### ISSUE TITLE
Have an option to remove the message that pops out saying unable to write dcs liberation state

### ISSUE THREAD

**Issue by Moguy164** [dcs-liberation/dcs_liberation#766]
Before filing, please search the issue tracker to see if this feature has already been requested.

**Is your feature request related to a problem? Please describe.**
yes, sometimes i like to do the campaign and give my friend to host, but since he isn't doing the campaign we keep getting this warning and it can get annoying fast

**Describe the solution you'd like**
an option to disable warning in liberation settings
**Additional context**

**Comment by MaHuJa** [comment]
If the mission is hosted 'elsewhere', that DCS instance need to be 'de-secured' so it can write the file that contains the results or outcome. This has not happened, so the results of the mission will stay in DCS and can never reach liberation.

Thus, you're not really playing liberation, thus the error message.

(You'll then need to 'manually submit' the state.json created on the server.)

**Comment by DanAlbert** [comment]
Yeah, this isn't a warning, it's an error. If you're seeing this message your game is broken, likely for the reasons described in the message. If the host machine isn't running liberation you need to manually patch the `MissionScripting.lua` before it'll work, but it'd be easier to just launch liberation on the other machine (you don't need to generate the campaign there, just make sure liberation is open when DCS starts).

If you're seeing it _only_ on client machines something weird is going on because mission lua scripts aren't supposed to run on client machines. It doesn't sound like that's the case though. If I'm wrong lmk and we'll reopen, but from the description it sounds like this message is entirely correct and suppressing it will just leave you with a silently broken game instead of a noisily broken game.

**Comment by Moguy164** [comment]
understood thank you
