### ISSUE TITLE
Western Georgia: Plane not landing at airfield different from takeoff

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#773]
**Describe the bug**
Created CAS mission for two A10C-II planes that would take off from Kobuleti and land at Sukhumi-Babushara.  However the planes land back at Kobuleti.  Liberation does recognize that the planes will be transferred however.

**To Reproduce**
1. Create campaign Caucasus - Western Georgia, Player: USA 2005, Enemy: Russia 1990
2. Purchase planes and play a few rounds  (Make sure to purchase A10C-II aircraft at Kobuleti
3. Create CAS mission where Departure airfield is Kobuleti and Arrival Airfield is Sukhumi-Babushara
4. Play the mission and watch the A10s land at Kobuleti instead of Sukhumi-Babushara.

**Expected behavior**
Offending A10Cs to land at Sukhumi-Babushara, their assigned landing airfield, instead of the same one that they took off from.

**Additional information**

Campaign, Mission, Tacview, Track.

Hosted by WeTransfer, link expires in a week:
https://we.tl/t-ifewRNL55h

**Version information (please complete the following information):**
 - DCS Liberation 2.3.4

**Comment by DanAlbert** [comment]
Their landing waypoint is clearly set at Sukhumi. If the AI isn't doing what we say there isn't really anything we can do about it. My guess is that the winchester/bingo RTB procedure the AI does always returns to the origin airfield rather than the landing airfield.

Not really an issue though, The aircraft will be transferred regardless of where they actually land.

**Comment by Mustang-25** [comment]
Going to mark this one as closed since Liberation really has no control over what the AI does with regard to this.
