### ISSUE TITLE
AI DEAD move to egress immediately if they cannot see targets when the reach ingress

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#774]
**Describe the bug**
I created a DEAD flight and the flight flew direct from Ingress to Egress instead of attacking the target.

**To Reproduce**
1.  Make a DEAD flight of F18s.
2.  Have SAM be inactive (not emitting)
Not sure how easy this one is to reproduce.  It's probably a special case, see the attached mission/campaign/track.

**Expected behavior**
Flight to attack SAM somehow I guess?  If SAM is protected by Tors and the like this may be a bad idea.

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:
Reusing previous used upload, was from the same mission.  Includes:  campaign, mission, track, tacview.

Hosted by WeTransfer, link expires in a week:
https://we.tl/t-ifewRNL55h

**Version information**
 - DCS Liberation 2.3.4:

**Additional context**
Mostly trying to raise awareness to this edge case.  I used Combined Arms to get the flight to attack the SAM.  The SAM search radar is overlapped by another vehicle, unsure if it's that causing the issue or the SAM not emitting causing the issue.

**Comment by Starfire13** [comment]
Your DEAD flight is probably armed with HARMs. The Hornets can't fire HARMs at a SAM site that isn't emitting because there is nothing to lock on to.

**Comment by HighwaymanEd** [comment]
DCS will use munitions in a specific priority for a role too.

If a Hornet is armed with HARMs and AGM-65, the unit will attempt to use the HARM as the weapon of choice as it is a dedicated DEAD/SEAD weapon whereas the AGM-65 is not, therefore, the AI sees it as thus; If I have a DEAD weapon, and my role is DEAD, then the DEAD weapon must be used before using anything else.

Also, unless it's been updated since I last checked the logic, if an AI unit is 'OFF' (not dead), the AI will not 'see' it and treats it like it doesn't exist, so if the radars are being turned off by the Skynet script by turning the group or unit AI off, the DCS AI aircraft will not see the unit to kill it. I don't know how the Skynet script actually works, I'm working from educated guesswork from how I've seen other scripts work to simulate 'Smart SAMs'

**Comment by DanAlbert** [comment]
The problem is that the AI only goes after targets that it detects and otherwise flies its flight plan. The flight plan is conservative to avoid continuing to fly toward a target it has already fired at, but that means sometimes it doesn't detect the target.

It's probably fine to plan them more aggressively. The flight will RTB when it's out of ammo anyway.

**Comment by Ryanwtod** [comment]
A temporary work around would be to have a 2 flight package, one setup as SEAD and the other as strike with JSOW or Maverick

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/930 has a lot of additional data for this problem. I'm broadening the title here to be a catch-all for "AI can't find targets immediately so goes home".

**Comment by Zwibber** [comment]
I don't mean to revive a dead thread or pretend to act like I know more than you guys but especially after looking at #930 I may have some additional insight:

- When creating a DEAD flight with any aircraft capable of carrying HARMs, the advanced waypoints options in the mission editor will be set to: ATTACK TARGET with GUIDED regardless of the payload set in the dynamic engine.  If no such weapon is loaded, the attack will not be conducted.
- When creating a DEAD or SEAD flight with B52s or F117s, there will not be any advanced waypoint options in the mission editor so of course the flight is going to go from ingress to egress without doing anything.
- When creating a STRIKE flight with B52s or F117s, there will be one task for the B52 to release all BOMBS at the first unit of the group (again regardless of payload selected) and as many bombing tasks as there are targets in the group for the F117s which they will then do with the option "GROUP ATTACK". This means they will only attack the first two targets.

I don't think this has anything to do with AI behavior and them "not seeing any targets". Instead I am certain this has something to do with the waypoint options for their created flight plan in the mission editor.

**Comment by DanAlbert** [comment]
> When creating a DEAD flight with any aircraft capable of carrying HARMs, the advanced waypoints options in the mission editor will be set to: ATTACK TARGET with GUIDED regardless of the payload set in the dynamic engine. If no such weapon is loaded, the attack will not be conducted.

https://github.com/dcs-liberation/dcs_liberation/issues/269

> When creating a DEAD or SEAD flight with B52s or F117s, there will not be any advanced waypoint options in the mission editor so of course the flight is going to go from ingress to egress without doing anything.

File a new bug with a save and a miz. Just plain not having waypoints actions is not a problem we've heard before afaik.

> When creating a STRIKE flight with B52s or F117s, there will be one task for the B52 to release all BOMBS at the first unit of the group (again regardless of payload selected) and as many bombing tasks as there are targets in the group for the F117s which they will then do with the option "GROUP ATTACK". This means they will only attack the first two targets.

https://github.com/dcs-liberation/dcs_liberation/issues/244

**Comment by Zwibber** [comment]
> File a new bug with a save and a miz. Just plain not having waypoints actions is not a problem we've heard before afaik

#1086

**Comment by DanAlbert** [comment]
Should be significantly improved now.

* Winchester decisions have been improved
* Bullets were taken away from AI for non-gunfighters for some mission types so that the winchester option actually works
* Weapon selection for DEAD flights is now auto instead of whatever it was before so they'll attack even if they have bombs instead of ARMs (mixed loadouts often do not work and it's a DCS bug, so nothing we can do: https://forums.eagle.ru/topic/271941-ai-rtbs-after-firing-decoys-despite-full-load-of-bombs)
* The DCS task was switched to CAS to allow more airframes
