### ISSUE TITLE
ZULU time on virtual kneeboard

### ISSUE THREAD

**Issue by HILOK** [dcs-liberation/dcs_liberation#792]
**Is your feature request related to a problem? Please describe.**
SETTING TOT IN THE HORNET REQUIRES ZULU TIME TO BE ENTERED (NOT LOCAL TIME)

**Describe the solution you'd like**
KNEEBOARD (AND BRIEFING PAGE) SHOULD SHOW ZULU INSTEAD OF LOCAL TIME

**Additional context**
AS FAR AS I AM AWARE IN AVIATION (AND MILITARY) TIMING ALWAYS REFERS TO ZULU.
ALTHOUGH I FIND THE LOCAL TIME IN THE PLANNER VERY USEFUL, I WISH WE COULD HAVE ZULU TIME IN PARENTHESES NEXT TO IT AS WELL.

THANKS

**Comment by DanAlbert** [comment]
Main reason this hasn't been done is because I haven't taken the time to figure out how DCS actually handles timezones, so it's not obvious how to translate from local to zulu. Most DCS maps include territory with more than one time zone (some using DST), and time zones shift a lot over time.

I'm guessing DCS does nothing with that and every map just has a single UTC offset, but need to test that theory before we can do this.

Also... caps lock.

**Comment by HILOK** [comment]
thanks for your quick reply, danalbert. i can see where the problem lies. didn't know there were even different time zones within one map. however, that actually enforces the necessity for zulu usage : )
thanks for pointing out capslock: that was actually intentionally to distinguish from paragraph titles (didn't expect those to turn out bold) : D

**Comment by DanAlbert** [comment]
Feature is present. It's configured per aircraft and at the moment we have only configured the hornet. If there are other aircraft with clocks that default to Zulu rather than local, let us know.

**Comment by oliverw** [comment]
The Apache for instance.
