### ISSUE TITLE
more varied weather

### ISSUE THREAD

**Issue by HILOK** [dcs-liberation/dcs_liberation#836]
**Is your feature request related to a problem? Please describe.**
in the PG lite scenario (dunno for other ones), temperature and QNH always stay the same (20deg, 2992inhg), although wind, clouds, rain do change over time.

**Describe the solution you'd like**
could we please have more variety for temperature and pressure?

**Additional context**
if that is of any help, i could offer to look up weather stats and provide a range of realistic values per season per region.

**Comment by magwo** [comment]
+1 from me!
It seems it would be fairly straightforward to randomize pressure and temperature within reasonable intervals. A small, conservative randomization would be great. It doesn't really need to be realistic.

In the real world, pressure is a very important aspect of aviation. It would be a dangerous habit to stop checking your altimeter setting, which is what gradually happens when you always fly missions with 29.92.

Similarly, temperature has a pretty big impact on takeoff speeds, runway needed and maximum takeoff weight. It's a good habit to check temperature and estimated rotation speed before taking off.

**Comment by magwo** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/1428

**Comment by HILOK** [comment]
thanks again for adding weather enhancements @magwo ! where can i find the version including these? thanks.

**Comment by magwo** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/1438

**Comment by magwo** [comment]
@HILOK Currently there's no version released, it will be on the development branch.

**Comment by HILOK** [comment]
is that the green button labeled "code"?

**Comment by magwo** [comment]
@HILOK This is now on the development branch. Expect to see the feature in an upcoming release.

Pressure, temperature, weather types (rain/cloud/clear/thunder) and night-time adjusted temperatures.
