### ISSUE TITLE
Build 1201: AI Aircraft Flying Too Slow

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#892]
**Describe the bug**
AEW&CS and BARCAP flights are flying at near stall speed  (E-3 at 173kts and 35000 feet, and F-15s at 152kts at 32109 feet).  BARCAP lead is using full burner to stay at altitude.

**To Reproduce**
1. Create Invasion Of Iran Campaign Summer 2010 and USA 2005, Iran 2015
2. Disable invulnerable AWACS
3. Create ASAP AEW&C (E-3A) flight to from Ras Al Khaimah to orbit at Havadarya
4. (In a different package) Create (mine was the earliest Liberation AI generated) BARCAP (F-15C) from Havadarya on Havadarya
5. Create other packages as normal
6. Have no player flights
7. Fly

**Expected behavior**
AEW&CS flights should not be at near stall speed.  BARCAP should not be using burner to not stall.

**Additional information**
[Campaign, Mission, and Tacview](https://github.com/Khopa/dcs_liberation/files/5979589/Build_1201_InvasionOfIran_AI_Planes_Stalling.zip)

**Version information (please complete the following information):**
 - DCS Liberation Build #1201

**Additional context**
I did notice a lot of the BARCAP flight "Racetrack start" waypoints' have speeds hovering around 50kts.

Observe the air speeds.
![AEWACS](https://user-images.githubusercontent.com/74509817/107907707-a2b79700-6f11-11eb-81a3-dd94cbb54587.png)
![F15](https://user-images.githubusercontent.com/74509817/107907745-b9f68480-6f11-11eb-8866-d5ab4a275c0a.png)

**Comment by DanAlbert** [comment]
This is _probably_ a DCS issue. AI pilots break themselves bloke this quite often. However given that this is happening with new start types and with new missions types we need to verify that it's not just a bad flight plan.

**Comment by SnappyComebacks** [comment]
I did notice that the orbit waypoint for the E-3 was set to ~170kts, but the Advanced Options at the orbit waypoint had the action to 350kts.  When I was watching the E-3 climb to altitude I watched it's airspeed steadily decrease.  I think it's possible that the Advanced Actions orbit option is ground speed and not airspeed, so the plane _is_ traveling at 350 but its airspeed is way lower.

It would be good for someone who has more experience with the mission editor to look though.

**Comment by DanAlbert** [comment]
Climbing is one of the things they do badly. If the AI does not make it to their orbit altitude before reaching the orbit waypoint they very ineffectively climb in a circle.

That's also usually one of the causes for other flights. The AI will not climb if their wingman is not formed up, so if the wingman takes too long to form up they will not have time to climb. I raised a bug with ED for this and their response was essentially "don't do that", but we have very few options for avoiding it since we can only guess at how much space the AI needs to climb.

But also yes, ME speeds are ground speeds, and 350kts ground speed at 35k ft is very slow.

**Comment by Meyomyx** [comment]
Probably the cause of this ..... but not certainly!

https://youtu.be/pogMyDMP1rw

**Comment by DanAlbert** [comment]
3.0 removes a lot of the pessimism in speed planning. If this was a case of being just _slightly_ too slow, that'll be fixed. If they've failed entirely it's pilot error and there's not a lot I can do to fix that.

If there are still any cases of flights being _planned_ slow (remember that the ME lies about the speed for anything after a hold point, or for the first point of a late-activated flight; the ME doesn't know when the waypoint becomes active so it assumes the aircraft has been traveling since mission start), upload a fresh save and miz and we'll reopen.
