### ISSUE TITLE
Waypoint Headings in Kneeboard

### ISSUE THREAD

**Issue by clutchtomcat** [dcs-liberation/dcs_liberation#915]
Redirected from Discord. Clarification on request: Headings from one waypoint to the next, not from current position to waypoint.

**Is your feature request related to a problem? Please describe.**
Older aircraft without nav systems, or limited nav systems that can only handle fewer waypoints than what Liberation generates (F-14), are reliant on a compass and stopwatch. 

The only way to get headings is the ruler in the F10 map. The F10 map causes significant performance issues and crashes in VR. Warbirds and other jets lacking autopilot (F-5) are a crash risk when using F10 map; many warbirds only have single axis trim so trimming it out isn't an option either. Clients cannot pause during multiplayer to use the F10 map in safety. 

**Describe the solution you'd like**
Headings between waypoints in the kneeboard. This is standard in real-world kneeboards, as is distance between waypoints, but that could get messy with imperial/metric conversions depending on what aircraft/faction you're flying for. If possible, distance is useful for route timing when joining a package.

**Comment by benedikt-wegmann** [comment]
I agree that headings should be in the "nav log", I just fear that a reliable mag heading isn't easy to derive outside of DCS. Remember that the kneeboard gets rendered before you even launch DCS.

I intend to improve the kneeboard further, if I can, and can try to look into this issue as well.
Maybe @DanAlbert can point me towards a starting point again? :wink: Perhaps an example in the code where calculations around waypoints are made, maybe similar to measurement of distances.

**Comment by DanAlbert** [comment]
I don't remember how the magnetic/true orientation happens in the game. Is it a part of the weather, and thus part of the briefing? Or is it fixed per map? If so, probably reasonable to just put the true headings on the kneeboard and let the pilot sort out the details.

I'm not sure how precise DCS is with headings in their projection. If world coordinates are orthogonal then we have that, but I think they are projected, and [we don't know what the projection is](https://github.com/Khopa/dcs_liberation/issues/91). If it is projected, we can't do anything about this without figuring out the projection parameters for each map :(

**Comment by benedikt-wegmann** [comment]
I feared that this was somewhat murky. Especially since we have to deal with it *outside* of DCS. Every module or LUA plugin can deal with it situational in DCS and in the mission.
I will keep an eye out for this issue @clutchtomcat when I work on the kneeboard again, but it may be a non-obviously difficult problem. :(

**Comment by DanAlbert** [comment]
If you feel like trying to solve for (not sure if that's possible) or brute force the projection parameters, DCS uses an inverse mercator projection for all its maps, I believe. We actually can get the parameters for the projection for the Caucasus, but for every other map the parameters are DRM'd :(

pyproj can do all the work if you find the parameters. If that sounds like something you want to try, I can upload a PR tomorrow showing how I did it for the Caucasus map. I shelved the work since what I had wouldn't work anywhere else until I got around to brute forcing the parameters for the other map. I have no idea how difficult that would be.

**Comment by benedikt-wegmann** [comment]
Hm, this sounds even more complicated than I expected.
I initially thought that if distances can be calculated, directions should be calculable, too, right? (I may be naive here)

**Comment by clutchtomcat** [comment]
I believe magnetic declination is dependent on map and even year selected in the mission. However, the aviation rule is "written is true," so anything in the kneeboard would be true heading. I don't suppose that makes it any easier considering the projection method conundrum.

**Comment by DanAlbert** [comment]
> I initially thought that if distances can be calculated, directions should be calculable, too, right? (I may be naive here)

Up is not necessarily due north :( If you look at the grid lines on the map you'll see that they are not exactly vertical/horizontal. The information we have in liberation is just the X/Y coordinate, and those are only directly aligned with the cardinal directions at the projection's meridian and equator, aiui.

**Comment by benedikt-wegmann** [comment]
Ah, I see. So the flight planner can calculate a distance and *some* direction between two points on the grid, but the grid is not aligned to cardinal directions. How unfortunate. 😭

**Comment by DanAlbert** [comment]
[The preview of the Falklands map that razbam posted](https://scontent-sjc3-1.xx.fbcdn.net/v/t1.0-9/153577245_3726931144060163_6636752236050859213_o.jpg?_nc_cat=110&ccb=3&_nc_sid=730e14&_nc_ohc=1ohM-SJOHUAAX_ol3CA&_nc_ht=scontent-sjc3-1.xx&oh=27ca75751b92d1990586acd1834d0bb8&oe=605B39CE) shows the problem pretty well since it's so far from the equator. "Up" is pretty close to 0 degrees at the right edge of the map, but is more like 5 degrees at the left edge.

I should add though that I have a pretty hard time wrapping (if you'll pardon the pun) my head around the cartographic problems, so maybe I'm wrong.

**Comment by DanAlbert** [comment]
> so maybe I'm wrong.

I checked on the channel map today and DCS pretty clearly just ignores this detail. Using the ruler to draw a line north on one of the non-vertical longitude lines on the map shows a non-0 heading.

In other words, we can ignore all the complicated parts I was worried about because DCS also ignores them.
