### ISSUE TITLE
Adding Waypoints Deletes TOTs

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#920]
Before filing, please search the issue tracker to see if the issue has already been reported.

**Describe the bug**
Adding waypoints seem to have adverse effects on kneeboard info. As pictured below, it deletes all the TOTs

**To Reproduce**
1. Create a flight plan
2. add a new waypoint 

**Expected behavior**
Given that new waypoints are added at the end of the flight plan, adding a waypoint should have no effect on TOT of the existing flight plan.

**Version info**
 - Build 1234

Before:
![image](https://user-images.githubusercontent.com/72566076/108881427-27608000-75b8-11eb-8e43-238cb1c93487.png)

After:
![image](https://user-images.githubusercontent.com/72566076/108881537-44954e80-75b8-11eb-96aa-7e9c4b984218.png)

![image](https://user-images.githubusercontent.com/72566076/108882006-c5ece100-75b8-11eb-89a8-7a7526a73db3.png)

**Comment by DanAlbert** [comment]
This is expected. We can't reason about a custom flight plan.

**Comment by Mustang-25** [comment]
> This is expected. We can't reason about a custom flight plan.

I understand that adding in extra waypoints into the middle of the flight plan would mess up the TOTs but can it just be set where the waypoints added at the end have no TOT and don't delete the other TOTs? I just use them as extra target reference points anyway so I don't want or need TOTs for them.

**Comment by DanAlbert** [comment]
Under the covers there are no ToTs to delete. They're calculated based on the flight plan (any time something about the flight plan changes they need to be recalculated, and for many types of flights that can include changes to other flights in the package). When you make a custom flight plan it's converted from a strike flight plan to a custom flight plan, and those have no way of calculating ToTs because they don't know what type of flight plan they are.

There's no fixing this without a complete overhaul of our waypoint system. Realistically I don't think that's going to happen, at least not any time soon.

It's a rigid and annoying system, but the less rigid system we had was constantly broken for TOT estimation so this is what we have until someone with way more time on their hands decides they want to spend it all on this.

**Comment by Mustang-25** [comment]
Ah, ok. Good to know!
