### ISSUE TITLE
BUG: Syria 2011 Faction- MiG-29S/A

### ISSUE THREAD

**Issue by KidChar13magne** [dcs-liberation/dcs_liberation#93]
The Syria side in DCS only has the MiG-29A, while the Syria 2011 faction in Liberation has the MiG-29S listed.

**Comment by MedievalBunny** [comment]
The Syrian Air Force, in real life, flies a Syria-specific variation of the MiG-29SM. In DCS the MiG-29S is the closest in capabilities to the MiG-29SM, and Syria has demonstrated R-77 capability as well. 

So, in this case, Liberation is actually more realistic than DCS's factions.

**Comment by KidChar13magne** [comment]
That makes sense, and I'm definitely all for realism. I suppose the bug is on the DCS side, then- any MiG-29S that is placed by Liberation will be replaced by an AJS37 in the sim.

**Comment by Khopa** [comment]
It will only appear as AJS 37 if you click on the unit in the mission editor. This is only DCS ME being confused because it does not expect this unit in the Syrian faction. See : 

![image](https://user-images.githubusercontent.com/2546901/90961899-53d1fd00-e4ac-11ea-8b52-7d0ea3020111.png)

If you don't mess around with the units, it should work fine.However, it will make you unable to change the units payload or waypoints in the Mission Editor without breaking it though...

But if you launch the mission, it will appear as a Syrian Mig-29S even though DCS doesn't allow to do this in Mission Editor : 

![image](https://user-images.githubusercontent.com/2546901/90961864-12d9e880-e4ac-11ea-8021-10adbde974d8.png)

**Comment by KidChar13magne** [comment]
Thank you both for your input! I did want to change the loadouts in ME, so I added the MiG-29S under Syria's faction list in DCS.
For anyone who wants to do this, add the line:
	cnt_unit( units.Planes.Plane, "MiG-29S");
under the --Syria section in db_countries.lua, located at DCS World/Scripts/Database.
