### ISSUE TITLE
AI does not appear to plan TARCAPs over frontline

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#940]
Before filing, please search the issue tracker to see if the issue has already been reported.

**Describe the bug**
AI does not plan TARCAP over frontlines even when adequate number of aircraft are available. Example scenario attached with maximum aircraft available at all airfields and lots of money. Not a single TARCAP.

[Tarcapnea.zip](https://github.com/Khopa/dcs_liberation/files/6095125/Tarcapnea.zip)

**Comment by DanAlbert** [comment]
This is because front lines don't project a threat zone (which is self-fulfilling, since that means they won't get TARCAPs). Fixed that, which also means that packages will now be smart enough to avoid blundering through the front line when it's cheap enough to go around.

It might be worth dialing down the engagement range for TARCAPs, but with the current planning style (single bubble around the aircraft, rather than a line of bubbles down the front line) the range is just a bit larger than the max length of the front line, so if we shrink it much then a TARCAP at one leg of its race track won't defend the other end of the track.
