### ISSUE TITLE
Tanker and AWACs location

### ISSUE THREAD

**Issue by Spartan111sqn** [dcs-liberation/dcs_liberation#952]
**Is your feature request related to a problem? Please describe.**
I see the tankers and AWACs location very artificial, the have to be in immortal and invisible for that.

**Describe the solution you'd like**
Locate AWACs on friendly zone at no less than 80nm from the border.
Locate Tankers around 50nm from the border or the most forwarded CAP around its zone.
Both no invisible either immortal

**Additional context**
Always both well defended by SAMs or ships in the friendly area

**Comment by Nosajthedevil** [comment]
**Additional context**
Maybe consider assigning them costs that would need to be paid to replace or repair like any other asset, but also allow BARCAP missions be assigned to them. I don't know if the easiest / best approach is to have fixed spots for each support AC that change as the most forwarded CAP changes or if they should be treated similar to the carrier groups where they can be moved when the mission is set up at the users discretion. I kind of like the latter, but since AI factions wouldn't move theirs to reflect the changing landscape maybe that's not the best approach. Just my 2 cents.

**Comment by DanAlbert** [comment]
Duplicate.

**Comment by Spartan111sqn** [comment]
I already realize that it has been already written before.

Thanks for answering!
