### ISSUE TITLE
Turn running without human interaction

### ISSUE THREAD

**Issue by Spartan111sqn** [dcs-liberation/dcs_liberation#953]
**Is your feature request related to a problem? Please describe.**
It seems that there is no big changes (except in front line) when human is not flying. Even more at the time that the human is flying the planned ATO is executed, when the human land and exit, the remain flights pendind to departure never take place.

**Describe the solution you'd like**
Use statistic to determine the result in all the topics, aircraft losses/wins, SAMs destroyed, repairs, etc

**Additional context**
on such way the feeling is that there is a war even if the human is not acting directly on it.

**Comment by alrik11es** [comment]
As a new player for this I thought the campaign worked like that. But I saw the same if I want to play only through the game map seems not possible.

**Comment by alrik11es** [comment]
I've been watching the code and it seems that a change about this kind must be done on the file `game/game.py` as a starting point. Something like `PlannedFlightResolver` class where you input all or every flights depending on it's side and calculates the effects based on some kind of statistics and randomness. The depth of this `PlannedFlightResolver` class is something that needs to be discussed here because depending on the depth it's harder or simpler to do. I'm going to start a concept branch on my fork about this topic to investigate about this.

Meanwhile I would like to discuss some ideas about this topic from other developers too.

**Comment by DanAlbert** [comment]
I don't think the implementation is the hard part, figuring out how to simulate this in any adequate way is. What's your plan for that?

I think a super dirty "60% of missions succeed" or similar would be a nice debugging tool, but players are going to have much higher standards.

**Comment by alrik11es** [comment]
You're right that players will want something more. Well a fully complete simulation is obviously discarded because you have DCS for that. So we need to start with a minimum and what you've proposed seems at least a starting point. I was thinking more in a system where we point from 1 to 10 for every unit and depending on its mission and this punctuation added to the number of units of a package gives a strength that could be opposed to strength of the enemy units in the vicinity of their objective. 

Variables to have in account for each package.
Strength points, Number of weapons, Mission Type, Objective, Time on mission

So for example.
F18 package with TARCAP mission with 12pts strength in frontline objective with time on target of 18 minutes.
On the other side SU25 8pts strength with CAS mission to frontline with time on target of 20 minutes.
If any package with mission TARCAP or BARCAP has time on target <= than any other aerial unit in the vicinity of their objective will fight with those units.
This "battles" should be resolved on each turn if the player push the pass turn button.

Something like this is what I had in mind. What do you think? Maybe is too much work.

**Comment by DanAlbert** [comment]
> I was thinking more in a system where we point from 1 to 10 for every unit and depending on its mission and this punctuation added to the number of units of a package gives a strength that could be opposed to strength of the enemy units in the vicinity of their objective.

I like this a lot because we can also use it for flight plan optimization.

> Maybe is too much work.

I think if you start simple (score aircraft and only aircraft) it'd give a good idea of scope, and if that works out it will have built the framework we need and the rest is just tuning.

Plan sounds reasonable to me :)

If you're in Discord ping me (ColonelPanic) and I'll get you added to the dev channel.

**Comment by KeeseAF** [comment]
Ive looked for like 20 minutes for something like this and i couldnt find it. commenting to follow along for any further discussion/ action

**Comment by DanAlbert** [comment]
This button on the side of the page will let you subscribe without commenting, btw (it will say "subscribe" if you're not subscribed): ![image](https://user-images.githubusercontent.com/315852/124678651-d0c55580-de77-11eb-8214-c52f7712ec75.png)

**Comment by DanAlbert** [comment]
Superseded by https://github.com/dcs-liberation/dcs_liberation/issues/1680
